### PR TITLE
Use Hadoop 3 exclusively for Accumulo 2.0

### PR DESCRIPTION
**Pull request by ctubbsii**

### CODE REVIEW

**Comment by ctubbsii** [comment]
I tested this with [uno] and Hadoop 3.0.2 and it worked fine.

[uno]: https://github.com/apache/fluo-uno

**Comment by joshelser** [comment]
> I tested this with uno and Hadoop 3.0.2 and it worked fine.

Have you tried 3.1.0? Last I heard, 3.1.0 is closer to what they'll call "GA" than 3.0.x

**Comment by ctubbsii** [comment]
I did not see 3.1.0 on the Hadoop website! I saw 3.0.3 as the latest, but it wouldn't download from Maven, so I dropped back to 3.0.2. I would be happy to try with 3.1.0, though.

**Comment by ctubbsii** [comment]
I found it. It was further down on the list.

**Comment by ctubbsii** [comment]
3.1.0 seems to have problems with resource utilization on my laptop... I'm not able to get it to run, but I'll try on a beefier machine another time.

**Comment by mikewalch** [comment]
What happens if a user tries to use Accumulo 2.0 with Hadoop 2.x?  If there isn't a proper error message currently, I think it would be good to create an issue.

**Comment by ctubbsii** [comment]
@mikewalch We're not banning the use of Hadoop 2.x... we're just changing the build and testing to expect it by default. It's possible it will still work... if the user deploys it with an appropriate class path (in fact, it definitely still works now). This isn't about forcing users to use a particular version... it's just about what we're focusing our support around.

Similarly, we wouldn't give an error message if a user used log4j 1.2.15, even though we're using 1.2.17; I don't think we should give an error message here, either.

**Comment by mikewalch** [comment]
@ctubbsii, sounds good to me. I thought this PR meant Hadoop 2.x would not work in the future. I didn't want users to get weird errors and not know it was due to using Hadoop 2.x. If it "works" but it isn't officially supported, that works for me.

**Pull request merged**
