### PR TITLE
Bump libthrift to 0.16.0

### PR DESCRIPTION
**Pull request by ctubbsii**

### CODE REVIEW

**Comment by ctubbsii** [comment]
> There is one CVE listed for 0.16, but I don't think we are affected by it.

Can you provide a reference? I searched and couldn't find 0.16 mentioned in any.

**Comment by ctubbsii** [comment]
All ITs passed with this change.

**Comment by dlmarion** [comment]
https://issues.apache.org/jira/projects/THRIFT/issues/THRIFT-5579

**Comment by ctubbsii** [comment]
> https://issues.apache.org/jira/projects/THRIFT/issues/THRIFT-5579

Thanks. You're right about that not applying to us. We don't use the WebSockets stuff for Accumulo.

**Pull request merged**
