### PR TITLE
Added logging to try and find the cause of the intermittent ZK failures

### PR DESCRIPTION
**Pull request by dlmarion**
I want to push a commit into `main`, that can be reverted later, to try and get more information about the intermittent ZK failures in the ITs.

### CODE REVIEW

**Comment by milleruntime** [comment]
> I want to push a commit into `main`, that can be reverted later, to try and get more information about the intermittent ZK failures in the ITs.

Interesting... Do you want to see it run on Jenkins? I can run your branch on Github with the full set of ITs.

**Comment by dlmarion** [comment]
Yeah, if you could do that, that would be great. I tried running it via GH Actions, but it didn't fail with the ZK error and I don't think I can get in to see the workspace.

**Review by EdColeman — APPROVED** [review]
Being that these message are test-only and would not be seen in production I don't see an issue with merging and leaving them in place.  Because the issue is intermittent, we need the information logging in place *before* we see  the error -  once it occurs, the next run is likely to succeed - and that does not help isolate the potential issue(s)

**Comment by milleruntime** [comment]
FYI only one IT failed from my full run on Github.
<pre>
[ERROR] Errors: 
[ERROR]   TabletIT>AccumuloClusterHarness.setupCluster:167 » IllegalState Unable to find instance id from zookeeper.
[INFO] 
[ERROR] Tests run: 35, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[WARNING] Corrupted channel by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /home/runner/work/accumulo/accumulo/test/target/failsafe-reports/2022-08-03T19-40-17_134-jvmRun1.dumpstream
</pre>

**Comment by dlmarion** [comment]
This is interesting, might have to add a retry loop in the case where I'm trying to dump the ZK contents. MiniAccumuloClusterImpl started ZK, called Accumulo `Initialize`, but could not find the resulting instanceId. I'm going to make a couple of tweaks.

```
2022-08-03T19:49:19,303 [miniclusterImpl.MiniAccumuloClusterImpl] WARN : Starting ZooKeeper
2022-08-03T19:49:20,628 [miniclusterImpl.MiniAccumuloClusterImpl] WARN : Initializing ZooKeeper
2022-08-03T19:49:23,445 [miniclusterImpl.MiniAccumuloClusterImpl] INFO : Starting MAC against instance miniInstance and zookeeper(s) localhost:45451.
2022-08-03T19:49:29,347 [common.X509Util] INFO : Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
2022-08-03T19:49:39,460 [miniclusterImpl.MiniAccumuloClusterImpl] WARN : ******* COULD NOT FIND INSTANCE ID - DUMPING ZK ************
2022-08-03T19:49:39,460 [miniclusterImpl.MiniAccumuloClusterImpl] WARN : Connected to ZooKeeper: localhost:45451
2022-08-03T19:49:39,460 [miniclusterImpl.MiniAccumuloClusterImpl] WARN : Looking for instanceId at /accumulo/instances/miniInstance
2022-08-03T19:49:39,523 [miniclusterImpl.MiniAccumuloClusterImpl] ERROR: Error dumping zk
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /accumulo
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102) ~[zookeeper-3.7.1.jar:3.7.1]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54) ~[zookeeper-3.7.1.jar:3.7.1]
	at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:2028) ~[zookeeper-3.7.1.jar:3.7.1]
	at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:2056) ~[zookeeper-3.7.1.jar:3.7.1]
	at org.apache.zookeeper.ZKUtil.visitSubTreeDFS(ZKUtil.java:236) ~[zookeeper-3.7.1.jar:3.7.1]
	at org.apache.accumulo.miniclusterImpl.MiniAccumuloClusterImpl.verifyUp(MiniAccumuloClusterImpl.java:681) ~[accumulo-minicluster-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.miniclusterImpl.MiniAccumuloClusterImpl.start(MiniAccumuloClusterImpl.java:620) ~[accumulo-minicluster-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.harness.AccumuloClusterHarness.setupCluster(AccumuloClusterHarness.java:167) ~[classes/:?]
```

**Comment by milleruntime** [comment]
>  might have to add a retry loop in the case where I'm trying to dump the ZK contents.

I am not sure why we are initializing as a separate process [here](https://github.com/apache/accumulo/blob/5d3f4e57e8c59488bddb5a310cfd4baaa4c5b619/minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java#L582). The process could be returning a success code but Accumulo hasn't finished initializing. We might want to just call init directly and wait for Accumulo to finish initializing.

**Comment by dlmarion** [comment]
I did look down that code path to see if anything was multi-threaded and not waiting for things to complete. I didn't see anything, and the existing code waits for the process to complete (the next line down from your reference). What you are saying is an option though.

**Comment by milleruntime** [comment]
> What you are saying is an option though.

I started tinkering in my workspace and it shouldn't be too bad of a change. The refactoring I did with the Initialize classes should help. I think it would help with the flakiness of our ITs if we don't spin off a separate process for initialization.

**Comment by ctubbsii** [comment]
The advantages of using a separate process for initialization are:
1. It reflects how users initialize, and exercises that process,
2. It avoids tainting any JVM-wide static state from the initialization process in the IT client code, and
3. It avoids treating the IT code as inherently part of the server side of things. Most ITs behave as Accumulo clients, not server-side utilities, and shouldn't be running server code in-process.

I don't see why running initialize in-process would help. It should suffice to wait for the initialize process to complete successfully, and then, if necessary, synchronize the IT with ZK.

**Pull request merged**
