### PR TITLE
Update AmpleConditionalWriteIT to use new file metadata format

### LINKED ISSUE #3831: Broken or Flaky test: AmpleConditionalWriterIT
**Test name(s)**
 - AmpleConditionalWriterIT.testFiles()
 - AmpleConditionalWriterIT.testSelectedFiles()
 - AmpleConditionalWriterIT.testSelectedFilesReordering()

**Describe the failure observed**
All of the tests in AmpleConditionalWriterIT (and maybe more, I haven't looked yet) that create a `StoredTabletFile` are failing. I think this is due to the change to the `StoredTabletFile` constructor in 1ab0cc7808fb68568b5312235bdea15ea396b04a. Last known working commit is 83d2dc24e87641171b2aef3fa3e4e35dc94cf279.

The constructor while the test was working was:
https://github.com/apache/accumulo/blob/83d2dc24e87641171b2aef3fa3e4e35dc94cf279/core/src/main/java/org/apache/accumulo/core/metadata/StoredTabletFile.java#L47-L51
and is currently this:
https://github.com/apache/accumulo/blob/31323e5e5ecd870aff94fa6aa3579730031a651b/core/src/main/java/org/apache/accumulo/core/metadata/StoredTabletFile.java#L62-L64

It looks like the new constructor expects the given string to be a json that it can deserialize and the old code expects the string to be a file path.

**Testing Environment:**
 - Version of this project: elasticity

### PR DESCRIPTION
**Pull request by cshannon**
After the changes with no-chop merge the StoredTabletFile metadata is now a json string that includes a range along with the path. This change updates the test to serialize the path into the new format with an infinite range.

This closes #3831

### CODE REVIEW

**Comment by cshannon** [comment]
@keith-turner - I marked this as a draft as a draft as is still broken because the metadata Json is being converted to Json a second time and breaking the test and wasn't sure how to handle that yet and was wondering if you could take a look. The line that is breaking is: https://github.com/cshannon/accumulo/blob/3d92a635be6f341000899975e0f2129bb884ee6d/test/src/main/java/org/apache/accumulo/test/functional/AmpleConditionalWriterIT.java#L463

**Comment by cshannon** [comment]
Here is the output of the different Json strings:

`actualMetadataValue` variable:
```json
{"txid":"FATE[0000000000000002]","selAll":true,"files":["{\"path\":\"hdfs://localhost:8020/accumulo/tables/2a/default_tablet/F0000070.rf\",\"startRow\":\"\",\"endRow\":\"\"}","{\"path\":\"hdfs://localhost:8020/accumulo/tables/2a/default_tablet/F0000071.rf\",\"startRow\":\"\",\"endRow\":\"\"}","{\"path\":\"hdfs://localhost:8020/accumulo/tables/2a/default_tablet/F0000072.rf\",\"startRow\":\"\",\"endRow\":\"\"}"]}
```
`newJson` variable:
```json
{"txid":"FATE[0000000000000002]","selAll":true,"files":["{"path":"hdfs://localhost:8020/accumulo/tables/2a/default_tablet/F0000070.rf","startRow":"","endRow":""}","{"path":"hdfs://localhost:8020/accumulo/tables/2a/default_tablet/F0000071.rf","startRow":"","endRow":""}","{"path":"hdfs://localhost:8020/accumulo/tables/2a/default_tablet/F0000072.rf","startRow":"","endRow":""}"]}
```

**Comment by DomGarguilo** [comment]
The issue with the failing test case is how the test json is being created using `createSelectedFilesJson()`. I can make a PR against your branch to try to change this method to use GSON to construct this json to see if it solves the issue.

**Comment by cshannon** [comment]
I think the problem is the SelectedFilesTypeAdapter is including the json metadata string as part of the new json so it's escaping it. I tried to convert the the spot where it was outputting the json to use `out.jsonValue(file);` instead of [out.value(file)](https://github.com/cshannon/accumulo/blob/3d92a635be6f341000899975e0f2129bb884ee6d/core/src/main/java/org/apache/accumulo/core/metadata/schema/SelectedFiles.java#L72) but now it gets a conditional mutatnoi violation error on testing

**Comment by cshannon** [comment]
> Did the serialization of these jsons change? This seems to suggest that they are now serialized with the escape characters.
> 
> The issue with the failing test case is how the test json is being created using `createSelectedFilesJson()`. I can make a PR against your branch to try to change this method to use GSON to construct this json to see if it solves the issue.

@DomGarguilo - I actually I think you are right, i think this is just a test issue. We do want to escape it as it's embedded json and that is fine. The test just needs to account for it. I can make the change real fast.

**Comment by EdColeman** [comment]
Try the following:

```
public static String createSelectedFilesJson(Long txid, boolean selAll,
      Collection<String> paths) {
    String filesJsonArray = GSON.get().toJson(paths);
    String formattedTxid = FateTxId.formatTid(Long.parseLong(Long.toString(txid), 16));
    return ("{'txid':'" + formattedTxid + "','selAll':" + selAll + ",'files':" + filesJsonArray
        + "}").replace('\'', '\"');
  }

```

**Comment by DomGarguilo** [comment]
> Try the following:
> 
> ```
> public static String createSelectedFilesJson(Long txid, boolean selAll,
>       Collection<String> paths) {
>     String filesJsonArray = GSON.get().toJson(paths);
>     String formattedTxid = FateTxId.formatTid(Long.parseLong(Long.toString(txid), 16));
>     return ("{'txid':'" + formattedTxid + "','selAll':" + selAll + ",'files':" + filesJsonArray
>         + "}").replace('\'', '\"');
>   }
> ```

At this point we might as well use GSON to construct the whole thing right? But then we might end up rewriting the code that is used in `SelectedFilesTypeAdapter.write()`. Not sure if that would defeat the purpose of the test or if we can factor that out for use in the test and within `SelectedFilesTypeAdapter.write()`.

**Comment by cshannon** [comment]
> > Try the following:
> > ```
> > public static String createSelectedFilesJson(Long txid, boolean selAll,
> >       Collection<String> paths) {
> >     String filesJsonArray = GSON.get().toJson(paths);
> >     String formattedTxid = FateTxId.formatTid(Long.parseLong(Long.toString(txid), 16));
> >     return ("{'txid':'" + formattedTxid + "','selAll':" + selAll + ",'files':" + filesJsonArray
> >         + "}").replace('\'', '\"');
> >   }
> > ```
> 
> At this point we might as well use GSON to construct the whole thing right? But then we might end up rewriting the code that is used in `SelectedFilesTypeAdapter.write()`. Not sure if that would defeat the purpose of the test or if we can factor that out for use in the test and within `SelectedFilesTypeAdapter.write()`.

I think this is probably fine because it's just a test. We need to construct the json outside of using the adapter because one of the tests actually does reverse order and the adapter will sort.

**Review by DomGarguilo — APPROVED** [review]
> I think this is probably fine because it's just a test. We need to construct the json outside of using the adapter because one of the tests actually does reverse order and the adapter will sort.

Forgot about that.

Everything LGTM now.

**Review by EdColeman — APPROVED** [review]

**Review by DomGarguilo — APPROVED** [review]
New changes look good

**Pull request merged**
