### PR TITLE
Fix name of properties in FateLogger

### LINKED ISSUE #2469: FateLogger bug
The Fate logger will log properties set in ZK but the method in `ZooStore` appends to the property name `"/prop_" + prop` so what is logged by the logger won't match up what is in ZK.
https://github.com/apache/accumulo/blob/aab34a980d7a9ccad63797913b99b331c5cbbaae/core/src/main/java/org/apache/accumulo/core/logging/FateLogger.java#L128-L132

### PR DESCRIPTION
**Pull request by milleruntime**
* Make the variables in Fate.java the full name of their ZK properties
* Closes #2469

### CODE REVIEW

**Comment by milleruntime** [comment]
This fixes the name of the properties in ZK:
<pre>
[zk: localhost:2181(CONNECTED) 2] ls /accumulo/834e3388-d546-4712-b956-b0fbd6c8eba4/fate/tx_6e3fcce088dd7fe8 
[prop_autoClean, prop_debug, repo_0000000000, repo_0000000003]
[zk: localhost:2181(CONNECTED) 4] get /accumulo/834e3388-d546-4712-b956-b0fbd6c8eba4/fate/tx_6e3fcce088dd7fe8/prop_debug
S CompactRange
</pre>

The property names were being printed in the log without the full name:
<pre>
2022-07-26T11:21:50,432 [fate.store] TRACE: [FATE[5bf40f1bd45a2bec]] setProperty debug to CreateTable
</pre>

But with this fix, the full name of the property will now be printed in the logger:
<pre>
2022-07-26T11:50:13,661 [fate.store] TRACE: [FATE[37fb4ecc9b07e375]] setProperty prop_debug to CreateTable
</pre>

**Comment by EdColeman** [comment]
Is there some confusion between properties and node names, node data?

`setProperty prop_debug to CreateTable`

This is either creating the FATE prop_debug node with the data 'CreateTable` or modifying the data of an existing node.  For me, property has a stronger tie to configuration properties rather than to node names for FATES (or the transaction data stored on those nodes)  With the log statement reading `setProperty` I'd be inclined to think I could see / modify that with shell `config` command.

**Comment by milleruntime** [comment]
> Is there some confusion between properties and node names, node data?

The term `property` in within Fate is confusing. Yes, technically we are setting data to a ZK node. The `property` here is not the same as the Accumulo properties. Here it is an internal FATE property that is stored in ZK.

**Comment by EdColeman** [comment]
Can we rename it from property to something else then then?  data, txData, even txProp could help reduce confusion, but I'd lean to something without prop in it if it reads okay in the rest of the context.

**Comment by milleruntime** [comment]
> Can we rename it from property to something else then then? data, txData, even txProp could help reduce confusion, but I'd lean to something without prop in it if it reads okay in the rest of the context.

Rename what? The method on the TStore interface is called `setProperty`, along with the implementing classes. I could make the logger say something like:
<pre>
2022-07-26T11:21:50,432 [fate.store] TRACE: [FATE[5bf40f1bd45a2bec]] setting prop_debug to CreateTable
</pre>
I also think we can remove the "[ ]" around the fate Tx ID now that it has a prefix.

**Comment by EdColeman** [comment]
TStore is internal API, right?  Maybe a full rename waits for the FATE API redesign, but this *could* be an incremental step towards clarifying things that help inform the future API changes. 

But for just the log statement:

`2022-07-26T11:21:50,432 [fate.store] TRACE: [FATE[5bf40f1bd45a2bec]] setting prop_debug to CreateTable`
could be:
`2022-07-26T11:21:50,432 [fate.store] TRACE: [FATE[5bf40f1bd45a2bec]] setting prop_debug node data to CreateTable`

**Review by Manno15 — APPROVED** [review]

**Pull request merged**
