### PR TITLE
Ignore IntelliJ IDE .ipr and .iws files

### PR DESCRIPTION
**Pull request by benkelly**
-  Added the JetBrains IDE `*.ipr` and `*.iws` with are generated by IntelliJ.

---
Signed-off-by: ben <git@benjamin.ie>

### CODE REVIEW

**Comment by milleruntime** [comment]
Hi @benkelly thanks for the contribution!  Any idea how these are generated?  I am just curious since I use IntelliJ and haven't seen these files.  I also haven't updated to 2020.2 yet, I'm still on 2020.1.1

**Comment by benkelly** [comment]
Hi @milleruntime, in on 2020.2 they generate for me when I run `mvn idea:idea` after I run `mvn clean install -DskipTests`

https://maven.apache.org/plugins/maven-idea-plugin/usage.html

**Comment by milleruntime** [comment]
Ok thanks!

**Comment by milleruntime** [comment]
@benkelly thanks for the contribution and welcome to the Apache Accumulo community. If you would like to be listed as a contributor on Accumulo's people page please make a website PR for [people.md.](https://github.com/apache/accumulo-website/edit/master/pages/people.md)

If you intend to make more contributions, please consider subscribing to the [dev list](https://accumulo.apache.org/contact-us/) and introducing yourself. Also, you can use the dev list or slack to reach out if you have questions about anything.

**Comment by ctubbsii** [comment]
> Hi @milleruntime, I'm on 2020.2 they generate for me when I run `mvn idea:idea` after I run `mvn clean install -DskipTests`
> 
> https://maven.apache.org/plugins/maven-idea-plugin/usage.html

Off topic (unsolicited :smiley_cat:) advice: please don't use `mvn clean install` unless you *really* need to. Usually, `mvn clean verify` is sufficient.
See: https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#usual-command-line-calls and https://stackoverflow.com/questions/50260921/differences-between-mvn-install-and-mvn-verify
Many guides will suggest using `install` instead of `verify`, and this has led many Maven users to use it when they shouldn't. There are appropriate times to do use it, but they aren't common, and I think a lot of beginner Maven users have been misled by online guides. The only appropriate time to use `install` is when you actually need to have a copy of your built artifacts available in your local Maven repository. Otherwise, you should use `verify` (or just `package`, if you just need to build the artifacts, but don't need to run ITs afterwards).

**Comment by benkelly** [comment]
> > Hi @milleruntime, I'm on 2020.2 they generate for me when I run `mvn idea:idea` after I run `mvn clean install -DskipTests`
> 
> > 
> 
> > https://maven.apache.org/plugins/maven-idea-plugin/usage.html
> 
> 
> 
> Off topic (unsolicited :smiley_cat:) advice: please don't use `mvn clean install` unless you *really* need to. Usually, `mvn clean verify` is sufficient.
> 
> See: https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#usual-command-line-calls and https://stackoverflow.com/questions/50260921/differences-between-mvn-install-and-mvn-verify
> 
> Many guides will suggest using `install` instead of `verify`, and this has led many Maven users to use it when they shouldn't. There are appropriate times to do use it, but they aren't common, and I think a lot of beginner Maven users have been misled by online guides. The only appropriate time to use `install` is when you actually need to have a copy of your built artifacts available in your local Maven repository. Otherwise, you should use `verify` (or just `package`, if you just need to build the artifacts, but don't need to run ITs afterwards).
> 
> 
> 
> EDIT: Also, thanks for the contribution! :smiley_cat: 

Thanks for the advice! 😃 

I have been guilty of just pressing ⬆️ and re-hitting `mvn clean install` then actually using the more suitable command! 🤣

**Comment by ctubbsii** [comment]
FWIW, the problems that can happen with `install` are basically:

1. Filling up your hard drive with unneeded copies of SNAPSHOT builds
2. Misconfigured dependencies in your project could be unintentionally resolved from your local repository when they fail to resolve from your multi-module reactor build or from your remote repository, where you expect them to exist, but don't. This will result in builds that only work for you, but not for anybody else.
3. Confusing code breakage that can be hard to troubleshoot, because code is behaving the way you *used* to have it, but you *fixed that bug already*, and your Maven build is resolving from your local repository instead of the fixed version you intend on your class path.

I'm sure there are others, but these are the ones I've seen most often. Sometimes you need to, though. For example, if you need to build a dependency for the purposes of testing it in a separate Maven project's build. When that happens for me, I try to purge these artifacts from my local repository once I'm done, so they don't pollute future builds.

**Pull request merged**
