### PR TITLE
Better error message when instance.volumes does not specify the accumulo directory

### PR DESCRIPTION
**Pull request by Manno15**
Closes https://issues.apache.org/jira/browse/ACCUMULO-2809 

This no longer throws an NPE  but instead throws :

<details>
<pre>
java.lang.IllegalArgumentException: Can not create a Path from an empty string
	at org.apache.hadoop.fs.Path.checkPathArg(Path.java:172) ~[hadoop-client-api-3.3.0.jar:?]
	at org.apache.hadoop.fs.Path.<init>(Path.java:184) ~[hadoop-client-api-3.3.0.jar:?]
	at org.apache.hadoop.fs.Path.<init>(Path.java:119) ~[hadoop-client-api-3.3.0.jar:?]
	at org.apache.accumulo.core.volume.VolumeImpl.prefixChild(VolumeImpl.java:137) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.server.ServerConstants.getInstanceIdLocation(ServerConstants.java:175) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.server.ServerUtil.getAccumuloInstanceIdPath(ServerUtil.java:105) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.server.ServerInfo.<init>(ServerInfo.java:96) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.server.ServerContext.<init>(ServerContext.java:71) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.manager.state.SetGoalState.main(SetGoalState.java:47) ~[accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.accumulo.start.Main.lambda$execMainClass$1(Main.java:163) ~[accumulo-start-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:834) [?:?]
</pre>
</details>

With the change the message is now
<details>
<pre>
java.lang.RuntimeException: Accumulo cannot be initialized because basepath is empty. 
This probably means instace.volumes is an incorrect value
	at org.apache.accumulo.core.volume.VolumeImpl.prefixChild(VolumeImpl.java:129) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.server.ServerConstants.getInstanceIdLocation(ServerConstants.java:175) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.server.ServerUtil.getAccumuloInstanceIdPath(ServerUtil.java:105) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.server.ServerInfo.<init>(ServerInfo.java:96) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.server.ServerContext.<init>(ServerContext.java:71) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at org.apache.accumulo.manager.state.SetGoalState.main(SetGoalState.java:47) ~[accumulo-manager-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.accumulo.start.Main.lambda$execMainClass$1(Main.java:163) ~[accumulo-start-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:834) [?:?]

</pre>
</details>

I think this message could be improved and possibly moved if we decide to detect for this specific case earlier in the initialization phase.

### CODE REVIEW

**Review by ctubbsii — COMMENTED** [review]
Would a more specific RTE be appropriate? IllegalArgumentException or IllegalStateException out something else?

**Comment by Manno15** [comment]
Possibly. I followed what was in `VolumeManager` and that uses RTE. I'm fine with either but I am not sure they add anything to the error itself.

**Comment by ctubbsii** [comment]
> Possibly. I followed what was in `VolumeManager` and that uses RTE. I'm fine with either but I am not sure they add anything to the error itself.

More specific exceptions increase the caller's ability to handle them on a case-by-case basis. If a UI was designed to initialize and run Accumulo based on a user's input from a prompt for the volumes, for example, an IllegalArgumentException could be detected and cause the user to be prompted for a better value. A generic RuntimeException, on the other hand, would not imply any specific handling. So, a UI like I describe wouldn't be know whether to prompt for a new value, or do something else.

In general, more specific exceptions are best, whenever possible. It's usually just a matter of finding the right one, or creating one that is appropriate. We probably have lots of existing generic RTE uses throughout our code, but I try to catch new ones in pull requests, and fix old ones, as we go, because it is better to be more specific whenever possible.

**Comment by Manno15** [comment]
> More specific exceptions increase the caller's ability to handle them on a case-by-case basis. If a UI was designed to initialize and run Accumulo based on a user's input from a prompt for the volumes, for example, an IllegalArgumentException could be detected and cause the user to be prompted for a better value. A generic RuntimeException, on the other hand, would not imply any specific handling. So, a UI like I describe wouldn't know whether to prompt for a new value, or do something else

I understand, that makes sense in that scenario. I will make a change for `IllegalArgumentException` because I think that would fit best for this error.

**Review by ctubbsii — APPROVED** [review]

**Pull request merged**
