### PR TITLE
Update run-verify.sh to not fail when optional arguments passed are empty

### PR DESCRIPTION
**Pull request by karthick-rn**
This PR resolves the issue reported in #1695. Noticed the ZK lib change has already been done via PR #1716.

### CODE REVIEW

**Review by ctubbsii — COMMENTED** [review]
This is okay... but it might be better to use an array variable instead. Or, at the very least, a comment above it to hint to anybody investigating a shellcheck failure why the optional argument is unquoted.

My personal preference is to use the array syntax, so shellcheck is happy, and you pass the args robustly, regardless of whether they contain any whitespace:

```bash
AUTH_OPT=()
[[ -n $VERIFY_AUTHS ]] && AUTH_OPT=('--auths' "$VERIFY_AUTHS")

SCAN_OPT=('--offline')
[[ $SCAN_OFFLINE == 'false' ]] && SCAN_OPT=()

"$ACCUMULO_HOME/bin/tool.sh" "$SERVER_LIBJAR" org.apache.accumulo.test.continuous.ContinuousVerify -Dmapreduce.job.reduce.slowstart.completedmaps=0.95 -libjars "$SERVER_LIBJAR" "${AUTH_OPT[@]}" -i "$INSTANCE_NAME" -z "$ZOO_KEEPERS" -u "$USER" -p "$PASS" --table "$TABLE" --output "$VERIFY_OUT" --maxMappers "$VERIFY_MAX_MAPS" --reducers "$VERIFY_REDUCERS" "${SCAN_OPT[@]}"
```

**Comment by karthick-rn** [comment]
> ```shell
> AUTH_OPT=()
> [[ -n $VERIFY_AUTHS ]] && AUTH_OPT=('--auths' "$VERIFY_AUTHS")
> 
> SCAN_OPT=('--offline')
> [[ $SCAN_OFFLINE == 'false' ]] && SCAN_OPT=()
> 
> "$ACCUMULO_HOME/bin/tool.sh" "$SERVER_LIBJAR" org.apache.accumulo.test.continuous.ContinuousVerify -Dmapreduce.job.reduce.slowstart.completedmaps=0.95 -libjars "$SERVER_LIBJAR" "${AUTH_OPT[@]}" -i "$INSTANCE_NAME" -z "$ZOO_KEEPERS" -u "$USER" -p "$PASS" --table "$TABLE" --output "$VERIFY_OUT" --maxMappers "$VERIFY_MAX_MAPS" --reducers "$VERIFY_REDUCERS" "${SCAN_OPT[@]}"
> ```

@ctubbsii This is neat & thanks for sharing. Originally I intended to fix this without removing the double quotes but then ran into several issues. Also never thought of using an array to overcome this problem. This is great. I'll change the description of the PR and push an update soon.

**Review by ctubbsii — APPROVED** [review]
@karthick-rn This looks good to me. Thanks.

Even though I suggested going in the direction of the array, I didn't actually test it. Were you able to verify that this change fixed the issue and works with, and without, the auth opts or scan opts set?

**Comment by karthick-rn** [comment]
> Were you able to verify that this change fixed the issue and works with, and without, the auth opts or scan opts set?

@ctubbsii Yes, I tested the change with & without the optional parameters set, in both cases the continuous verify script did not throw the reported error.

**Review by keith-turner — APPROVED** [review]

**Comment by ctubbsii** [comment]
Thanks, @karthick-rn !

**Pull request merged**
