### PR TITLE
Minor hadoop-mapreduce cleanup

### PR DESCRIPTION
**Pull request by milleruntime**
* Drop unwrapping DelegationTokenStub and methods
* Drop exceptions never thrown

### CODE REVIEW

**Comment by milleruntime** [comment]
@ctubbsii I believe [this token unwrapping code ](https://github.com/apache/accumulo/pull/809/commits/691333f53ddc0ac4d840403e972765aee07865f1#diff-5eec2550f6fe8327e58d743712cd2960L334)I am dropping here is the same you are dropping?

**Comment by milleruntime** [comment]
> Was this used by anything? It looks like removal of unused code.

Nope.  It was unused.

**Comment by ctubbsii** [comment]
In that case, seems prudent to merge it, but it's not directly related to what I referenced.

**Comment by mikewalch** [comment]
Jenkins passed so ignore my last comment.

**Pull request merged**
