### PR TITLE
Integrate Accumulo-Access into Accumulo

### PR DESCRIPTION
**Pull request by dlmarion**

### CODE REVIEW

**Comment by dlmarion** [comment]
This won't build until apache/accumulo-access#37 is merged

**Comment by keith-turner** [comment]
I opened #3746 a bit ago, but I have not updated it with the latest changes in accumulo-access. Need to reconcile this PR and #3746.

**Comment by dlmarion** [comment]
> I opened #3746 a bit ago, but I have not updated it with the latest changes in accumulo-access. Need to reconcile this PR and #3746.

I knew there was work done for this already, but could not find the issue. I agree that the two PRs need to be reconciled.

**Comment by keith-turner** [comment]
I merged this branch into #3746 and resolved conflicts as a way of reconciling the branches.  The following are the major diffs I uncovered while doing this.

 * Why make accumulo access optional jar in the assemble pom?
 * Should we deprecate ColumnVisibility.quote()?  There are two instances of that method (one for string and one for byte[]).  This branch deprecates one of those.  When I merged I removed the single deprecation and threw in a TODO.  If we want to deprecate, thinking we should do both or neither.
 * This branch had ColumnVis wrap and AccessExpression.  In #3476 ColVis was still wrapping a byte array instead of an AccessExpress.  I kept the byte[] to avoid going from byte[]->String->byte[] in some cases.  Also avoid an extra object allocation in some cases.  However I am not sure about this.  Wrapping the AccessExpression seems cleaner, but may be inefficient in some circumstances w/ more copies and object allocations.
 * The existing changes in #3746 did not need to add a new List<byte[]> constructor to AccessEvaluator, so I kept those.  So if we want to keep those, then may not need to add that method in accumulo-access.

**Comment by dlmarion** [comment]
> Why make accumulo access optional jar in the assemble pom?

That's just how the assemble pom dependencies are marked. This follows convention. The dependencies are copied to the resulting tarball.

**Comment by dlmarion** [comment]
> This branch had ColumnVis wrap and AccessExpression. In https://github.com/apache/accumulo/pull/3746 ColVis was still wrapping a byte array instead of an AccessExpress. I kept the byte[] to avoid going from byte[]->String->byte[] in some cases. Also avoid an extra object allocation in some cases. However I am not sure about this. Wrapping the AccessExpression seems cleaner, but may be inefficient in some circumstances w/ more copies and object allocations.

I made a comment on apache/accumulo#3746 regarding this.

**Comment by dlmarion** [comment]
> * Should we deprecate ColumnVisibility.quote()?  There are two instances of that method (one for string and one for byte[]).  This branch deprecates one of those.  When I merged I removed the single deprecation and threw in a TODO.  If we want to deprecate, thinking we should do both or neither.

I made a comment in apache/accumulo#3746 about this

> * This branch had ColumnVis wrap and AccessExpression.  In [updates column visibility to use accumulo access library #3746](https://github.com/apache/accumulo/pull/3746) ColVis was still wrapping a byte array instead of an AccessExpress.  I kept the byte[] to avoid going from byte[]->String->byte[] in some cases.  Also avoid an extra object allocation in some cases.  However I am not sure about this.  Wrapping the AccessExpression seems cleaner, but may be inefficient in some circumstances w/ more copies and object allocations.

I liked the simplicity of ColVis wrapping AccessExpression. The VisibilityEvaluator is changing to use AccessEvaluator, so the byte[] in ColVis *must* be a valid AccessExpression. In ColVis(byte[]) constructor, you are calling `AccessExpression.validate`, so I'm not sure that you are saving much w/r/t object creation. I wonder if the answer is for ColVis to have `AccessExpression` and `byte[]` members that are set in the constructor to avoid the runtime cost of calling `AccessExpression.getExpression`.

> * The existing changes in [updates column visibility to use accumulo access library #3746](https://github.com/apache/accumulo/pull/3746) did not need to add a new List<byte[]> constructor to AccessEvaluator, so I kept those.  So if we want to keep those, then may not need to add that method in accumulo-access.

Fine by me, whatever works.

**Comment by keith-turner** [comment]
> I liked the simplicity of ColVis wrapping AccessExpression. The VisibilityEvaluator is changing to use AccessEvaluator, so the byte[] in ColVis must be a valid AccessExpression. In ColVis(byte[]) constructor, you are calling AccessExpression.validate, so I'm not sure that you are saving much w/r/t object creation. I wonder if the answer is for ColVis to have AccessExpression and byte[] members that are set in the constructor to avoid the runtime cost of calling AccessExpression.getExpression.

I like ColVis wrapping AccessExpression too.  I have not fully worked this out, but wondering if another piece of this puzzle is deprecating `byte[] getExpression()` and replacing it with `AccessExpression getAccessExpression()` in ColVis.  Not sure about that though, would need to try to know what the implications are.  When thinking of that deprecation, I started to wondering about a more general deprecation.   Could AccessExpression replace ColVis completely in the Accumulo API, I get completely lost when thinking through that though because there are so many things to consider.

**Comment by dlmarion** [comment]
Closing this in favor of #3746

**Pull request closed without merging**
