### PR TITLE
Move server navigation out of navbar in monitor

### LINKED ISSUE #3548: Accumulo goal state not visible on all pages
ticket #3373 added back the display of the system goal state but only on the manager server overvew page.  This should be moved into the title bar along with the links so that is does not matter which page you are on.

Accumulo 2.1.1

### PR DESCRIPTION
**Pull request by DomGarguilo**
fixes #3548

This PR...
* moves the 'manager server', 'tablet servers' and 'garbage collector' links out of the 'servers' dropdown in the navbar and into their own separate links
* makes it so that when the manager state or goal state is `SAFE_MODE` the manager notification circle is yellow and when the manager state or goal state is `CLEAN_STOP` it is red

Here are some screenshots with various manager states:
Screenshot from 2023-06-30 15-00-42

Screenshot from 2023-06-30 15-00-59

Screenshot from 2023-06-30 15-01-18

Screenshot from 2023-06-30 15-01-24

Screenshot from 2023-06-30 15-01-30

### CODE REVIEW

**Review by ctubbsii — CHANGES_REQUESTED** [review]
> * moves the 'manager server', 'tablet servers' and 'garbage collector' links out of the 'servers' dropdown in the navbar and into their own separate links

-1 to that part, as per my comments on https://github.com/apache/accumulo/issues/3548#issuecomment-1613916979 and https://github.com/apache/accumulo/issues/3548#issuecomment-1615135466


> * makes it so that when the manager state or goal state is `SAFE_MODE` the manager notification circle is yellow and when the manager state or goal state is `CLEAN_STOP` it is red

+1 to that part of the change.

I wouldn't mind so much expanding the menu if it didn't take up so much space and add so much clutter to the top bar. But, even if we could find a way to make them take up less space, it's not scalable... we're adding a bunch of different server types (scan servers, compactors, etc.) and there just isn't enough space up there to separate them out. And it doesn't make sense to separate out some server types and leave others collapsed. So, I think it just needs to stay collapsed, and we need to use some other distinct visual element that propagates up to indicate this special circumstance. (Alternatively, users can just monitor the REST endpoint in any monitoring or alerting tool they wish, rather than rely on our monitor's look and feel to present that information.)

**Comment by EdColeman** [comment]
Is this approach going to work if there are multiple managers?  That's not the case now, but asking if the changes would be able to accommodate more that one manager?  The answer  might be that with multiple managers, a whole lot of other things will need to change, so it does not matter.  But, would be desirable if it could be accommodated, or at least provide a path towards multiple managers rather than being another road block.

**Comment by ctubbsii** [comment]
> Is this approach going to work if there are multiple managers?

I'm not sure how safe mode would work with multiple managers, but assuming they each could be in safe mode, then visually on the monitor, the main change would be to add an "s" to make it plural. The dot color or other visual element could indicate that any one of the managers are in safe mode. So, I don't think it really affects this at all right now.

**Comment by DomGarguilo** [comment]
In 589787c I returned the navbar servers dropdown to how it was. I also made it do that servers dropdown notification takes into account the manager state and goal state when its color is set. I also did quite a bit of refactoring to break things down into smaller methods and create constants for frequently repeated variable names.

**Review by Manno15 — APPROVED** [review]
These latest changes look good.

**Comment by ctubbsii** [comment]
@DomGarguilo can you show some updated screenshots for the recent changes, when you get a chance?

**Comment by DomGarguilo** [comment]
Here are some updated screenshots. Let me know if there are any other specific cases that you might want to see.

Screenshot from 2023-07-11 10-03-58
Screenshot from 2023-07-11 10-04-39

**Comment by ctubbsii** [comment]
> Here are some updated screenshots. Let me know if there are any other specific cases that you might want to see.

@DomGarguilo Thanks for that. I personally like this, but @ivakegg said that it could go ignored if it was just a yellow dot in the rolled up version, because it's common for the Servers dot to be yellow due to some TServers being offline, rather than anything to do with the Manager. So, that's why I had proposed using a unique visual element that got rolled up when the Manager is in safe mode, so it's distinguishable from the common situation where it's merely yellow because a few tservers are offline. Yellow is still good to use, but instead of a dot, it could be a different icon.

**Comment by ctubbsii** [comment]
@DomGarguilo I'm going to go ahead and include this in 2.1.2, because I think it gets us closer to what we want. But I will create a new issue for subsequent work to create a distinct visual indicator for the rollup when the manager's indicator is yellow vs. the tservers' being yellow, so you don't have to expand the menu to notice the manager is yellow.

**Comment by ctubbsii** [comment]
Didn't realize the PR was against main before I merged this, so I needed to cherry-pick it to 2.1 to backport it, in commit 313238b5e8887f3e70809d920c1d359fc1b29010

**Comment by ctubbsii** [comment]
The follow-on ticket is #3688

**Pull request merged**
