### PR TITLE
Commons collections

### PR DESCRIPTION
**Pull request by milleruntime**
Just get some tests running in Travis

### CODE REVIEW

**Comment by milleruntime** [comment]
Ok looks like Travis didn't run so I will Test this bad boy locally.

**Comment by milleruntime** [comment]
Tests failing so putting this on hold for now.

**Comment by milleruntime** [comment]
All Unit tests are passing.  Haven't run the ITs yet.

**Comment by milleruntime** [comment]
I think this is good finally so I will merge.

**Comment by milleruntime** [comment]
I am seeing this warning... Is this what you are referring to?
[INFO] --- maven-assembly-plugin:3.0.0:single (binary-assembly) @ accumulo ---
[INFO] Reading assembly descriptor: src/main/assemblies/binary-release.xml
[WARNING] The following patterns were never triggered in this artifact inclusion filter:
o  'commons-collections:commons-collections'

**Comment by ctubbsii** [comment]
I didn't try a build to see the warning. But yeah, it's warning of the same thing I was talking about.

The assembly descriptor references a set of components to include in the tarball. That list contains dependencies of the assemble module. The above warning indicates that the `commons-collections:commons-collections` artifact can't be found among the assemble module's dependencies and wasn't included. The reason is because it was replaced with the new groupId/artifactId... we just need to update the `component.xml` file to have the correct new groupId/artifactId for commons-collections.

**Pull request merged**
