### PR TITLE
Stop logging maps in ContextManager

### PR DESCRIPTION
**Pull request by milleruntime**

### CODE REVIEW

**Comment by EdColeman** [comment]
Are these frequent? Does not having a context convey information to the user?

Would something like
```
log.debug("Managed Contexts: {}", context == null ? "none" : contexts);
```
be too busy?

**Comment by EdColeman** [comment]
I do not know how to classify / balance noise vs. useful information in this case.  I can see the viewpoint that if it is useful or important to see the context when you have it configured, the absence could also be informative? - Say you expected it to be set but was not? Or all my others have it set, but why not this one?

It's really hard to go through a log file and find messages that are "missing" - especially if your not sure that you should be looking for them in the first place.

One message seems reasonable as an alternative - but I also don't recall this being and issue - but I am also unsure that if there was a suspected problem, what it would look like and what information would be useful in tracking it down.

**Comment by ctubbsii** [comment]
Can we just make it so it logs if there are changes?

**Comment by milleruntime** [comment]
These log statements are getting printed from `AccumuloVFSClassLoader.removeUnusedContexts(contextsInUse)` which is called in a thread in `startCleanupThread()` from the `DefaultContextClassLoaderFactory`. It seems the whole point of the method is to just to remove unused objects so I don't think we need to be printing every time. From a user standpoint, I think they would only care if something is being removed from the `unused` map, which is printed in the next loop.

**Comment by ctubbsii** [comment]
> It seems the whole point of the method is to just to remove unused objects so I don't think we need to be printing every time.

Do we log elsewhere when the context is initialized, then?

> From a user standpoint, I think they would only care if something is being removed from the `unused` map, which is printed in the next loop.

If the removals are already being logged, and the initialization is already logged, then I agree it doesn't make sense to continually log the current set here.

**Comment by milleruntime** [comment]
> Do we log elsewhere when the context is initialized, then?

It is difficult to tell exactly where things get initialized but I found these log statements.
https://github.com/apache/accumulo/blob/42c84e8e86ce53b9345bfcc7b5c8c6b4e2c33eab/start/src/main/java/org/apache/accumulo/start/classloader/vfs/ContextManager.java#L53-L55

https://github.com/apache/accumulo/blob/42c84e8e86ce53b9345bfcc7b5c8c6b4e2c33eab/start/src/main/java/org/apache/accumulo/start/classloader/vfs/ContextManager.java#L197

**Review by ctubbsii — APPROVED** [review]

**Pull request merged**
