### PR TITLE
Website menu/navbar reorganization

### PR DESCRIPTION
**Pull request by mikewalch**
* Links to User Manual, Javadocs & Examples go to latest release
  in 'Documentation' menu
* Added 'Documentation Archive' for historical reference
* All release notes also have links to documentation for that release
* Added github and twitter buttons next to where download button is.
* Removed old release notes archive as it is now automatically
  generated.
* Moved 'Papers & Presentations' link to 'Community' menu.

### CODE REVIEW

**Comment by milleruntime** [comment]
+1
I really like the Quick Links to latest release and nice touch with the version number in parenthesis. GitHub and Twitter buttons look great.  Here are some other suggestions:

You could shorten "Documentation Archive" to just "Archive" since its under the Documentation menu. You could also move the link to Community->News Archive under "Archive" since we have News on the front page.

Can we remove the Thanks link under Community? This could be linked to somewhere else.

I don't think Documentation -> Screenshots needs its own menu item. A link to Screenshots could be under Features.

**Comment by mikewalch** [comment]
@milleruntime, I pushed another commit that should address your recommendations.  The commit also makes some more changes to the navbar/menu.

**Comment by keith-turner** [comment]
I don't like the multiple links to GH and twitter on front page.

**Comment by keith-turner** [comment]
+1

**Pull request merged**
