### PR TITLE
ACCUMULO-4551 thrift 0.10.0

### PR DESCRIPTION
**Pull request by ctubbsii**
This PR includes changes to update thrift, but without any re-generated Java code for easier review. For the full set of changes, including re-generated code, see #215 . [ACCUMULO-4551](https://issues.apache.org/jira/browse/ACCUMULO-4551)

### CODE REVIEW

**Comment by keith-turner** [comment]
@ctubbsii did you try running all of the ITs for this change?

**Comment by ctubbsii** [comment]
@keith-turner No, only `-Psunny`, which passed.

**Comment by keith-turner** [comment]
I remember we had to add some special handling for TApplicationException when going from 0.9.1 to 0.9.3.  I wonder if this is still needed.  It would be useful to find some ITs that expect AccumuloServerException and see if those are still working.

**Comment by ctubbsii** [comment]
@keith-turner I believe it still is needed, but some of the stuff we may have done to handle exceptions on oneway methods might no longer be needed. I saw some changes in the exception handling in the generated code for that. Feel free to review it. @joshelser may also have some insight (I believe he fixed the oneway issue previously, but I can't find the ticket).

**Comment by ctubbsii** [comment]
I ran all the ITs with 0.10.0, and everything passed. (Some unstable tests had to be re-run, but their stability is unrelated to thrift version.) I'm going to merge this into master.

**Pull request merged**
