### PR TITLE
Updated AccumuloITBase.java to enforce a default timeout

### PR DESCRIPTION
**Pull request by MuazmaZ**
Updated default TimeoutSeconds() method to be 10 minutes

### CODE REVIEW

**Comment by ctubbsii** [comment]
@MuazmaZ Were you able to run the ITs with this timeout? Did you notice any particularly problematic tests that might need to be tweaked as a result of this change?

**Comment by MuazmaZ** [comment]
@ctubbsii I didn't see any test, in particular, to be problematic

**Comment by billierinaldi** [comment]
I'm attempting mvn verify with this change on my laptop now (with a timeout.factor). But I haven't run a verify on this laptop before, so I don't know whether this would typically succeed.

**Comment by ctubbsii** [comment]
I would be happy to merge this in now, but I'm seeing other failures currently on the master branch, and would like to see those resolved first.

**Comment by keith-turner** [comment]
I can run the ITs for this branch.

**Comment by ctubbsii** [comment]
> I can run the ITs for this branch.

@keith-turner Can you clarify whether you mean:

1. You *will* run the ITs on this branch to see if this is okay to merge, or
2. You *have* run the ITs on this branch and you think it's okay to merge now.

**Comment by keith-turner** [comment]
@ctubbsii I have the ITs running now for this branch merged into master.  If it all is well I can merge.

**Comment by keith-turner** [comment]
Saw the following failures 

```
[ERROR] Failures: 
[ERROR]   UnorderedWorkAssignerReplicationIT.dataWasReplicatedToThePeer:288 Drain did not finish within 30 seconds
[ERROR] Errors: 
[ERROR] org.apache.accumulo.test.MetaRecoveryIT.test(org.apache.accumulo.test.MetaRecoveryIT)
[ERROR]   Run 1: MetaRecoveryIT.test:97 » TestTimedOut test timed out after 240 seconds
[ERROR]   Run 2: MetaRecoveryIT.test »  Appears to be stuck in thread Time-limited test-SendThr...
[INFO] 
[ERROR] org.apache.accumulo.test.functional.MetadataMaxFilesIT.test(org.apache.accumulo.test.functional.MetadataMaxFilesIT)
[ERROR]   Run 1: MetadataMaxFilesIT.test:80 » TestTimedOut test timed out after 300 seconds
[ERROR]   Run 2: MetadataMaxFilesIT.test »  Appears to be stuck in thread Time-limited test-Sen...
[INFO] 
[ERROR] org.apache.accumulo.test.replication.UnorderedWorkAssignerReplicationIT.dataWasReplicatedToThePeerWithoutDrain(org.apache.accumulo.test.replication.UnorderedWorkAssignerReplicationIT)
[ERROR]   Run 1: UnorderedWorkAssignerReplicationIT.dataWasReplicatedToThePeerWithoutDrain:601 » TestTimedOut
[ERROR]   Run 2: UnorderedWorkAssignerReplicationIT.dataWasReplicatedToThePeerWithoutDrain »  A...
[INFO] 
[INFO] 
[ERROR] Tests run: 610, Failures: 1, Errors: 3, Skipped: 1
```

**Comment by keith-turner** [comment]
I am currently looking into these test failures.  Rerunning the failed test on this branch and in master.

**Comment by keith-turner** [comment]
I ran MetadataMaxFilesIT and MetaRecoveryIT a few times in this branch and the master branch.  For both branches the test would fail sometimes and succeed sometimes.  So those test seem to be a bit flaky even w/o this change.

**Comment by keith-turner** [comment]
@MuazmaZ  thanks for the contribution.  If you would like to add yourself as a contributor to the Accumulo people page [please submit a PR](https://github.com/apache/accumulo-website/edit/master/pages/people.md).

**Comment by MuazmaZ** [comment]
Thanks @keith-turner @ctubbsii and @billierinaldi for resolving this. I also ran maven verify and got no errors.

**Pull request merged**
