### PR TITLE
Update Last Location. Fix #1169 

### LINKED ISSUE #1169: balancing strategy
The balancer currently will assign out the tablets given their initial locations per the "last" cf in the metadata, and the will slowly move tablets to get a final steady state.  In many deployments we are starting up a large accumulo cluster and it will take an hour or more to attain a steady state.  There needs to be a mechanism by which we delay the initial assignment (most likely handled by #1167) and then to determine a final steady state before doing the initial assignments.  This will help in the case where we are expanding the cluster considerably and bringing it up for the first time.

### PR DESCRIPTION
**Pull request by Manno15**
This the one-line change leftover after the revert of pull request #1453. The rest of those changes will be tested more thoroughly and hopefully can be salvaged. In the meantime, this change fixes the issue without a bunch of the refactoring done in the previous pull request. I apologize for the delay. 

I ran the entire IT suite, and I didn't see any relavent breakages from this change besides the one mentioned below. 

Also, an AssertNull was removed from the MasterAssignmentIT. Let me know if that is acceptable or if I need to refactor that IT further.

### CODE REVIEW

**Comment by ivakegg** [comment]
Shouldn't this include a revert of the previous revert?

**Comment by Manno15** [comment]
I am not sure I folllow what you mean. Sorry.

**Comment by milleruntime** [comment]
> Shouldn't this include a revert of the previous revert?

I don't think so.  He pulled out this one line from the previous change (which included too many other changes that broke the build).

**Comment by Manno15** [comment]
I am currently working on getting those other changes to build but this one should be good to go.

**Comment by milleruntime** [comment]
I am in the process of running the all the ITs.  I want to make sure this change wasn't part of problem which forced us to revert.

**Comment by ctubbsii** [comment]
I don't currently understand assignments to know what this patch fixes or why it fixes it. Can you add a brief comment here (so that way it can be included in the commit log) to explain what is being fixed, specifically, and why this fix works?

Once we have that, and the ITs pass, I'd be okay with merging it for 2.1 (with that text included in the commit log message when it is merged).

**Comment by Manno15** [comment]
The idea behind this change is to guarantee lastLocation gets assigned to the correct location. In my testing, a cluster can fully balance but lastLocation still have its original value, of either null or the location the tablet was initially in. In these instances, if the cluster is taken down and back up, it would go back to its original unbalanced state. This issue was brought up by @ivakegg since the balancing for his larger data set took quite a bit of time to do the entire balancing process. This pull request will ideally alleviate that from happening.

**Comment by ctubbsii** [comment]
Thanks. I'm okay with this change... I just wish we had a better grasp on the intended (designed) role that last location played, as distinct from the current location. I don't think that's documented anywhere, and it makes it really hard to address issues in this area.

**Comment by ctubbsii** [comment]
Have all the ITs been run with this change?

**Comment by Manno15** [comment]
They were at the time but not recently.

**Comment by ctubbsii** [comment]
I ran the full ITs overnight and everything looks good. I'll merge this today. Thanks, @Manno15 .

**Comment by ctubbsii** [comment]
Reverted due to conclusions realized in https://github.com/apache/accumulo/pull/1653#issuecomment-691274564

**Pull request merged**
