### PR TITLE
Reword some comments to clarify

### PR DESCRIPTION
**Pull request by milleruntime**
* Also rename some methods in CompactableImpl

### CODE REVIEW

**Review by Manno15 — APPROVED** [review]

**Review by keith-turner — APPROVED** [review]

**Comment by milleruntime** [comment]
@keith-turner One comment I was hoping we could expand on was "So the selected set must be initialized." I am not sure if that means in the current method or before calling the current method.

**Review by DomGarguilo — APPROVED** [review]
LGTM. See a PR I made to this branch [here](https://github.com/milleruntime/accumulo/pull/16) for a few other very small comment related fixes.

**Comment by keith-turner** [comment]
> @keith-turner One comment I was hoping we could expand on was "So the selected set must be initialized." I am not sure if that means in the current method or before calling the current method.

Seems like it initializes some instance var in the method and also uses the returned value to initialize some more instance var later in the constructor.  I don't think anything is initialized before the method call.

**Comment by milleruntime** [comment]
> > @keith-turner One comment I was hoping we could expand on was "So the selected set must be initialized." I am not sure if that means in the current method or before calling the current method.
> 
> Seems like it initializes some instance var in the method and also uses the returned value to initialize some more instance var later in the constructor. I don't think anything is initialized before the method call.

OK I think I am going to just drop that sentence since it doesn't really add anything and is just confusing me.

**Pull request merged**
