### PR TITLE
Declaration of map in MapCounter.java as final

### PR DESCRIPTION
**Pull request by Amisha328**

### CODE REVIEW

**Comment by Amisha328** [comment]
Are there still any conflicts or all are resolved?

**Comment by EdColeman** [comment]
Thanks for the contribution @Amisha328 and welcome to the Apache Accumulo community. If you would like to be listed as a contributor on Accumulo's people page please make a website PR for people.md. https://github.com/apache/accumulo-website/edit/main/pages/people.md
If you intend to make more contributions, please consider subscribing to the dev list and introducing yourself. Also, you can use the dev list or slack to reach out if you have questions about anything. https://accumulo.apache.org/contact-us/

**Comment by Amisha328** [comment]
Thanks, a lot @EdColeman 
I would love to be part of Accumulo.
Thanks for the opportunity.

**Comment by Amisha328** [comment]
@EdColeman I didn't exactly get what I have to do to be listed as a contributor on Accumulo's people page.
Could you please help me with that?

**Comment by EdColeman** [comment]
1. Checkout the [accumulo-website](https://github.com/apache/accumulo-website) project
2. Update the (./accumulo-website/pages/people.md )[https://github.com/apache/accumulo-website/blob/main/pages/people.md]
  - add your name and other information if you want under, the Contributors section.
  - names should be in alphabetical order
  - include a reference to your original contribution.
3. Submit the changes as PR to the accumulo-website project.

**Comment by Amisha328** [comment]
@EdColeman,
I have added my name to people.md.  
But, I don't understand where to include a reference to the original contribution.

**Comment by EdColeman** [comment]
In the commit message.  Something like

Update contributors to add amisha328

Fixed issue #2066 with PR #2071 - made MapCounter final

**Comment by Amisha328** [comment]
Okay,
Thank you!

**Pull request merged**
