### PR TITLE
Fix major compaction metrics to not reference the tserver

### LINKED ISSUE #5062: Metric accumulo.tserver.compactions.majc.running may not be needed anymore
**Describe the bug**

The metric accumulo.tserver.compactions.majc.running is being emitted by the manager.   This metric may no longer be needed, this information can be computed by summing idle metrics from compactors.  If the metric is still needed, it be being computed incorrectly because this count was observed to be higher than the known number of actual running compactions.

**Expected behavior**

The metric accumulo.tserver.compactions.majc.running is removed from the manager or corrected if its wrong.

### PR DESCRIPTION
**Pull request by dlmarion**
Closes #5062

### CODE REVIEW

**Review by keith-turner — APPROVED** [review]
Seems like the three metric names in this PR could use the `accumulo.compaction` prefix like in #5075.  Like `accumulo.compaction.majc.queued`.  Also not something for this PR, but it seems like `MAJC_QUEUED` and `MAJC_RUNNING` could be removed.  Those two metrics are dupicating data the is present in per compactor RG metrics and could be derived from those.

**Comment by dlmarion** [comment]
> Seems like the three metric names in this PR could use the `accumulo.compaction` prefix like in #5075. Like `accumulo.compaction.majc.queued`. 

I merged into #5075 and fixed the names here.

Also not something for this PR, but it seems like `MAJC_QUEUED` and `MAJC_RUNNING` could be removed. Those two metrics are dupicating data the is present in per compactor RG metrics and could be derived from those.

`CompactionCoordinator.registerMetrics` registers `MAJC_QUEUED` and `MAJC_RUNNING`. I see that QueueMetrics registers `COMPACTOR_JOB_PRIORITY_QUEUE_JOBS_QUEUED` with a `queue.id` tag, which could be summed up to replace `MAJC_QUEUED`. I don't see a direct replacement for `MAJC_RUNNING` though. What did you have in mind for that?

**Comment by dlmarion** [comment]
> `CompactionCoordinator.registerMetrics` registers `MAJC_QUEUED` and `MAJC_RUNNING`. I see that QueueMetrics registers `COMPACTOR_JOB_PRIORITY_QUEUE_JOBS_QUEUED` with a `queue.id` tag, which could be summed up to replace `MAJC_QUEUED`. I don't see a direct replacement for `MAJC_RUNNING` though. What did you have in mind for that?

Ok, I see now in #5062 you said `... this information can be computed by summing idle metrics from compactors.` I'm wondering if that may not be intuitive to a user to use that for running compactions given the name.

**Comment by dlmarion** [comment]
> > `CompactionCoordinator.registerMetrics` registers `MAJC_QUEUED` and `MAJC_RUNNING`. I see that QueueMetrics registers `COMPACTOR_JOB_PRIORITY_QUEUE_JOBS_QUEUED` with a `queue.id` tag, which could be summed up to replace `MAJC_QUEUED`. I don't see a direct replacement for `MAJC_RUNNING` though. What did you have in mind for that?
> 
> Ok, I see now in #5062 you said `... this information can be computed by summing idle metrics from compactors.` I'm wondering if that may not be intuitive to a user to use that for running compactions given the name.

Ok, using the server idle metric to gauge whether or not the Compactor is running a compaction is probably not the way to go. The process has to be idle for so long, regulated by Property.GENERAL_IDLE_PROCESS_INTERVAL, to be considered idle. This is so that the metric is not constantly flapping.

**Comment by dlmarion** [comment]
I removed `MAJC_QUEUED` and `MAJC_RUNNING`. I also added some new metrics as at least one was being used in the wrong place. I look at this as some general cleanup, but I think more might be needed. Specifically, I'm thinking the metric names might need to be reviewed and corrected.

**Pull request merged**
