### PR TITLE
Make Accumulo 1.9 compatible with ZK 3.5

### PR DESCRIPTION
**Pull request by karthick-rn**
Fix as described in #1503

### CODE REVIEW

**Comment by ctubbsii** [comment]
The title indicates it is for 1.9, but the PR was made against the master branch.

**Comment by karthick-rn** [comment]
Thanks @ctubbsii. Corrected the branch.

**Comment by billierinaldi** [comment]
Thanks for the patch, @karthick-rn! For the general.classpaths change, we should keep both ZK jar locations on the classpath so that it will work with either 3.5 or 3.4 and earlier versions. (If you look at the rest of the entries for general.classpaths, you can see we have entries for different versions of Hadoop, so there is a precedent for this.)

**Comment by billierinaldi** [comment]
We're able to run Accumulo 2.0.0 with ZK 3.5 using fluo-muchos with [this change in accumulo-env.sh](https://github.com/apache/fluo-muchos/blob/282a7cf92c72415877e2956fd78803a74bc57394/ansible/roles/accumulo/templates/accumulo-env.sh#L43-L49). I'm not sure if we'd want to add a change like this to the default accumulo-env.sh in master or if we'd just want to document it. Any thoughts?

**Comment by ctubbsii** [comment]
> We're able to run Accumulo 2.0.0 with ZK 3.5 using fluo-muchos with [this change in accumulo-env.sh](https://github.com/apache/fluo-muchos/blob/282a7cf92c72415877e2956fd78803a74bc57394/ansible/roles/accumulo/templates/accumulo-env.sh#L43-L49). I'm not sure if we'd want to add a change like this to the default accumulo-env.sh in master or if we'd just want to document it. Any thoughts?

I think a simpler approach of just adding `${ZOOKEEPER_HOME}/lib` to the existing `CLASSPATH` line would be good for 2.x. Are there any pitfalls to doing something simple like that?

**Comment by billierinaldi** [comment]
I think that might work. We should test it out to make sure.

**Comment by ctubbsii** [comment]
> I think that might work. We should test it out to make sure.

Okay. Let's go ahead and merge this in, and that can be a separate issue.

**Pull request merged**
