### PR TITLE
Implements missing compacton selection functionality

### PR DESCRIPTION
**Pull request by keith-turner**
Compaction selection functionality that opened files was not implemented because it opens user files in the manager.  This change implements the functionality inorder to get integration test passing.  There is already an open issue about finding a better way to do this. See #3526

### CODE REVIEW

**Comment by keith-turner** [comment]
This PR along with #3785 and #3784 are all part of an effort to get `mvn verify -Psunny` working in the elasticity branch.

**Comment by dlmarion** [comment]
Would this be another task type for #3801 ?

**Comment by dlmarion** [comment]
I wonder if we should get #3801 where it needs to be and merged, then implement this in that framework vs merging this to get `sunny` working just to have to back it out later.

**Comment by keith-turner** [comment]
> I wonder if we should get https://github.com/apache/accumulo/pull/3801 where it needs to be and merged, then implement this in that framework vs merging this to get sunny working just to have to back it out later.

Its a small change.  I would like to get the verify sunny build working.  Would like to also look into expanding what is in the sunny tests to make sure all major features are well covered (ingest, scan, compact, split, merge, bulk import, etc).

**Pull request merged**
