### PR TITLE
ACCUMULO-4310 - User manual should mention accumulo-site.xml property…

### PR DESCRIPTION
**Pull request by mikewalch**
… in instructions to enable native maps

### CODE REVIEW

**Comment by keith-turner** [comment]
+1

**Comment by dhutchis** [comment]
+1

**Comment by ctubbsii** [comment]
Test comment

**Comment by ctubbsii** [comment]
Test comment

**Comment by ctubbsii** [comment]
Test comment

**Comment by ctubbsii** [comment]
BTW, it's possible to give a +1 with the icon to "Add your reaction", rather than create separate comments. It keeps things nice and rolled up, instead of potentially long-scrolling +1 vertical columns.

**Comment by ctubbsii** [comment]
Test comment

**Comment by keith-turner** [comment]
@mikewalch  what branch did you intend this to go in?

**Comment by mikewalch** [comment]
master and 1.8 should be sufficient but adding it to more (like 1.7) would be great.

**Comment by ctubbsii** [comment]
1.7 and later use the same mechanism to build the docs, so it should be trivial to add it to all 3 of those. 1.6 is a bit annoying, because of the docs using a LaTeX build.

**Pull request closed without merging**
