### PR TITLE
fixes race condition in test

### PR DESCRIPTION
**Pull request by keith-turner**

### CODE REVIEW

**Review by DomGarguilo — APPROVED** [review]
Looks reasonable is it. Could potentially rename the scanners to something like `scannerEventual` `batchScannerEventual` `scannerImmediate` `batchScannerImmediate` but not sure how much value that would add.

**Comment by dlmarion** [comment]
what's the race condition? I thought that you could change the settings on a scanner and call `iterator()` at any point.

**Comment by keith-turner** [comment]
> what's the race condition? I thought that you could change the settings on a scanner and call iterator() at any point.

The consistency level was set on the scanner in the foreground thread twice, but the code in the background threads could run at any time so do not know which scanner setting they will use.  When `iterator()` is called on the scanner it uses what ever config was set before that point.  The `iterator()` is called in the background thread by `Iterables.size()`

**Comment by dlmarion** [comment]
We could have retrieved the iterator in the foreground then and passed it to the background thread making the `setConsistencyLevel` and `iterator` calls done serially in the foreground? I think re-using the Scanner / BatchScanner is a good test.

**Comment by keith-turner** [comment]
> We could have retrieved the iterator in the foreground then and passed it to the background thread making the setConsistencyLevel and iterator calls done serially in the foreground?

Was thinking about that, but was worried if the scanner tried to read any data at the time the iterator was created that it would block in the foreground thread.  I looked and the scanner does not seem to block until hasNext is called after creating an iterator, did not check the batch scanner.  The behavior could change in the future, but maybe its ok if the test catches that and fails.

**Comment by dlmarion** [comment]
We might want to have a test somewhere that test's Scanner/BatchScanner re-use with concurrent iterators with different settings if we don't have one already.

**Comment by keith-turner** [comment]
> We might want to have a test somewhere that test's Scanner/BatchScanner re-use with concurrent iterators with different settings if we don't have one already.

That would be a really nice test to have.

**Pull request merged**
