### PR TITLE
Upgrade findbugs to spotbugs 

### PR DESCRIPTION
**Pull request by milleruntime**
https://find-sec-bugs.github.io/
for security audits of Java web applications.

### CODE REVIEW

**Comment by mikewalch** [comment]
It looks like using this plugin might require us to move to spotbugs (which isn't a bad idea).  It also looks like some more configuration might necessary.  See the docs below:

https://github.com/find-sec-bugs/find-sec-bugs/wiki/Maven-configuration

**Comment by milleruntime** [comment]
So I got the plugin working with the new version of findbugs (aka spotbugs).  Now I just need to triage all the new bugs, which is going to take some time.

To start this is a big one, which I am not sure if we can ignore or not:
[INFO] org.apache.accumulo.start.classloader.AccumuloClassLoader.getClassLoader() creates a org.apache.accumulo.start.classloader.AccumuloClassLoader$2 classloader, which should be performed within a doPrivileged block [org.apache.accumulo.start.classloader.AccumuloClassLoader] At AccumuloClassLoader.java:[line 219] DP_CREATE_CLASSLOADER_INSIDE_DO_PRIVILEGED

[INFO] new org.apache.accumulo.start.classloader.vfs.AccumuloReloadingVFSClassLoader(String, FileSystemManager, ReloadingClassLoader, long, boolean) creates a org.apache.accumulo.start.classloader.vfs.PostDelegatingVFSClassLoader classloader, which should be performed within a doPrivileged block [org.apache.accumulo.start.classloader.vfs.AccumuloReloadingVFSClassLoader] At AccumuloReloadingVFSClassLoader.java:[line 186] DP_CREATE_CLASSLOADER_INSIDE_DO_PRIVILEGED

[INFO] new org.apache.accumulo.start.classloader.vfs.AccumuloReloadingVFSClassLoader(String, FileSystemManager, ReloadingClassLoader, long, boolean) creates a org.apache.commons.vfs2.impl.VFSClassLoader classloader, which should be performed within a doPrivileged block [org.apache.accumulo.start.classloader.vfs.AccumuloReloadingVFSClassLoader] At AccumuloReloadingVFSClassLoader.java:[line 184] DP_CREATE_CLASSLOADER_INSIDE_DO_PRIVILEGED

[INFO] org.apache.accumulo.start.classloader.vfs.AccumuloReloadingVFSClassLoader$2.run() creates a org.apache.accumulo.start.classloader.vfs.PostDelegatingVFSClassLoader classloader, which should be performed within a doPrivileged block [org.apache.accumulo.start.classloader.vfs.AccumuloReloadingVFSClassLoader$2] At AccumuloReloadingVFSClassLoader.java:[line 123] DP_CREATE_CLASSLOADER_INSIDE_DO_PRIVILEGED

[INFO] org.apache.accumulo.start.classloader.vfs.AccumuloReloadingVFSClassLoader$2.run() creates a org.apache.commons.vfs2.impl.VFSClassLoader classloader, which should be performed within a doPrivileged block [org.apache.accumulo.start.classloader.vfs.AccumuloReloadingVFSClassLoader$2] At AccumuloReloadingVFSClassLoader.java:[line 121] DP_CREATE_CLASSLOADER_INSIDE_DO_PRIVILEGED

[INFO] org.apache.accumulo.start.classloader.vfs.AccumuloVFSClassLoader.getClassLoader() creates a org.apache.commons.vfs2.impl.VFSClassLoader classloader, which should be performed within a doPrivileged block [org.apache.accumulo.start.classloader.vfs.AccumuloVFSClassLoader] At AccumuloVFSClassLoader.java:[line 219] DP_CREATE_CLASSLOADER_INSIDE_DO_PRIVILEGED

**Comment by ctubbsii** [comment]
I'm not sure I understood what you were saying about Maven executing the "old one".

As for all the bugs in core... you could just temporarily add a blanket exclude to the remaining modules' exclude-filter.xml for all SECURITY type bugs, in order to work through one module at a time.

**Comment by milleruntime** [comment]
Checkout 3151de8d.  I missed updating the plugin execution section of the pom to use spotbugs.  Once I did this, I saw even more bugs.

**Comment by milleruntime** [comment]
Creating a follow on ticket for using the sec-bugs plugin.  I am going to use this PR just for upgrading findbugs to spotbugs.

**Comment by ctubbsii** [comment]
It's probably a good idea to separate out the spotbugs upgrade from the find-sec-bugs. The renames look good to me, and everything else you've done looks good to me, but I have an extra commit I'm going to add to this PR to eliminate some of the other matches from grepping for "findbugs". In particular, there are some "findbugs mitigations" that were done and mentioned in comments, that I think there are better solutions for, so I'm going to do those, and include them here, so that we can eliminate all references to findbugs in this transition.

**Comment by ctubbsii** [comment]
@milleruntime I added commit 0ce8d44d17d5d2aed8432b05fea8453e019e45e0 to include my review feedback. With that (and rebased on top of #619) all looks good to me. Feel free to squash my commit in with everything else.

**Comment by milleruntime** [comment]
Cool sounds good.

**Pull request merged**
