### PR TITLE
Throw sercurity exceptions when permissions checks fail. Backport to 1.10

### PR DESCRIPTION
**Pull request by Manno15**
Based on #1828 in main. This is to back to 1.10. Confirmed the bug did exist on that branch as well.

### CODE REVIEW

**Comment by Manno15** [comment]
When I get the chance, I plan on adding tests in either `ShellIT` or `ShellServerIT` to verify these permissions are checked properly

**Review by ctubbsii — APPROVED** [review]
Thanks @Manno15 !

**Comment by ctubbsii** [comment]
@Manno15 You may want to check that AuditMessageIT passes for you on this branch, because it failed in the main branch until I fixed it in 3b23f6af17ddc0da76fd4756a4c45c72aea50730

**Comment by Manno15** [comment]
@ctubbsii I made the changes to `AuditMessageIT` to get it to run. I will take a look at to see if this is the best spot for the permission denials.

**Comment by milleruntime** [comment]
Thanks for the quick fix @Manno15 !  Feel free to add the changes to the IT this PR or as a separate PR, whatever is easier.

**Comment by Manno15** [comment]
I plan on doing it in a separate pr, I am still debugging some things on it. Is this good to merge? @milleruntime

**Review by milleruntime — APPROVED** [review]
Looks good.  Sorry I had missed your change to `AuditMessageIT`

**Pull request merged**
