### PR TITLE
ACCUMULO-4767 Remove duplicate code in DefaultCryptoModule

### PR DESCRIPTION
**Pull request by PircDef**
Removed duplicate code in DefaultCryptoModule
Added check for existence of array in BlockedOutputStream before using the array in a stream's flush.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by ctubbsii** [comment]
This looks good to merge. But first, I just want to double check that you intended the git author info in the commit to be: `someone <someone@someplace.net>`. Your previous commits have used the github noreply addresses, like `Nick Felts <31989480+PircDef@users.noreply.github.com>`. I'm not sure how GitHub's noreply addresses work, but either way, I think the someplace.net address should be avoided, since that's a real domain.

**Comment by PircDef** [comment]
Glad you noticed, that was unintended.

**Comment by PircDef** [comment]
Pretty sure I picked a suboptimal fix, but a new PR is up that should be fixed.

**Comment by ctubbsii** [comment]
Are you aware you can force push to the existing branch, and you don't need to create a new PR?

**Pull request closed without merging**
