### PR TITLE
Remove MiniAccumuloClusterImpl.verifyup

### PR DESCRIPTION
**Pull request by dlmarion**
Reverts the commits associated with this method.

### CODE REVIEW

**Review by milleruntime — APPROVED** [review]
Assuming you want to go through with this, I am OK with it.

**Comment by ctubbsii** [comment]
I'm not sure this is necessary. I think we can get #2414 to the point where the verifyUp is still helpful, but doesn't cause test problems. Let's try to get #2414 polished, and then merged. And, then if we're still having trouble after a few rounds of testing, and the fix isn't obvious, then we can revisit this.

**Comment by milleruntime** [comment]
> I'm not sure this is necessary. I think we can get #2414 to the point where the verifyUp is still helpful, but doesn't cause test problems. Let's try to get #2414 polished, and then merged. And, then if we're still having trouble after a few rounds of testing, and the fix isn't obvious, then we can revisit this.

I would be fine with that. I am still a little concerned if the additional time for every test is worth it, if this really only helps a fraction of the ITs. 

It may be a better use of time to go the other direction, aka streamline the ITs by removing less useful code from the framework (i.e. standalone overhead, support for one-off features, etc.) to try and simplify it.

**Comment by ctubbsii** [comment]
> I would be fine with that. I am still a little concerned if the additional time for every test is worth it, if this really only helps a fraction of the ITs.

Understood. Let's see if it's actually a significant problem first.

> It may be a better use of time to go the other direction, aka streamline the ITs by removing less useful code from the framework (i.e. standalone overhead, support for one-off features, etc.) to try and simplify it.

That's a good idea, too. I wouldn't consider them mutually exclusive.

**Comment by dlmarion** [comment]
#2414 was merged. Only one test ( LateLastContactIT.test() ) failed in an IT run on `main` after that merge. I'm going to close this PR.

**Pull request closed without merging**
