### PR TITLE
Fixed bugs found when testing offline scans

### PR DESCRIPTION
**Pull request by keith-turner**
Fixed a few bugs found when running [this test](https://gist.github.com/keith-turner/f2159111b025e600a6e0abbaba1d92f3) to exercise offline scans.

### CODE REVIEW

**Review by ctubbsii — COMMENTED** [review]
Does this patch need to be applied to 2.1?

**Comment by keith-turner** [comment]
> Does this patch need to be applied to 2.1? (Also the unit tests are failing)

Yes it will need to be applied to 2.1.  The bug was found when testing offline scans, but it fixes more general problems with btach scans in the scan server.

**Review by dlmarion — APPROVED** [review]

**Comment by dlmarion** [comment]
@keith-turner  - you may want to merge this directly to 2.1

**Review by Manno15 — APPROVED** [review]

**Comment by keith-turner** [comment]
> @keith-turner - you may want to merge this directly to 2.1

That will be a lot cleaner than cherry picking it back and then merging it forward. I am going to do that.

**Pull request merged**
