### PR TITLE
De-dupe some code

### PR DESCRIPTION
**Pull request by milleruntime**
* Create static methods in ClientContext for ZooKeeperInstance

### CODE REVIEW

**Comment by milleruntime** [comment]
> Nice deduplication.
> 
> ZooUtil is probably a better place for the static method than embedded in ClientContext (it's better to keep the ZK stuff isolated to one spot, rather than intermingled with the rest of our utilities/internal code; it'll be easier to abstract ZK later).

Good idea.  I wasn't sure of where the best place was for these methods.  

I wanted to talk to @keith-turner about using Ample for deduping ```ZooKeeperInstance.getRootTabletLocation()``` but wasn't sure how to use it with the old code.

**Comment by keith-turner** [comment]
> I wanted to talk to @keith-turner about using Ample for deduping ZooKeeperInstance.getRootTabletLocation() but wasn't sure how to use it with the old code.

I think that code needed special case because Ample's impl requires a ClientContext but that code is happening before everything needed for a ClientContext exists.

**Comment by ctubbsii** [comment]
@milleruntime I believe this PR breaks `ZooKeeperInstanceTest` cases for `testGetInstanceID_IDMissingForID` and `testGetInstanceID_IDMissingForName`.

I'm trying to get the unit tests to pass on Java 11, and this is one I noticed was failing and seemed unrelated. These test methods are expecting a `RuntimeException`, but nothing is thrown. It could be that the test needs to be updated... but it could also be that the code didn't preserve prior behavior. I haven't investigated yet, and considering reverting this so I can get the UTs to pass under Java 11, before re-applying this change.

**Comment by ctubbsii** [comment]
After some investigation, I realized this needs to be reverted. It doesn't handle some situations correctly (details in revert message). This can probably be fixed and re-applied after the unit tests are passing again (I'm working on that now).

**Comment by milleruntime** [comment]
> @milleruntime I believe this PR breaks `ZooKeeperInstanceTest` cases for `testGetInstanceID_IDMissingForID` and `testGetInstanceID_IDMissingForName`.
> 
> I'm trying to get the unit tests to pass on Java 11, and this is one I noticed was failing and seemed unrelated. These test methods are expecting a `RuntimeException`, but nothing is thrown. It could be that the test needs to be updated... but it could also be that the code didn't preserve prior behavior. I haven't investigated yet, and considering reverting this so I can get the UTs to pass under Java 11, before re-applying this change.

Tests were failing when I merged... why revert?  I could have just applied a fix.

**Comment by ctubbsii** [comment]
I reverted because the code was broken and I wasn't prepared to fix it. It seemed the prudent thing to do, so I could get the build working again. Now that I fixed the build, this should be easy to reapply and isolate the failures to triage the breakage, and I had intended to do that today if you don't get to it first.

**Pull request merged**
