### PR TITLE
Add ZooKeeper ACLs to encoded propety nodes.

### PR DESCRIPTION
**Pull request by EdColeman**
Control access to the encoded property nodes with ZooKeeper ACLs
Added IT test to check that system, all namespaces and tables have an ACL set.

### CODE REVIEW

**Comment by dlmarion** [comment]
Does DumpConfigIT still work?

**Comment by EdColeman** [comment]
@dlmarion - it passes in my ide and all sunny tests passed - why do you ask?

**Comment by dlmarion** [comment]
Just making sure that the other utilities work with the ACLs.

**Comment by EdColeman** [comment]
Anything that gets a ZooReader or ZooReaderWriter from a ServerContext will be operating with an authenticated session. If something instantiates a ZooReader directly, that would specifically need to add the authorization - the static  ZooUtil.digestAuth method to access restricted node in ZooKeeper - include the encoded props.

**Pull request merged**
