### PR TITLE
Reduce ssh connections to hosts in accumulo-cluster

### PR DESCRIPTION
**Pull request by dlmarion**
The accumulo-cluster script would ssh to the host for each server that it wanted to start or stop. This change moves the processing of the number of servers that need to be started or stopped to the accumulo-service script so that only one ssh connection needs to be created to the host for that server type and group.

### CODE REVIEW

**Comment by dlmarion** [comment]
I have tested this locally and things seem to be working.

**Review by ctubbsii — COMMENTED** [review]
Overall, this looks fine to me, but I'm wondering if it supports fine-grained control over the number of instances per type, for a particular server. For example, for each server A, B, and C, I want 1 tserver and 3 sserver. Is that possible with this iteration of these scripts, and the cluster config file?

**Comment by dlmarion** [comment]
I tested it with this configuration and from what I can tell everything came up (and shutdown) as expected. This has different groups and different numbers of servers per group.

```
manager:
  - localhost

monitor:
  - localhost

gc:
  - localhost

tserver:
  default:
    servers_per_host: 1
    hosts:
      - localhost
  test1:
    servers_per_host: 2
    hosts:
      - localhost

compactor:
  default:
    servers_per_host: 1
    hosts:
      - localhost
  test2:
    servers_per_host: 3
    hosts:
      - localhost

sserver:
  default:
    servers_per_host: 1
    hosts:
      - localhost
  test3:
    servers_per_host: 4
    hosts:
      - localhost

```

**Comment by ctubbsii** [comment]
Okay, so that does look like it's working then. As an aside, even though the current yaml seems to be very robust in terms of configurability, I'm wondering if the implementation would be simpler and the config file could be more intuitive, if the config were organized primarily by groups and hosts, rather than primarily by server types.

For example:

```yaml
groups:
  - default:
      hosts: [ localhost ]
      manager: 1
      monitor: 1
      gc: 1
      tserver: 1
      compactor: 1
      sserver: 1

  - test1:
      hosts: [ localhost ]
      tserver: 2

  - test2:
      hosts: [ localhost ]
      compactor: 3

  - test3:
      hosts: [ localhost ]
      sserver: 4
```

So now, the script becomes simpler: for each group, set up the group options (name, etc.), then for each host within that group, ssh, and for each service within that group during that ssh session, start up the service.

None of this is strictly necessary for your PR, but I'm mentioning it here, because I think it aligns your goal of making the scripts more efficient, by using a config that represents a simpler and more efficient program flow (and is also more intuitive).

One thing that could change from this suggestion, though, is instead of having just a count, each type could be a complex object like:

```yaml
      tserver:
        count: 2
        extra-opts: [ ]
```

**Comment by dlmarion** [comment]
So, I like the idea of centering the cluster.yaml on the group, but I think your example doesn't capture the fact that the different processes are likely running on different servers. Here is your example with that taken into account:

```
groups:
  - default:
      manager: 1
        - hosts:
           - localhost1
      monitor: 1
        - hosts:
           - localhost2
      gc: 1
        - hosts:
           - localhost3
      tserver: 1
        - hosts:
           - localhost1
      compactor: 1
        - hosts:
           - localhost2
      sserver: 1
        - hosts:
           - localhost3

  - test1:
      tserver: 2
        - hosts:
           - localhost1
           - localhost2

  - test2:
      compactor: 3
        - hosts:
           - localhost1
           - localhost2
           
  - test3:
      sserver: 4
        - hosts:
           - localhost2
           - localhost3
      
```

**Pull request merged**
