### PR TITLE
Remove old code that should have been removed with prior changes

### PR DESCRIPTION
**Pull request by dlmarion**

### CODE REVIEW

**Comment by milleruntime** [comment]
Looks OK. Would be nice to add a Test to FateCommandTest for `fate print`.

**Comment by ctubbsii** [comment]
Which prior changes should these have been associated with? Can you mention the commit or issue/PR number in the body of this commit log when you merge?

**Comment by dlmarion** [comment]
Yeah, sorry, will do. I was putting something up quickly for Mike, he ran into an issue while testing.

**Review by milleruntime — APPROVED** [review]
Nice! Assuming all the tests pass, LGTM.

**Comment by milleruntime** [comment]
I did think of one thing. You could use `assertThrows()` to catch the exceptions, when they are thrown.

**Comment by dlmarion** [comment]
> You could use assertThrows() to catch the exceptions, when they are thrown.

I'm not following - I'm not catching any exceptions in the test. There is some error information printed to output, but no error is thrown.

**Pull request merged**
