### PR TITLE
deprecates lru block cache and makes TinyLfu the new default

### PR DESCRIPTION
**Pull request by keith-turner**
If the TinyLfu cache works well as the default going forward then the LRU cache could eventually be dropped.

### CODE REVIEW

**Comment by keith-turner** [comment]
Opened this based on a conversation w/ @cshannon about 4.0 testing.  If we do all future testing with TinyLfu and it seems to work well and have no problems, then the lru cache code could eventually be dropped.

**Comment by keith-turner** [comment]
Ran `mvn verify -Psunny` successfully with these changes.

**Review by cshannon — APPROVED** [review]
Should we set the `forRemoval` flag to be true in the deprecated annotation? I guess if that's the case we'd be expected to remove it for sure from 4.0 so maybe we leave it as is and be more conservative.

**Comment by keith-turner** [comment]
> Should we set the forRemoval flag to be true in the deprecated annotation? I guess if that's the case we'd be expected to remove it for sure from 4.0 so maybe we leave it as is and be more conservative.

forRemoval has subtle problems and there was a PR that outlined those problems and removed its partial use in the code, but not sure what the PR number is.  For this particular code its unlikely users reference it any other way than configuring it, so that leaves the log message as the primary way of notifying the user of it deprecation.  I mainly added the deprecation annotation to avoid new direct uses in the accumulo code base.

**Pull request merged**
