### PR TITLE
Add createIfNotExists method to table/namespace operations

### LINKED ISSUE #418: Add createIfNotExists method to table/namespace operations
Currently, if you want to create a namespace or table in Accumulo that may already exists, you need to try to create it and ignore the exception.

```java 
  try {
      connector.namespaceOperations().create("mynamespace");
    } catch (NamespaceExistsException e) {
      // ignore
    }

    try {
      connector.tableOperations().create("mynamespace.mytable");
    } catch (TableExistsException e) {
      // ignore
    }
```

It would be nice if a `createIfNotExists` method was added to the API that ignored this exception. This would simplify the above code to the following:

```java
connector.namespaceOperations().createIfNotExists("mynamespace");
connector.tableOperations().createIfNotExists("mynamespace.mytable");
```

### PR DESCRIPTION
**Pull request by jkosh44**
Methods will create a namespace or table if one didn't exist otherwise
it does nothing. Both methods return a boolean to indicate whether a
table/namespace was created.

Closes #418

### CODE REVIEW

**Comment by jkosh44** [comment]
@milleruntime I had been running the Sunny Day tests, but I think I forgot to do it before the most recent push. I'll run this and re-push to get the proper formatting. Thanks for the pointer.

**Comment by milleruntime** [comment]
No problem.  Running verify with -Psunny is good to do once but running all the tests can be daunting and time consuming.  Keep an eye on your PR for "All checks have passed" above (one build is done by Apache servers, the other by Travis-CI).  The Apache Jenkins servers are very flaky but yours is looking good.  Let me know when you are good with this PR and I will merge for you.

**Comment by jkosh44** [comment]
I'm good with it if you are. Feel free to merge.

**Comment by milleruntime** [comment]
@keith-turner you OK with adding 2 new methods to the API?

**Pull request closed without merging**
