### PR TITLE
Add test and fix for bug in KeyBuilder

### PR DESCRIPTION
**Pull request by milleruntime**
Found this weird bug in `KeyBuilder` while working on #2117. The Java UTF-8 Charset encoder puts an empty byte at the end of the string when there is an underscore present and I can't figure out why. Opening this PR to show the test failure, if anyone has any ideas.

### CODE REVIEW

**Comment by Manno15** [comment]
I will help investigate the issue.

**Comment by Manno15** [comment]
From my testing (using your test), the issue appears to be more related to the length of the CharSequence than what is in the CharSequence.

**Comment by milleruntime** [comment]
> From my testing (using your test), the issue appears to be more related to the length of the CharSequence than what is in the CharSequence.

Yeah it looks like 10 or more characters comes back with an extra byte. While 9 characters or less is fine.

**Comment by milleruntime** [comment]
There is a simpler way to convert from `CharSequence` to byte array that I implemented it in 9c99225. I am not sure why the Java `CharsetEncoder` was used in the first place.

**Review by Manno15 — APPROVED** [review]
Confirmed that this fixes the issue

**Comment by milleruntime** [comment]
The original PR https://github.com/apache/accumulo/pull/145 for KeyBuilder used `CharsetEncoder` as a replacement for Text to avoid going from string->text->bytes. But I think this was an oversight as we can just go from String -> bytes and avoid the `CharBuffer` and `CharsetEncoder` expanding the byte array beyond the original size of the `CharSequence`.

**Pull request merged**
