### PR TITLE
ACCUMULO-2844 Removed 'slave' terminology

### PR DESCRIPTION
**Pull request by mikewalch**
* Replaced 'slave' with 'tserver' in most cases
* When referring to slave node, used the term 'worker'
* The 'slaves' configuration file is now 'tservers'
* All references to 'slave' were changed except for those in
  the design doc for ACCUMULO-378 which discusses replication

### CODE REVIEW

**Comment by mikewalch** [comment]
For testing, I built the Accumulo tarball and was able to start Accumulo successfully using the scripts.  I started Accumulo without the `tservers` and error messages were printed that the 'tservers' file could not be found.  I did not do any testing of the test scripts.

**Comment by mikewalch** [comment]
Below are the errors that are printed if `tservers` file is missing.

```
Starting monitor on localhost
Starting tablet servers ...egrep: /install/accumulo-2.0.0-SNAPSHOT/conf/tservers: No such file or directory
 done
2016-09-08 15:38:59,896 [util.NativeCodeLoader] WARN : Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2016-09-08 15:39:01,574 [server.Accumulo] INFO : Attempting to talk to zookeeper
2016-09-08 15:39:01,772 [server.Accumulo] INFO : ZooKeeper connected and initialized, attempting to talk to HDFS
2016-09-08 15:39:01,960 [server.Accumulo] INFO : Connected to HDFS
/install/accumulo-2.0.0-SNAPSHOT/bin/start-daemon.sh: line 67: /install/accumulo-2.0.0-SNAPSHOT/conf/tservers: No such file or directory
Starting master on localhost:
/install/accumulo-2.0.0-SNAPSHOT/bin/start-daemon.sh: line 67: /install/accumulo-2.0.0-SNAPSHOT/conf/tservers: No such file or directory
Starting gc on localhost
/install/accumulo-2.0.0-SNAPSHOT/bin/start-daemon.sh: line 67: /install/accumulo-2.0.0-SNAPSHOT/conf/tservers: No such file or directory
Starting tracer on localhost
```

**Comment by joshelser** [comment]
> Below are the errors that are printed if `tservers` file is missing.

Thoughts on how to address compatibility from the 1.x `slaves` file? Do we want to allow fall-back to ease upgrades? I would think so, although it looks like it would require changes in multiple places which is annoying.

**Comment by keith-turner** [comment]
> Thoughts on how to address compatibility from the 1.x slaves file?

At the very least we want clear error messages is the new file is not found, which we have.  Do not want users to waste a lot of time trying to figure out why its not starting.

> Do we want to allow fall-back to ease upgrades? 

-0.  Would be slightly helpful in the case of automation.   I think w/ the error message about a  missing tservers file, most users will quickly figure out what they need to do.   If we did do it may want to error in the case where tservers and slaves file both exist.  In case where only slaves files exist, could print an error message saying its deprecated and should be renamed.

**Comment by dimaspivak** [comment]
Should probably rename this PR; it's ACCUMULO-2844, not ACCUMULO-2884.

**Comment by mikewalch** [comment]
> Should probably rename this PR; it's ACCUMULO-2844, not ACCUMULO-2884.

Nice catch @dimaspivak. Will do

**Comment by joshelser** [comment]
> >    Do we want to allow fall-back to ease upgrades?
> -0. Would be slightly helpful in the case of automation. I think w/ the error message about a missing tservers file, most users will quickly figure out what they need to do. If we did do it may want to error in the case where tservers and slaves file both exist. In case where only slaves files exist, could print an error message saying its deprecated and should be renamed.

This sounds OK to me. We have a bit more leeway with a "real" major release than I'm used to. I think I would be OK with error'ing out of the script in the case when only the `slaves` file exists instead of just printing a message (catch it as early as possible and push people to rename now instead of delaying).

**Comment by mikewalch** [comment]
> This sounds OK to me. We have a bit more leeway with a "real" major release than I'm used to. I think I would be OK with error'ing out of the script in the case when only the slaves file exists instead of just printing a message (catch it as early as possible and push people to rename now instead of delaying).

I like this approach.  I don't like falling back to 'slaves' file if 'tservers' does not exist as all scripts that depend on 'tservers' need to do this.  A proper error message is sufficient.  It's an easy fix.  I will add the following checks to the script and update the PR:
* First, fail if 'slaves' file exists and tell user to rename file to 'tservers' or remove 'slaves' if both exist.  This will prevent users from having both files.
* Next, fail if 'tservers' does not exist

**Comment by joshelser** [comment]
>     First, fail if 'slaves' file exists and tell user to rename file to 'tservers' or remove 'slaves' if both exist. This will prevent users from having both files.
    Next, fail if 'tservers' does not exist


+1 on that plan

**Comment by mikewalch** [comment]
Added checks to scripts in c182f806daa48

**Comment by joshelser** [comment]
Created ACCUMULO-4449 for this "subset" of changes.

**Pull request closed without merging**
