### PR TITLE
ACCUMULO-3970

### PR DESCRIPTION
**Pull request by rweeks**
Here's a sketch of what I'm thinking for ACCUMULO-3970. It's by no means ready to be merged, I just want to send the PR as a starting point for a discussion.

The idea is to define a new type of iterator, a VisibilityTransformingIterator, which can be set on a table. The iterator is only active in scan scope and is applied before the scan authorizations. Concrete subclasses of the VisibilityTransformingIterator receive individual key-value pairs that are present in the table and, for each pair, produce zero or more extra representations of that value. How these extra representations are produced will probably be driven by how an organization wants to anonymize or de-identify its data.

### CODE REVIEW

**Comment by ctubbsii** [comment]
Test comment

**Comment by ctubbsii** [comment]
ACCUMULO-3970

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by milleruntime** [comment]
@rweeks Can I close this PR?  Looking at the feedback on the JIRA ticket, I take it folks were not comfortable with this change or felt that it was out of scope to include in Accumulo.

**Comment by milleruntime** [comment]
If no one objects over the next week, I will close this pull request.

**Comment by ctubbsii** [comment]
@milleruntime I think it's fine to close now. This PR was never intended to be merged. It can always be re-opened if there is consensus on including the feature in a future version, and the PR is updated with new merge-ready commits.

**Pull request closed without merging**
