### PR TITLE
Synchronize method shared between FaTE ops

### PR DESCRIPTION
**Pull request by dlmarion**
Added the synchronized modifier to CancelCompactions.mutateZooKeeper which
could be called from concurrent delete table or cancel compaction operations

### CODE REVIEW

**Review by milleruntime — APPROVED** [review]

**Comment by keith-turner** [comment]
Was there a problem observed with this code?  I ask because ZooReaderWriter. mutateExisting() is used by the code and that already offers concurrency protection. So curious why more is needed.

**Comment by dlmarion** [comment]
@keith-turner - you are saying that because of the table locks?

**Comment by keith-turner** [comment]
> @keith-turner - you are saying that because of the table locks?

I am asking because the call `zoo.mutateExisting(...)` should properly handle two concurrent threads attempting to modify the same ZK node.  So I am curious what problem synchronizing the method solves that the call to  `zoo.mutateExisting(...)` does not already address.

**Comment by dlmarion** [comment]
Yeah, I deleted my comment when I re-read yours and looked at the code. I'm not sure if it was a problem, I think it was something that @milleruntime saw looking at the code. I can revert easily enough. Waiting to hear from @milleruntime

**Comment by milleruntime** [comment]
> > @keith-turner - you are saying that because of the table locks?
> 
> I am asking because the call `zoo.mutateExisting(...)` should properly handle two concurrent threads attempting to modify the same ZK node. So I am curious what problem synchronizing the method solves that the call to `zoo.mutateExisting(...)` does not already address.

Are you saying that the way that method is written it should handle concurrent modifications?

**Comment by keith-turner** [comment]
> I was more concerned about what happens with ZK problems and 2 separate operations trying to modify the same exact node.

If there is a problem with that, then its a bigger problem because many places in the code use mutateExisting.

**Comment by keith-turner** [comment]
> Are you saying that the way that method is written it should handle concurrent modifications?

Yeah it hopefully should.  The mutateExisting code gets the stat from ZK when it reads the node and when it writes back out to ZK it passes the stat version.  If the version has changes, then ZK should throw an exception causing the mutate operation to retry.

https://github.com/apache/accumulo/blob/48e31af4962660dd1c09054cd5128a30f86b3c71/core/src/main/java/org/apache/accumulo/fate/zookeeper/ZooReaderWriter.java#L182-L195

**Comment by keith-turner** [comment]
If the added sync is not fixing any problems, then it has the potential to cause problems.  Since its a static sync it can cause FATE txs that are completely unrelated to each other to wait on each other.

**Comment by milleruntime** [comment]
> If the added sync is not fixing any problems, then it has the potential to cause problems. Since its a static sync it can cause FATE txs that are completely unrelated to each other to wait on each other.

What about sync'ing on an object? TableId maybe?

**Comment by keith-turner** [comment]
> What about sync'ing on an object? TableId maybe?

Sure, could have more granular sync. But why is it needed?

**Comment by dlmarion** [comment]
Based on something @ctubbsii said the other day, I wonder if sync() should be called when BADVERSION is encountered. See the note at https://zookeeper.apache.org/doc/r3.6.3/zookeeperProgrammers.html#ch_zkGuarantees.

**Comment by dlmarion** [comment]
So, am I reverting this commit?

**Comment by keith-turner** [comment]
> So, am I reverting this commit?

I would be in favor of that, unless there is a problem it fixes.  The static lock can cause contention.

**Comment by milleruntime** [comment]
> > So, am I reverting this commit?
> 
> I would be in favor of that, unless there is a problem it fixes. The static lock can cause contention.

Sounds like it would be better to revert to prevent lock contention but I am not sure what @EdColeman is saying about ZK.

**Pull request merged**
