### PR TITLE
fixes order of thread pool adjustment

### PR DESCRIPTION
**Pull request by keith-turner**
When looking into #2276 I noticed that some of the existing methods called thread pool methods in a very specific order depending on if they were increasing or decreasing.  I think this order used to matter and avoided bugs, not sure if it still does.  Opened this PR just in case it does matter, have not test it though.

Also copied a logging statement over from one of the existing methods.

### CODE REVIEW

**Comment by dlmarion** [comment]
@keith-turner - I didn't realize that the order of those calls mattered. Good catch. Looks good to me.

**Review by dlmarion — APPROVED** [review]

**Review by EdColeman — APPROVED** [review]

**Comment by dlmarion** [comment]
I included this change in https://github.com/apache/accumulo/pull/2278

**Comment by keith-turner** [comment]
> I included this change in #2278

After #2278 is merged we can close this.

**Review by ctubbsii — APPROVED** [review]

**Comment by dlmarion** [comment]
@keith-turner  - #2278 has been merged.

**Pull request closed without merging**
