### PR TITLE
Fix #2078 - Marked modifier of fields store, environment and keepRunning in Fate.java as final.

### LINKED ISSUE #2078: Variables in org.apache.accumulo.fate.FATE class can be final.
The fields store, environment and executor can be marked final in [FATE](https://github.com/apache/accumulo/blob/552fd33407f9346fba45525f3abb36864de2ea09/core/src/main/java/org/apache/accumulo/fate/Fate.java#L51)

### PR DESCRIPTION
**Pull request by Akshit6828**
Fixed #2078.

### CODE REVIEW

**Comment by Akshit6828** [comment]
Fix #2078 - Reverted modifier 'executor' to private and marked 'keepRunning' as final.

**Review by EdColeman — APPROVED** [review]

**Comment by EdColeman** [comment]
Thanks for the PR @Akshit6828.  If you wish to be added as a contributor to https://accumulo.apache.org/people/ , please open a pull request to add yourself at https://github.com/apache/accumulo-website/edit/main/pages/people.md and leave a reference to #2080 in your commit log.

If you intend to be a regular contributor to Accumulo projects, please consider subscribing to our developer mailing list (https://accumulo.apache.org/contact-us/) and introducing yourself.

**Comment by Akshit6828** [comment]
Sure @EdColeman. Thanks for giving me this chance. I am honoured to be added as a contributor. 😃

**Comment by Akshit6828** [comment]
Hi, @EdColeman  I have submitted the PR https://github.com/apache/accumulo-website/pull/281. Please check it and update me about the checks.

**Pull request merged**
