### PR TITLE
Add 3 ITs to Sunny Tests. Closes #2147

### LINKED ISSUE #2147: Revaluate Sunny Test profile
The sunny test profile feel a little incomplete as it is currently only running 4 ITs (@Category(SunnyDayTests.class):
<pre>
test/src/main/java/org/apache/accumulo/test/functional/NativeMapIT.java:@Category(SunnyDayTests.class)
test/src/main/java/org/apache/accumulo/test/rpc/ThriftBehaviorIT.java:@Category(SunnyDayTests.class)
test/src/main/java/org/apache/accumulo/test/InMemoryMapIT.java:@Category(SunnyDayTests.class)
test/src/main/java/org/apache/accumulo/test/start/KeywordStartIT.java:@Category(SunnyDayTests.class)
</pre>

I think we could add a few ITs to make sure we have basic functionality covered. I think including ITs dealing with compactions, the metadata table, bulk import or write ahead logs would be good.

### PR DESCRIPTION
**Pull request by milleruntime**
Add ITs for bulk import, WALs and iterators to Sunny Day profile

### CODE REVIEW

**Review by DomGarguilo — APPROVED** [review]
Looks good to me. Only adds about 10 seconds for me

**Comment by Manno15** [comment]
Are there any possible reliability issues with these tests?

**Review by Manno15 — APPROVED** [review]

**Comment by milleruntime** [comment]
> Are there any possible reliability issues with these tests?

I considered that when picking them and I don't recall these being flaky. They haven't failed the Jenkins build in the past year either.

**Comment by milleruntime** [comment]
I will go ahead and merge. These can easily be removed if someone doesn't like them in the profile or we find them to be flaky.

**Pull request merged**
