### PR TITLE
 Misc ThriftTransportPool improvements

### PR DESCRIPTION
**Pull request by keith-turner**

### CODE REVIEW

**Comment by ctubbsii** [comment]
@keith-turner This issue never really had any description of what these improvements were intended to achieve. Can you briefly summarize here what the overall intent was, to give some context?

**Comment by keith-turner** [comment]
@ctubbsii I  opened #1548 to add documentation to the code.  I also modified the code to use methods present in Dequeue that are more descriptive.

**Comment by ctubbsii** [comment]
@keith-turner Thanks. #1548 looks good to me to document what the new code does. However, I was more asking about the changeset... something that referenced the change itself and the basic reason, as in "Use Deque instead of LinkedList for CachedConnections because X". I can't tell without a deeper dive, but I *think* there was no change in behavior, so X here would be something like "more efficient retrieval of recent connections". A one-liner something along those lines would be better than the current "Misc improvements" comment (although we can't change history, I thought it would be nice to document here for reference).

**Comment by keith-turner** [comment]
It certainly could have had a better commit message.  I can't remember the specifics of how this came to be.  The goal was to avoid a linear search when removing idle connections.

**Comment by jzgithub1** [comment]
@ctubbsii  and @keith-turner .  I think you are getting to the root of the problem of the intermittent failure of the TransportCachingIT.testCachedTransport with this improvement (#1542).  The flakiness of that test is showing a problem with the function 
```java 
private TTransport getTransport(ThriftTransportKey cacheKey)
```
in my opinion.  I will make comments on that issue also.

**Comment by ctubbsii** [comment]
> The goal was to avoid a linear search when removing idle connections.

Thanks. That helps.

**Pull request merged**
