### PR TITLE
Convert Monitor table problems to datatables. Fixes #1719

### LINKED ISSUE #1719: Per Table problem links not working in Monitor
On the Monitor if there are table problems (Debug menu -> Table problems) the page will get populated with links.  The links in the Summary table under the "Table" column do not work.  The links in the "Table" column in the Details table do work though and will take you to the table status page for that table. See screenshot.

per-table-problem-bug-marked

### PR DESCRIPTION
**Pull request by milleruntime**
This will fix the bug but we lose the ability to filter the details table.  I couldn't get the search box to look right with the two tables and don't think its intuitive to be used to filter anyway.  I think the making the table links filter the details table can be a follow on task.  This PR just makes the links go to the table page.

pertable-problem-fix

### CODE REVIEW

**Comment by milleruntime** [comment]
The Time column I set as a duration when it should be a date.  I am in the process of fixing.

**Comment by milleruntime** [comment]
So I went to test the link to "clear all problems" from a particular table and it cleared out all the problems.  This would be fine, except it cleared all problems from all tables. *sigh* now I have no more test data.

@keith-turner would you happen know of an easy way to trigger a table problem manually?  The only problem I was able to see (and this was only by luck after running a bunch of Standalone ITs and got uno into a bad state) was "Error recovering tablet from log files".  I am going to try an corrupt a WAL and see if that works.

**Comment by milleruntime** [comment]
> @keith-turner would you happen know of an easy way to trigger a table problem manually? 

I was able to generate a table problem message by overriding an r-file and trying to scan the table.

**Review by ctubbsii — APPROVED** [review]
Looks okay to me at a glance. I don't know how to review it without actually running it (which I don't have time to do right this moment). The proof is whether it works. :smiley_cat:

**Comment by Manno15** [comment]
I will try to run this on my end today to see if I can give any feedback.

**Comment by Manno15** [comment]
I was able to create a table problem and confirmed all the links work as expected. All the other details in the details table are accurate as well. +1 from me.

**Comment by milleruntime** [comment]
Thanks @Manno15 and @ctubbsii !

**Comment by milleruntime** [comment]
@Manno15 if you still have the logs for your test, can you check the Monitor log for errors? When I click "clear All testtable problems" it doesn't refresh.  I think the query is timing out.  I see this error in the Monitor Log:
```
2020-10-02T14:42:02,943 [clientImpl.ThriftScanner] DEBUG: Failed to locate tablet for table : !0 row : ~err_^@
2020-10-02T14:42:09,275 [monitor.Monitor] INFO : Failed to obtain problem reports 
java.lang.RuntimeException: org.apache.accumulo.core.clientImpl.ThriftScanner$ScanTimedOutException
        at org.apache.accumulo.core.clientImpl.ScannerIterator.getNextBatch(ScannerIterator.java:184) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.clientImpl.ScannerIterator.hasNext(ScannerIterator.java:109) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.problems.ProblemReports$1.hasNext(ProblemReports.java:246) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.server.problems.ProblemReports.summarize(ProblemReports.java:301) ~[accumulo-server-base-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.monitor.Monitor.fetchData(Monitor.java:359) ~[accumulo-monitor-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.monitor.Monitor.lambda$run$0(Monitor.java:478) ~[accumulo-monitor-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:37) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.apache.accumulo.core.clientImpl.ThriftScanner$ScanTimedOutException
        at org.apache.accumulo.core.clientImpl.ThriftScanner.scan(ThriftScanner.java:263) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.clientImpl.ScannerIterator.readBatch(ScannerIterator.java:155) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.clientImpl.ScannerIterator.getNextBatch(ScannerIterator.java:173) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        ... 7 more
```

This could be because I corrupted my test table and it can't scan.  It should still be able to scan the metadata though.

**Comment by Manno15** [comment]
@milleruntime I am not at work anymore. I can check my logs Monday if you still need them. Sorry! Also, for my test I made my table error on compaction so I believe I was still lable to scan. I can try repeating your process so I can get better results.

**Comment by milleruntime** [comment]
> This could be because I corrupted my test table and it can't scan. It should still be able to scan the metadata though.

This error is probably unrelated to the table not refreshing.  I think this scan timeout was happening when I restarted my tserver.

**Comment by Manno15** [comment]
@milleruntime Do you still need to see my logs?

**Comment by milleruntime** [comment]
> @milleruntime Do you still need to see my logs?

No thats OK thanks.  I was curious if you saw any issues with the tables refreshing after you click any of the clear links.

**Comment by Manno15** [comment]
Nope, that I recall

**Comment by milleruntime** [comment]
OK sounds good.  I pushed a minor fix that just cleaned up the JS refresh functions but I think the issues were mainly with how I was corrupting my tables.

**Pull request merged**
