### PR TITLE
Implementation of SeekingFilter, CfCqSliceFilter and CfCqSliceSeekingFilter

### PR DESCRIPTION
**Pull request by rweeks**
Implementation for ACCUMULO-3691 including a filter which behaves similarly to the existing ColumnSliceFilter but can seek to the next potential match instead of explicitly rejecting every KV pair that falls outside the slice. Probably faster for small slices on large rows.

### CODE REVIEW

**Comment by rweeks** [comment]
Ahh shoot I could do better with some javadoc [here|https://github.com/apache/accumulo/pull/41/files#diff-f2f053c299562ad7fa7ca3d67a3a782bR57] and elsewhere. I'm not sure how to revoke a pull request but I'll add some documentation and resubmit.

**Comment by ctubbsii** [comment]
This pull request should be for ACCUMULO-3961.

**Comment by rweeks** [comment]
Wow, I am really off the ball today. Sorry. I'll close this request.

**Comment by keith-turner** [comment]
This is neat.   Some class level javadoc on SeekingFilter would also be nice

**Pull request closed without merging**
