### PR TITLE
Add correct property versions

### LINKED ISSUE #3085: 3 Properties with version X.X.X in 2.1
There are 3 properties in Property.java that have "X.X.X" as their version. I think they were added in 2.1.0 as they are marked experimental and related to the crypto services. @milleruntime - do you know?

### PR DESCRIPTION
**Pull request by ddanielr**
Sets "X.X.X" property versions to their correct "2.1.0" context. 

closes #3085

### CODE REVIEW

**Review by Manno15 — APPROVED** [review]
Changes look good.

**Comment by ctubbsii** [comment]
Please double check the target branch and marked fix version before merging PRs. This one was merged to main, but the original ticket had triaged this issue and marked it for 2.1.1. This now needs to be backported into 2.1.1, and merged forward again into the main branch using a new PR against the 2.1 branch.

**Comment by ctubbsii** [comment]
I cherry-picked this to the 2.1 branch in c8e1500a69f9c52e9eba58b1407b9ccc86d41739 and merged it forward in fddb41e711b05b6dbec21805d579b8216d47418a
So, nothing further needs to be done here to backport.

**Comment by ctubbsii** [comment]
Thanks for the PR @ddanielr . I think this might be you first contribution to the project. If you wish to be added as a contributor to https://accumulo.apache.org/people/ , please open a pull request to add yourself at https://github.com/apache/accumulo-website/edit/main/pages/people.md (in order) and leave a reference to `apache/accumulo#3132` in your commit log.

If you intend to be a regular contributor to Accumulo projects, please consider subscribing to our developer mailing list (https://accumulo.apache.org/contact-us/) and introducing yourself. :smiley_cat:

**Comment by cshannon** [comment]
> @cshannon Please double check the target branch and marked fix version before merging PRs. This one was merged to main, but the original ticket had triaged this issue and marked it for 2.1.1. This now needs to be backported into 2.1.1, and merged forward again into the main branch using a new PR against the 2.1 branch.

Sorry about that, I usually check that but forgot in this case when I merged, I'll double check in the future. It would be nice if there was some way for Github to warn when merging if the target doesn't match the right branch but I doubt that's possible since the versions we have are not tied to branches in any real way.

**Comment by ddanielr** [comment]
This was my fault, I didn't double check my target branch when staging the PR. Agree with @cshannon that a warn message on merging would be great from a tooling perspective.

**Pull request merged**
