### PR TITLE
Convert all tests to assertThrows

### PR DESCRIPTION
**Pull request by DomGarguilo**
The goal of this PR is to convert all usage of the older `@Test(expected = ...` form of exception testing to the newer `assertThrows()`.

An example conversion:
```java
  @Test(expected = IllegalArgumentException.class)
  public void testNegativeTimeout() {
    BatchWriterConfig bwConfig = new BatchWriterConfig();
    bwConfig.setTimeout(-1, TimeUnit.DAYS);
  }
```
Would become:
```java
  @Test
  public void testNegativeTimeout() {
    BatchWriterConfig bwConfig = new BatchWriterConfig();
    assertThrows(IllegalArgumentException.class, () -> bwConfig.setTimeout(-1, TimeUnit.DAYS));
  }
```

I used this command to verify all tests that were changed still pass:
`mvn clean verify -Dit.test=ConditionalWriterIT,ReadWriteIT,KerberosIT,MetaConstraintRetryIT,ShellServerIT,BulkNewIT,ZooKeeperPropertiesIT,AccumuloInputFormatIT,NewTableConfigurationIT,MetaSplitIT,CloneTestIT -Dtest=ZooReaderWriterTest,TabletMetadataTest,TCredentialsUpdatingInvocationHandlerTest,AuthorizationsTest,FastFormatTest,ReplicationProcessorTest,TabletLocationStateTest,RelativeKeyTest,InMemoryMapTest,GarbageCollectionTest,OpTimerTest,ConfigCheckUtilTest,ScannerOptionsTest,ConfigurationTypeHelperTest,LogFileKeyTest,DefaultFormatterTest,SortedMapIteratorTest,TabletServerSyncCheckTest,LoadPlanTest,MetadataTimeTest,Upgrader9to10Test,ZooAuthenticationKeyDistributorTest,AuthenticationTokenSecretManagerTest,MutationTest,AccumuloConfigurationTest,ArrayByteSequenceTest,ListLexicoderTest,HadoopCredentialProviderTest,WholeRowIteratorTest,ConditionTest,ProblemReportingIteratorTest,UnsynchronizedBufferTest,TabletTimeTest,ManagerReplicationCoordinatorTest,IteratorSettingTest,TabletMutationPrepAttemptTest,ZooSessionTest,ValueTest,TServerUtilsTest,SpaceAwareVolumeChooserTest,RFileTest,BatchWriterConfigTest,LinkingIteratorTest,HexFormatterTest,RFileClientTest,CredentialProviderTokenTest,PasswordConverterTest,ReplicationSchemaTest,ServerContextTest,DelegationTokenConfigTest,KeyTest,ThriftTransportKeyTest,SequenceLexicoderTest,AccumuloTest,AuthenticationKeyTest,RowEncodingIteratorTest,ShellUtilTest,ZooKeeperInstanceTest -Dspotbugs.skip -Dtimeout.factor=1`

### CODE REVIEW

**Comment by milleruntime** [comment]
@DomGarguilo I would prefer general code improvements like this that touch a lot of files to be merged in the next version (most likely 2.2) so to not slow down the 2.1 release. Did you have a reason why this needs to be in 2.1?

**Comment by DomGarguilo** [comment]
> Did you have a reason why this needs to be in 2.1?

Nope, it can wait. Do you think I should mark this as draft until then?

**Comment by milleruntime** [comment]
> > Did you have a reason why this needs to be in 2.1?
> 
> Nope, it can wait. Do you think I should mark this as draft until then?

I was thinking we could create a temporary branch for 2.2 then merge it when we release 2.1. @ctubbsii any thoughts on this?

**Review by ctubbsii — APPROVED** [review]
I just did a thorough review of this, and it's all good. However, I did find a few additional fixes that I have prepared subsequent PR for, so I'll merge this now so I can open that.

**Comment by ctubbsii** [comment]
> @DomGarguilo I would prefer general code improvements like this that touch a lot of files to be merged in the next version (most likely 2.2) so to not slow down the 2.1 release. Did you have a reason why this needs to be in 2.1?

These are all test files, with a very predictable fix, that I need to get merged for my subsequent fixes. I don't think there's a reason to delay on this.

**Comment by DomGarguilo** [comment]
Either merging now or waiting until after 2.1.0 is released is fine with me. What do you think, @milleruntime?

This change (#2435), which can stand alone, is a precursor to a set of other changes I have in mind that relate to upgrading JUnit from version 4 to 5. Those future changes, which may look similar to those in #2427, may be more disruptive and I am assuming we would want to hold off on a lot of those changes until after the 2.1.0 release. This PR might be fine to merge but for changes like that, should we just hold off on working on those altogether or should there be a separate branch for them like @milleruntime suggested?

**Comment by milleruntime** [comment]
This can be merged. I talked to Ed and he is OK with the changes.

**Review by EdColeman — APPROVED** [review]
I think these changes should be okay to merge - I didn't look at the specific changes, but from the discussion, this PR seems to be moving things in the direction we would want to go - and it is not adding junit 5 specific changes so it seem like something that can go in now rather than waiting.

**Comment by ctubbsii** [comment]
My followup changes to this are in #2436

**Pull request merged**
