### PR TITLE
ACCUMULO-4494 Add families and inclusive to IteratorTestInput

### PR DESCRIPTION
**Pull request by dhutchis**
Changed the relevant tests to use the new information.
Added equals() and hashCode() for good measure.
By default the families is empty and inclusive is false,
so no existing code should break.
Inserted a couple side changes to clear compiler warnings.

### CODE REVIEW

**Comment by dhutchis** [comment]
As an aside, it would be nice to make `AccumuloTestInput` a final class, which would guarantee its immutability.

I would also like to make the helper methods in all the test case classes (such as `IsolatedDeepCopiesTestCase`) private.

However, both these changes could break a user's code.

**Comment by joshelser** [comment]
>  By default the families is empty and inclusive is false,
so no existing code should break.

Agreed.

> I would also like to make the helper methods in all the test case classes (such as IsolatedDeepCopiesTestCase) private.

I think this is fine. Users running the framework shouldn't be looking inside the test cases. This is also outside of public API (which should be corrected...).

Thanks for putting this together @dhutchis. Let me express my enthusiasm by committing for you :)

**Comment by joshelser** [comment]
Ok, running a test and will commit. I did make two minors changes:

1. Removed the assert in favor of throwing an IllegalStateException (to match convention)
2. Switched the null-check and `getClass()` check in favor of `instanceof` which does both.

**Comment by dhutchis** [comment]
Thanks Josh!

**Pull request closed without merging**
