### PR TITLE
Increased number of locks in SynchronousLoadingBlockCache and set them to be fair

### PR DESCRIPTION
**Pull request by dlmarion**
SynchronousLoadingBlockCache was introduced in ACCUMULO-4641. The code in this class used to be located in LruBlockCache. In ACCUMULO-4641 the number of load locks was reduced from 5003 to 2017. There is no comment as to why this was done, but it was something I noticed while looking at the fairness of the load locks. This commit resets the default size back to 5003, as it was in 1.10.x. This commit also changes the load locks to be fair, which allows the different scan threads in the tablet / scan server to make progress when there is a collision and multiple threads use the same lock.

### CODE REVIEW

**Comment by cshannon** [comment]
Was there an actual issue observed that caused you to change to using fair locks? Whenever I've done any reading into the topic fair locks are generally discouraged due to the performance penalty that often happens.

**Comment by dlmarion** [comment]
User saw scan threads waiting on the lock, so some scans were making progress and others were not.

**Comment by cshannon** [comment]
Something else I noticed is that it would be good to change this line here even though it's not related to the PR. 

https://github.com/apache/accumulo/blob/49d335313f18275a66e604e274db9ba6895a4373/core/src/main/java/org/apache/accumulo/core/file/blockfile/cache/lru/SynchronousLoadingBlockCache.java#L116-L118

The call to lock() should always be outside of the try block so it should be: 

```java
loadLock.lock();
try {
   ...
```

This is because if the call to lock() fails you can end up with an IllegalMonitorStateException when the thread calls unlock() in the finally block since it doesn't own the lock. In practice this would be pretty rare as lock() _shouldn't_ ever really throw an exception. It's much more of an issue if you use something like `lockInterruptibly()` but it's still best practice to have it outside the try block.

**Review by keith-turner — APPROVED** [review]
Since loading a block from persistent storage may be a slow operation I think it makes sense to use fair locks.  If fair locks are slower than non-fair, they are hopefully still orders or magnitude faster than loading the missed block.  So since the operation is slow, using a fair queue seems really good for operations queued up waiting their turn.

As for the increasing the arrays size from 2017 to 5003, that seems good in that it should lower the chance of collisions.  The only ill effect of a larger array size that I can think of is that may increase the chance of processor cache misses.  However this probably is not relevant and even if it were it would probably be inconsequential relative to the cost of loading the block.

**Comment by ctubbsii** [comment]
If GitHub has to show `...` for the first line of a commit message, it is a good hint that it's far too long. We've had several very long "subject" line portions in our git logs. This was the most recent one I noticed (but not the worst). It would be a good goal to keep very brief subject lines in the git logs, and put more details in the body.

For example, here's my attempt to polish up this commit message's subject line (solely as an example for how it could be done for future commits):

```diff
-Increased number of locks in SynchronousLoadingBlockCache and set them to be fair (#3175)
+Improve lock behavior in SynchronousLoadingBlockCache (#3175)
```

The body already describes what the improvements are (increasing the count and making them fair), so we don't need those details in the subject line.

**Pull request merged**
