### PR TITLE
ACCUMULO-4704 Check for use of Guava @Beta

### PR DESCRIPTION
**Pull request by ctubbsii**
Use findbugs plugin to avoid use of Guava @Beta methods and classes

### CODE REVIEW

**Comment by milleruntime** [comment]
I'd like to run this to see if it picks up anything else.  I should be able to run it today.

**Comment by ctubbsii** [comment]
@milleruntime  There's still a few that this picks up. I'll see if I can take care of those if you don't get to it first.

**Comment by ctubbsii** [comment]
Okay, so it picks up a *lot* more than I had initially realized. It turns out that many things in Guava are still marked "Beta" in the version we're using (14.0.1).

The Cache stuff has dropped Beta status in the latest version, and hasn't changed its APIs, so those are probably safe to add to the findbugs exclude-filter.xml files. There's a few others I haven't been able to check yet if they are still Beta.

**Comment by milleruntime** [comment]
I am working my way through them.  I can push to your branch as I go, just let me know

**Comment by milleruntime** [comment]
Adding findbug exceptions for our classes is problematic because you can't just say "ignore Guava Cache classes".  There is a pull request against this plug-in that would help a lot: https://github.com/overstock/library-detectors/pull/2

I am thinking once we run this plug-in against 1.7 and 1.8 and make changes that we don't want it to run all the time.  We should just put it in Master.

**Comment by ctubbsii** [comment]
> Adding findbug exceptions for our classes is problematic because you can't just say "ignore Guava Cache classes".

Yeah, I ran into that, too. :frowning_face: 

> I am thinking once we run this plug-in against 1.7 and 1.8 and make changes that we don't want it to run all the time. We should just put it in Master.

:+1:

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by milleruntime** [comment]
@ctubbsii I sent you an update to this branch for the recently released 1.2 of the library-detetors plugin.  I added the exceptions to the pom that we were missing so it will successfully run against current 1.7 code.  Although now I am thinking we want to close this PR and just make these changes against master.

**Comment by milleruntime** [comment]
Closing in favor of #340

**Pull request closed without merging**
