### PR TITLE
Fix faulty test: `SortedLogRecoveryTest.testMissingDefinition`

### LINKED ISSUE #2489: Faulty test: SortedLogRecoveryTest
**Describe the bug**
The sorted log recovery test is not behaving as intended.
https://github.com/apache/accumulo/blob/3ea979d5971016b9c2512a96cc5b6bd5d1969b2e/server/tserver/src/test/java/org/apache/accumulo/tserver/log/SortedLogRecoveryTest.java#L348-L359

It looks like the test is expecting an exception to be thrown from `recover()` which does not happen.

What the test is currently doing is calling `recover()` which executes without throwing an error. Then, the test hits `fail()` every time which is caught in the catch block and ignored.

So, there are two problems:

1. The test will always pass (regardless of whether `recover()` throws and exception or not).
2. From my testing, `recover()` never throws an exception in this test which means it most likely has a faulty premise.

We need to determine whether `recover()` should indeed be failing or not and fix the logic that checks that condition.

### PR DESCRIPTION
**Pull request by DomGarguilo**
Closes #2489

The changes in this PR delete `SortedLogRecoveryTest.testMissingDefinition()`.

Based off the name of the test (testMissingDefinition) it seems that this test assumes that an exception will be thrown when there is no definition present. Instead, this information is just logged and does not cause an exception to be thrown:
```
[log.SortedLogRecovery] INFO : Tablet table<< is not defined in recovery logs [testlog]
```
Additionally, this test is incorrectly set up to handle the `fail()` statement which will just be caught in the catch block instead of making the test actually fail.

### CODE REVIEW

**Comment by ctubbsii** [comment]
> this test assumes that an exception will be thrown when there is no definition present

Did this code ever throw an exception in that case in the git history? If so, when and why did it change? Should it throw an exception?

**Comment by DomGarguilo** [comment]
> Did this code ever throw an exception in that case in the git history? If so, when and why did it change? Should it throw an exception?

Yea it looks like it was changed from throwing and exception to logging [here](https://github.com/apache/accumulo/commit/ef9c0044e5e2de5e616c21527ed5df5baed3b254) which stems from [this Jira ticket](https://issues.apache.org/jira/browse/ACCUMULO-1033). According to the jira ticket, it was purposefully changed to logging. This was probably not picked up sooner because the test will always pass regardless of whether something is thrown or not.

**Comment by ctubbsii** [comment]
In that case, I think the test should be modified instead of removed, to ensure that it doesn't throw an exception in that case, to prevent a regression... unless there's already a test that does that.

**Comment by DomGarguilo** [comment]
> In that case, I think the test should be modified instead of removed, to ensure that it doesn't throw an exception in that case, to prevent a regression... unless there's already a test that does that.

Good point. I did not consider that. I'll make sure that case is covered one way or another.

**Review by ctubbsii — APPROVED** [review]

**Pull request merged**
