### PR TITLE
Added code to determine Accumulo version from running tserver

### PR DESCRIPTION
**Pull request by lstav**
Fixes ACCUMULO-4061, tserver Accumulo version is now available. 

As discussed in #200, I separated the PRs for 4061 and 4558.

### CODE REVIEW

**Comment by milleruntime** [comment]
Looks good.  This is the minimum we need for now and can revisit the other changes later.  I can merge this since its already been discussed and reviewed elsewhere.

**Comment by ctubbsii** [comment]
Does this change cause the new version field to appear in a REST endpoint anywhere? I don't see any monitor code changes, but if the object is being dumped to JSON, there may not need to be any explicit changes in the REST code.

**Comment by milleruntime** [comment]
No its not in this PR.  I don't know if you or @lstav wanted it to be a REST endpoint but this just has the version added to Thrift and a getVersion to tserver.

**Comment by lstav** [comment]
I figured that adding this to the REST endpoint would be on another PR, like @milleruntime said, this is just to add the version to Thrift and the method in tserver. I think that for that PR we could also include adding the version as a column on the Tserver page of the Monitor site.

**Comment by lstav** [comment]
Closing since it was already merged, will add the version to the REST api on another PR

**Pull request closed without merging**
