### PR TITLE
Removed TableInfo.majors field

### LINKED ISSUE #3609: Remove TableInfo.major field from thrift struct
The field in the thrift struct was populated by code removed in #3604.  Need to remove this field and all the code that uses it in the rest of Accumulo.  This may be related to #3608 and #3594, maybe all can be done in the same PR, not sure.

### PR DESCRIPTION
**Pull request by dlmarion**
Fixes #3609

### CODE REVIEW

**Comment by dlmarion** [comment]
Before this change, the Monitor would likely show `0(0)` for major compactions on the tserver page. I'm not sure what it will show now, it could even be broken. However, we might need to re-imagine how the Monitor is going to work anyway.

**Comment by keith-turner** [comment]
> Before this change, the Monitor would likely show 0(0) for major compactions on the tserver page. I'm not sure what it will show now, it could even be broken. However, we might need to re-imagine how the Monitor is going to work anyway.

Interesting, we do need to decide what we want to do with that column in monitor.  We could still gather per table information on queued and running compactions, but it would be done in a very different way that in used to.  May need a follow on issue for that.

**Review by keith-turner — APPROVED** [review]
Thinking before this and its issue is closed out, need to open a new issue to decide what do with the column in the monitor.

**Comment by dlmarion** [comment]
> Thinking before this and its issue is closed out, need to open a new issue to decide what do with the column in the monitor.

Do you think this is covered by #3608?

**Comment by keith-turner** [comment]
> Do you think this is covered by https://github.com/apache/accumulo/issues/3608?

I added a comment to the issue about what still needs to be done.

**Pull request merged**
