### PR TITLE
Refactor AccumuloStoreReadWriteIT to also run against ZooStore

### PR DESCRIPTION
**Pull request by cshannon**
This renames AccumuloStoreReadWriteIT to FateStoreIT and adds an implementation for both the Accumulo and Zookeeper Fate stores. The tests in this class apply to both so this change allows all the tests to run against both implementations

The helper executor methods that were part of FateIT were moved into FateTestRunner to be re-used between the FateIT and FateStoreIT tests.

### CODE REVIEW

**Comment by cshannon** [comment]
I was hoping git would detect the file rename (it did initially) but after adding more changes it no longer detected `AccumuloStoreReadWriteIT` being renamed to `FateStoreIT` so it shows up as a delete/create in the diff.

**Comment by keith-turner** [comment]
> I was hoping git would detect the file rename (it did initially) but after adding more changes it no longer detected AccumuloStoreReadWriteIT being renamed to FateStoreIT so it shows up as a delete/create in the diff.

That would have been nice.  Were any changes made to the actual tests?

**Comment by cshannon** [comment]
> > I was hoping git would detect the file rename (it did initially) but after adding more changes it no longer detected AccumuloStoreReadWriteIT being renamed to FateStoreIT so it shows up as a delete/create in the diff.
> 
> That would have been nice. Were any changes made to the actual tests?

There were some, I refactored the class a bit so it was abstract and uses the helper executor stuff so that the child classes handle the actual creation of the store. But the logic in the 3 tests themselves are basically identical so i was surprised it didn't detect the rename as so much of the file is the same.

**Review by keith-turner — APPROVED** [review]

**Comment by keith-turner** [comment]
> But the logic in the 3 tests themselves are basically identical

ok, I didn't look at the actual test.  Just looked a the changes around the test to support both stores.

**Comment by cshannon** [comment]
> ok, I didn't look at the actual test. Just looked a the changes around the test to support both stores.

Sounds good, yeah the tests didn't change so you already reviewed it. I could have done a separate rename commit first and pushed that to elasticity but not a big deal so i'll just merge this as.

**Pull request merged**
