### PR TITLE
Call requireSame(SUSPEND) in MetaDataStateStore to resolve TODO

### PR DESCRIPTION
**Pull request by dlmarion**

### CODE REVIEW

**Review by cshannon — CHANGES_REQUESTED** [review]
It would be good to add a test to `AmpleConditionalWriterIT` to verify that the condition for `SUSPEND` in requireSame works as intended, similar to the recently added test I created for the new `USER_COMPACTION_REQUESTED` column in #4254

**Comment by dlmarion** [comment]
> It would be good to add a test to `AmpleConditionalWriterIT` to verify that the condition for `SUSPEND` in requireSame works as intended

Test added in 309ffa2

**Review by cshannon — APPROVED** [review]
The test LGTM but it takes a long time to run, it takes 4 minutes when I run it so it might be worth tweaking some of the test configs. For example, I tried changing the `TABLE_SUSPEND_DURATION` property to 30 seconds from 3 minutes and that cut down the test run time to 2 minutes. I'm not sure if there are any other tweaks that could be made too (maybe the `MANAGER_TABLET_GROUP_WATCHER_INTERVAL` to speed up the check but that's not a table config)

**Comment by dlmarion** [comment]
> The test LGTM but it takes a long time to run, it takes 4 minutes when I run it so it might be worth tweaking some of the test configs. For example, I tried changing the `TABLE_SUSPEND_DURATION` property to 30 seconds from 3 minutes and that cut down the test run time to 2 minutes. I'm not sure if there are any other tweaks that could be made too (maybe the `MANAGER_TABLET_GROUP_WATCHER_INTERVAL` to speed up the check but that's not a table config)

`MANAGER_TABLET_GROUP_WATCHER_INTERVAL` is set to `5s` in MiniAccumuloClusterImpl already. Setting `TABLE_SUSPEND_DURATION` to `30s` does not have the same effect for me. The test run time is still around 4m.

**Pull request merged**
