### PR TITLE
Fix #705 TableName from baseSplit is ignored, when getting inputTableConfig within AbstractInputFormat.initialize()

### LINKED ISSUE #705: NullPointerException when doing MapReduce job
Caused by: java.lang.NullPointerException
        at org.apache.accumulo.core.client.mapred.AbstractInputFormat$AbstractRecordReader.initialize(AbstractInputFormat.java:608) 
        at org.apache.accumulo.core.client.mapred.AccumuloRowInputFormat$1.initialize(AccumuloRowInputFormat.java:60)

### PR DESCRIPTION
**Pull request by deniskuzZ**
https://issues.apache.org/jira/browse/ACCUMULO-4857

### CODE REVIEW

**Comment by milleruntime** [comment]
tableConfig is used in many other places before getting the samplerConfig.  I am wondering why the tableConfig is null in the first place.  Could this be a race condition where the table hasn't been created yet?

**Comment by busbey** [comment]
I believe this is surfacing in Hive. Here's the stack trace from jira:

```
Caused by: java.lang.NullPointerException

 at org.apache.accumulo.core.client.mapred.AbstractInputFormat$AbstractRecordReader.initialize(AbstractInputFormat.java:637)

 at org.apache.accumulo.core.client.mapred.AccumuloRowInputFormat$1.initialize(AccumuloRowInputFormat.java:67)

 at org.apache.accumulo.core.client.mapred.AccumuloRowInputFormat.getRecordReader(AccumuloRowInputFormat.java:92)

 at org.apache.hadoop.hive.accumulo.mr.HiveAccumuloTableInputFormat.getRecordReader(HiveAccumuloTableInputFormat.java:224)

 at org.apache.hadoop.hive.ql.io.HiveInputFormat.getRecordReader(HiveInputFormat.java:295)
```

**Comment by busbey** [comment]
@deniskuzZ could you confirm if this was against a table that already existed in Accumulo?

**Comment by deniskuzZ** [comment]
@busbey Yes, table was already registered in Accumulo.

**Comment by deniskuzZ** [comment]
> tableConfig is used in many other places before getting the samplerConfig. I am wondering why the tableConfig is null in the first place. Could this be a race condition where the table hasn't been created yet?

btw, in version 1.7.3 it's also null, it's just not used inside initialize(), if statements return false

**Comment by milleruntime** [comment]
> btw, in version 1.7.3 tableConfig is also null

This tells me that the problem existed in 1.7 as well and that the changes in 1.8/1.9 are just exposing the issue.

It appears that the code getting the tableConfig is looking in the JobConf for a key that must be missing.  Here is how the tableConfig is pulled from the job configuration: https://github.com/apache/accumulo/blob/1.9/core/src/main/java/org/apache/accumulo/core/client/mapreduce/lib/impl/InputConfigurator.java#L679

**Comment by milleruntime** [comment]
The key which should be something like: "AccumuloInputFormat.InputConfigurator.ScanOpts.table_configs"

**Comment by deniskuzZ** [comment]
> The key which should be something like: "AccumuloInputFormat.InputConfigurator.ScanOpts.table_configs"

getDefaultInputTableConfig(implementingClass, conf) -> getInputTableName(implementingClass, conf)

public static String getInputTableName(Class<?> implementingClass, Configuration conf) {
    return conf.get(enumToConfKey(implementingClass, ScanOpts.TABLE_NAME));
}
this one becomes NULL, wasn't able to figure out yet why, but there is some conf object manipulations.

in my case key is AccumuloInputFormat.InputConfigurator.ScanOpts.accumulo_pushdown, where accumulo_pushdown is a table name

**Comment by ctubbsii** [comment]
@deniskuzZ : Just a quick note, the `ACCUMULO-XXXX` version numbering scheme applies to JIRA, not GitHub issues. To reference another issue on GitHub, just do `#XXXX`

**Comment by milleruntime** [comment]
Check to make sure AccumuloRowInputFormat.setInputTableName(JobConf, tableName) is called.  I suspect this is why the tableConfig is null.  That method we were looking at will fall back and call getDefaultInputTableConfig() which will just get the config using the tableName set in that static method.  Looking at our tests, it seems to do this for everything.  The 4 methods we require to be set are listed [here](https://github.com/apache/accumulo/blob/1.9/core/src/main/java/org/apache/accumulo/core/client/mapred/AccumuloRowInputFormat.java#L53).

**Comment by deniskuzZ** [comment]
> Check to make sure AccumuloRowInputFormat.setInputTableName(JobConf, tableName) is called. I suspect this is why the tableConfig is null. That method we were looking at will fall back and call getDefaultInputTableConfig() which will just get the config using the tableName set in that static method. Looking at our tests, it seems to do this for everything. The 4 methods we require to be set are listed [here](https://github.com/apache/accumulo/blob/1.9/core/src/main/java/org/apache/accumulo/core/client/mapred/AccumuloRowInputFormat.java#L53).

It's set: https://github.com/apache/hive/blob/3c70302a290442cfa12bfc389ad6fe8a7885e1c0/accumulo-handler/src/java/org/apache/hadoop/hive/accumulo/mr/HiveAccumuloTableInputFormat.java#L311
However it's getting lost in the middle (in mapred)

**Comment by milleruntime** [comment]
@deniskuzZ I see that configure method called in getSplits() but not getRecordReader().  There is also a comment about it being unnecessary since all the information should be in RangeInputSplit.  So all the information may be there but the tableName might not be set by the static method.

**Comment by deniskuzZ** [comment]
@milleruntime 
2nd parameter of getInputTableConfig(job, tableName), tableName = baseSplit.getTableName()
is ignored when fetching tableConfigs: getInputTableConfigs(implementingClass, conf)

getInputTableConfigs() calls getDefaultInputTableConfig() that requires "tableName". This table name is taken from JobConf, not from the baseSplit.

Shouldn't this be changed to baseSplit.getTableName() with fallback to JobConf?

**Comment by deniskuzZ** [comment]
@milleruntime, updated pull request

**Comment by deniskuzZ** [comment]
@milleruntime, build is is green (https://jenkins.revelc.net/job/Accumulo-PR/95/)

getDefaultInputTableConfig() is not a public API method and is called only from getInputTableConfigs()

overloaded getInputTableConfigs(implementingClass, conf, tableName) is only used in mapred(uce).AbstractInputFormat to get the input table configs.

> I see now, thanks @deniskuzZ. I think this is a valid change but I have a few concerns. I am worried that code previously written which calls getDefaultInputTableConfig() may expect to get the tableName from the JobConf and will break with this change. And since we follow SemVer, we can't change a method signature in the public API. This would require deprecating the old method and replacing it with a new one.
> 
> My other concern is that we are trying to clean up the Map Reduce code for 2.0.0-Alpha release (it is a mess right now if you didn't notice, with too much exposed to the public API) so we may be deprecating this code for something better.
> 
> In the meantime, I submitted a job to run all tests https://jenkins.revelc.net/job/Accumulo-PR/95/

@milleruntime, build is is green, all tests passed.

getDefaultInputTableConfig() is not a public API method and is called only from getInputTableConfigs()

overloaded getInputTableConfigs(implementingClass, conf, tableName) is only used in mapred(uce).AbstractInputFormat to get the input table configs.

**Comment by milleruntime** [comment]
> getDefaultInputTableConfig() is not a public API method

Sorry you are correct.  The class you modified is in an impl sub-package so no worries there.

The build looks good so I just need to figure out this MapReduce clean up for 2.0.  I hope to have something up within the next few days.

**Pull request closed without merging**
