### PR TITLE
Add new property tserver.max.scan.result.timeout

### PR DESCRIPTION
**Pull request by milleruntime**

### CODE REVIEW

**Comment by milleruntime** [comment]
Related to #2598 but may not be needed if there is a fix.

**Comment by dlmarion** [comment]
See comment at https://github.com/apache/accumulo/issues/2598#issuecomment-1082146876. I wonder if we should leave this as is and instead back-off on the client side when a timeout occurs.

**Review by dlmarion — APPROVED** [review]
I see no issue with making this configurable

**Comment by milleruntime** [comment]
> I wonder if we should leave this as is and instead back-off on the client side when a timeout occurs.

Are you working on this change? I think I can just merge this new option as is and if we want to make an improvements, they can be a follow on task. Seems like this timeout will still be there no matter what changes are made

**Comment by dlmarion** [comment]
> Are you working on this change? 

I am not.

> I think I can just merge this new option as is and if we want to make an improvements, they can be a follow on task. Seems like this timeout will still be there no matter what changes are made

Agreed

**Pull request merged**
