### PR TITLE
Improvements to TabletStateChangeIteratorIT

### PR DESCRIPTION
**Pull request by milleruntime**
* Modified copyTable method to gather info about the metadata first
before creating the copy, preventing information about the copy itself
from being seen.
* Added debugging information

### CODE REVIEW

**Comment by milleruntime** [comment]
These improvements seem to have fixed the issue in 2.1 as well so as soon as the checks pass I will go ahead and merge.

**Comment by DomGarguilo** [comment]
Another small improvement may be to pre-split the table in the createTable method. I'm not too sure what is going on with the online/offline of the table, however if it is found that the split does not need to occur after the table is created for this test, it has been found that pre-splitting the table leads to greater stability and efficiency.

The updated code could look something like this:
```java
private void createTable(String t, boolean online) throws AccumuloSecurityException, AccumuloException, TableNotFoundException, TableExistsException {
    Connector conn = getConnector();
    SortedSet<Text> partitionKeys = new TreeSet<>(Arrays.asList(new Text("some split"));
    NewTableConfiguration ntc = new NewTableConfiguration().withSplits(partitionKeys);
    conn.tableOperations().create(t, ntc);
    conn.tableOperations().online(t, true);
    if (!online) {
      conn.tableOperations().offline(t, true);
    }
  }
```

**Comment by milleruntime** [comment]
Thanks @DomGarguilo good idea.

**Review by EdColeman — APPROVED** [review]

**Comment by milleruntime** [comment]
> Another small improvement may be to pre-split the table in the createTable method. I'm not too sure what is going on with the online/offline of the table, however if it is found that the split does not need to occur after the table is created for this test, it has been found that pre-splitting the table leads to greater stability and efficiency.
> 
> The updated code could look something like this:
> 
> ```java
> private void createTable(String t, boolean online) throws AccumuloSecurityException, AccumuloException, TableNotFoundException, TableExistsException {
>     Connector conn = getConnector();
>     SortedSet<Text> partitionKeys = new TreeSet<>(Arrays.asList(new Text("some split"));
>     NewTableConfiguration ntc = new NewTableConfiguration().withSplits(partitionKeys);
>     conn.tableOperations().create(t, ntc);
>     conn.tableOperations().online(t, true);
>     if (!online) {
>       conn.tableOperations().offline(t, true);
>     }
>   }
> ```
> 
> Not sure if this is something worth including, just thought I would point it out though.

This won't work in 1.10. The ability to pre-split tables wasn't added until 2.0. Ugh! I forgot about how crappy our API used to be. Be glad that you aren't cursed with that knowledge :grin:

**Comment by DomGarguilo** [comment]
> This won't work in 1.10. 

Whoops. Maybe something to keep in mind if changes are made to the current version in that case.

**Pull request merged**
