### PR TITLE
Add Sunny Tag to more tests for elasticity branch

### PR DESCRIPTION
**Pull request by dlmarion**

### CODE REVIEW

**Comment by dlmarion** [comment]
FYI that I wanted to add the Sunny tag to `ServiceLockIT` as well, but I got some error about the `Tag` that didn't make sense to me.

**Comment by keith-turner** [comment]
Adding the test for bulk, merge, compaction, etc gives good high coverage of the major features of Accumulo.  The following test seem to exercise internal impl details of the high level features that would be partially exercised by the test that exercise the high level features.  

 * LocatorIT
 * ManagerAssignmentIT
 * TabletManagementIteratorIT
 * TabletManagementScannerIT
 * TabletResourceGroupBalanceIT
 

So thinking maybe these test should not be added.

**Review by keith-turner — APPROVED** [review]

**Review by ctubbsii — COMMENTED** [review]
Some of these tests seem like more than just quick smoke tests to make sure we haven't fundamentally broken some basic core functionality. I would not consider merges or all of the edge case scan server ITs to be basic core functionality, maybe not even bulk import. Yes, they are important, but they can be run when the full ITs run... or we can create a new category if needed. But, the purpose of the sunny tests are to *quickly* run checks, and adding a bunch more to them is going to make smoke testing contributions harder.

I would suggest rolling these out, and creating a new category for elasticity-related features, if there is a need for such a category. Maybe one or two of these could be added to sunny, but I don't think all of them should be.

**Comment by dlmarion** [comment]
@ctubbsii - @keith-turner and I talked about this and I think we both agreed that for now, for the elasticity branch, we are good with marking these as part of the sunny tests. These tests are being built periodically by a Jenkins server, it's not something that we are doing manually. All of the tests are not working yet on the elasticity branch and this gives us a good indication that the major features are working. We can revisit this when all of the ITs are working.

**Comment by keith-turner** [comment]
We also discussed #3826 that could be created in 2.1 or 3.1 and merged forward into elasticity.  In elasticity this new test could replace alot of the test that were tagged for sunny in this PR.   If #3826 is not done, then we #3825 to remind us to reevaluate what is tagged as sunny.

**Pull request merged**
