### PR TITLE
Improve InstanceOperations Doc

### PR DESCRIPTION
**Pull request by DomGarguilo**
~~Fixes 2244~~

~~These changes add a `setProperties` method to InstanceOperations. There are many places in the code that set multiple properties one after another each with its own call to `setProperty`. This change may make the code cleaner by allowing multiple properties to be set with a single call using a map of properties.~~

~~Not sure if this is a change we want to make, just thought I'd give it a shot. If this is merged, I'll create a follow on ticket to find and convert places in the code that may benefit from this.~~

Added improvements to InstanceOperations doc

### CODE REVIEW

**Review by EdColeman — COMMENTED** [review]
The doc changes look fine - the other changes likely will be superseded - in fact there is likely to be a preference setting multiple properties to cut down on round-trips to ZooKeeper.

**Comment by DomGarguilo** [comment]
> the other changes likely will be superseded

In that case, should I change this PR to only include the doc updates or keep everything?

**Review by ctubbsii — COMMENTED** [review]
I think adding this to the public API is premature at this point, since the implementation offers no benefit over the user looping themselves to set multiple properties. To make this useful, it would benefit from being an atomic set of multiple properties, and that depends on the work @EdColeman is doing on the ZooKeeper properties storage on the back end, and it will also depend on subsequent RPC changes, and some design considerations (like, do we want to have a properties mutator that adds/deletes/updates properties, rather than a fixed "set" method?)

I would hold off on this PR for now. We should reconsider when more progress is made on the back end with how we store ZK properties.

**Comment by ctubbsii** [comment]
> > the other changes likely will be superseded
> 
> In that case, should I change this PR to only include the doc updates or keep everything?

You can either change this PR to only include the doc updates, and we can hold off on the other changes until later... or you can submit a new PR with only the doc updates, and when that is merged, you can rebase this PR and mark it "WIP" for the rest of the stuff, until we're ready for it.

**Comment by DomGarguilo** [comment]
I went ahead and changed this PR to only include the doc improvements. Another PR can be made down the road if we choose to revisit #2244

**Review by Manno15 — APPROVED** [review]
The doc changes look good.

**Pull request merged**
