### PR TITLE
Refactor Shell ITs

### PR DESCRIPTION
**Pull request by milleruntime**
* Create ShellCreateTableIT from tests moved from ShellServerIT
* Create TestShell class
* Modify ShellServerIT to not delete tables after ever test
* Move ShellConfigIT into shell package
* Move ShellIT into shell package

### CODE REVIEW

**Comment by ctubbsii** [comment]
> * Create ShellCreateTableIT from tests moved from ShellServerIT

What's different about those tests that necessitated being separate?

> * Modify ShellServerIT to not delete tables after ever test

It's probably fine either way, but what motivated this change? Is this going to be a problem in resource-constrained environments, because all the tests are using the same Mini?

Did you just move tests around, or delete you delete any? I didn't get to do a thorough review, but I got the impression that a lot was deleted, and not necessary as much created.

**Comment by milleruntime** [comment]
These ITs are passing for me
<pre>
[INFO] Running org.apache.accumulo.test.shell.ShellCreateTableIT
[INFO] Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 60.733 s - in org.apache.accumulo.test.shell.ShellCreateTableIT
[INFO] Running org.apache.accumulo.test.shell.ShellConfigIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.201 s - in org.apache.accumulo.test.shell.ShellConfigIT
[INFO] Running org.apache.accumulo.test.shell.ShellServerIT
[INFO] Tests run: 58, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 186.816 s - in org.apache.accumulo.test.shell.ShellServerIT
[INFO] Running org.apache.accumulo.test.shell.ShellIT
[INFO] Tests run: 19, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 170.239 s - in org.apache.accumulo.test.shell.ShellIT
</pre>

**Comment by milleruntime** [comment]
> What's different about those tests that necessitated being separate?

They were similar, all creating tables and named testCreateTable*. 

> It's probably fine either way, but what motivated this change? Is this going to be a problem in resource-constrained environments, because all the tests are using the same Mini?

It shouldn't, I created a separate IT for the new one, instead of making it extend `ShellServerIT`

> Did you just move tests around, or delete you delete any? 

Yes. Only thing I deleted was the After test method that was deleting tables.

**Comment by milleruntime** [comment]
Compared to the times of the ITs running on machine from main:
<pre>
[INFO] Running org.apache.accumulo.test.ShellConfigIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.234 s - in org.apache.accumulo.test.ShellConfigIT
[INFO] Running org.apache.accumulo.test.ShellServerIT
[INFO] Tests run: 81, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 242.953 s - in org.apache.accumulo.test.ShellServerIT
[INFO] Running org.apache.accumulo.test.ShellIT
[INFO] Tests run: 19, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 169.329 s - in org.apache.accumulo.test.ShellIT
[INFO] Total time:  08:30 min
</pre>
The total time overall is the same. Hopefully these changes make it easier to debug individual tests. I had a hard time debugging one of the tests in ShellServerIT and it took a while to run the whole IT. For example, now they each get their own directory in mini. I would prefer lots of small tests that take less than a minute to run. Even with this change, ShellServerIT still have ~50 tests in it so I might split out another IT since that is a lot for one IT. One idea I had was to put all the tests that are testing a simple command in one and the rest (which do more complicated things) in another IT.

**Comment by milleruntime** [comment]
@ctubbsii are you familiar with the test `scansWithClassLoaderContext` in ShellServerIT ? This seems to be the only test that can't be run by itself in IntelliJ. It is checking if a class is already on the classpath but it will throw an exception if it is already. I was thinking this could just clean the class from the classpath if it detects it but wasn't sure how to do that.

**Comment by ctubbsii** [comment]
> @ctubbsii are you familiar with the test `scansWithClassLoaderContext` in ShellServerIT ? This seems to be the only test that can't be run by itself in IntelliJ. It is checking if a class is already on the classpath but it will throw an exception if it is already. I was thinking this could just clean the class from the classpath if it detects it but wasn't sure how to do that.

Sorry, not off the top of my head, I'm not familiar. I'd have to investigate.

**Review by ctubbsii — APPROVED** [review]
Overall, I think these changes are good, especially the part about moving the shell tests into a common package, and moving some of the utility classes, like the callback and the test shell into their own classes.

However, you may wish to rename `TestShell`, because it currently will get picked up as a test class for unit tests, as it matches the default naming patterns for `maven-surefire-plugin`. I don't think it contains any tests itself, so it won't actually be a problem, but it could be confusing that it looks like a class containing test cases and will be loaded by surefire to attempt to run tests in it.

Maybe, call it `FakeShell` or `MockShell` or `ShellEmulator` or similar?

https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#includes

Overall, it's good, though. Thanks for answering my previous questions.

**Comment by milleruntime** [comment]
> However, you may wish to rename TestShell, because it currently will get picked up as a test class for unit tests, as it matches the default naming patterns for maven-surefire-plugin.

Oh good catch. I will rename it.

**Review by Manno15 — APPROVED** [review]
Changes look good. Confirmed pass as expected.

**Pull request merged**
