### PR TITLE
Create Config page on Monitor

### PR DESCRIPTION
**Pull request by milleruntime**
* Displays non sensitive properties on the Monitor. Link is under REST

### CODE REVIEW

**Comment by DomGarguilo** [comment]
What is the use case for this?

**Comment by DomGarguilo** [comment]
> Can you supply a screenshot of the page?

Screenshot from 2022-04-07 12-42-44

Here is a screenshot of part of the page @Manno15. I don't think its meant to be human readable. I think its meant to serve as an endpoint where one can fetch the config in XML form.

**Comment by milleruntime** [comment]
Yeah it will show up here: http://localhost:9995/rest/config
It could be both human or machine readable. I just picked XML because my browser displays it more neatly than JSON.

**Comment by milleruntime** [comment]
For example:
`
<conf>
<property>compaction.coordinator.compaction.finalizer.check.interval=60s</property>
<property>compaction.coordinator.compaction.finalizer.threads.maximum=5</property>
<property>compaction.coordinator.compactor.dead.check.interval=5m</property>
<property>compaction.coordinator.message.size.max=10M</property>
<property>compaction.coordinator.port.client=9132</property>
<property>compaction.coordinator.port.search=false</property>
<property>compaction.coordinator.threadcheck.time=1s</property>
<property>compaction.coordinator.threads.minimum=1</property>
<property>compaction.coordinator.threads.timeout=0s</property>
<property>compaction.coordinator.tserver.check.interval=1m</property>
`

**Comment by milleruntime** [comment]
It also makes for easy copy and pasting.

**Comment by DomGarguilo** [comment]
When I visit the page, my browser doesn't display it so nicely (view my screenshot from earlier as an example). I only see the xml when I inspect or wget/curl the page. We could potentially add two pages, one used to fetch the data (JSON or XML) and another used to view it by a user which could be in the form of a table or something more readable than JSON or XML.

**Review by ctubbsii — COMMENTED** [review]
I'm not convinced this is a good idea. At best, it will show the configuration of the monitor itself. It won't show the configuration of tservers, which may have different properties configured, or of the manager or gc. It also intentionally doesn't show sensitive properties.

So, it only shows a partial view of one server's configuration, and misrepresents it as the monolithic configuration for the entire cluster.

That is not only misleading, but it also goes against some of the previous work done to migrate to commons-configuration2 to support more modular configuration management at the service level. There isn't a "one global configuration" (there never has been, but now users have even more options with commons-configuration2 to manage their configuration in a modular way per server instance).

**Comment by ctubbsii** [comment]
> When I visit the page, my browser doesn't display it so nicely (view my screenshot from earlier as an example). I only see the xml when I inspect or wget/curl the page. We could potentially add two pages, one used to fetch the data (JSON or XML) and another used to view it by a user which could be in the form of a table or something more readable than JSON or XML.

You can use `jq` to format the output: `curl <url> | jq .`; stuff like this doesn't generally need to be human-readable.

**Comment by milleruntime** [comment]
> I'm not convinced this is a good idea. At best, it will show the configuration of the monitor itself. It won't show the configuration of tservers, which may have different properties configured, or of the manager or gc. It also intentionally doesn't show sensitive properties.
> 
> So, it only shows a partial view of one server's configuration, and misrepresents it as the monolithic configuration for the entire cluster.
> 
> That is not only misleading, but it also goes against some of the previous work done to migrate to commons-configuration2 to support more modular configuration management at the service level. There isn't a "one global configuration" (there never has been, but now users have even more options with commons-configuration2 to manage their configuration in a modular way per server instance).

I pulled the code from `ConfigCommand` so we can easily do anything we are doing there. And we could display config by different servers and have the server name as a node in the output.

**Comment by ctubbsii** [comment]
> I pulled the code from `ConfigCommand` so we can easily do anything we are doing there. And we could display config by different servers and have the server name as a node in the output.

The ConfigCommand has some of the same issues (as does the public API it calls). But, at the very least, you can't view any configuration in the shell unless you've done *some* kind of authentication. That's not true of this change to the monitor. This just provides it without any kind of authentication.

To partially address the misleading information problem, you could display the config for each server, but that would be a bit of information overload. Or you could just display the one, but with "as reported by serverX". However, either way, you'd have to either modify the public API, or bypass it to get the server information and talk directly via Thrift. I don't think that extra code is worth it when the benefits are marginal. And, ultimately, I don't think it would better than an authorized sysadmin securely grabbing a copy of the config files from each server's class path and dumping the ZK config to get the authoritative information, that they can already do today.

Overall, though, I don't think the monitor's scope should grow to be a tool for configuration management, even if it is just used to report configuration. I'm also deeply uncomfortable exposing all this through the monitor without authentication. I think users have much more reliable and secure means for viewing the configuration they've deployed to their own servers than anything we'd add insecurely to the monitor.

**Comment by milleruntime** [comment]
> The ConfigCommand has some of the same issues (as does the public API it calls).

What kind of issues?

**Pull request closed without merging**
