### PR TITLE
Adding ChangeSecret utility to the accumulo admin command

### PR DESCRIPTION
**Pull request by cshannon**
Issue #2807

### CODE REVIEW

**Review by Manno15 — APPROVED** [review]
Changes look good and I confirmed the command works as intended. My only question is if we intend to keep the use of SiteConfiguration or not (see issue #2155).

**Comment by ctubbsii** [comment]
> Changes look good and I confirmed the command works as intended. My only question is if we intend to keep the use of SiteConfiguration or not (see issue #2155).

It is fine to use SiteConfiguration. The Admin command is a server-side utility only, requires the server base jar. The shell is a client side utility and should not depend on the server jars for its class path. That's the difference.

I haven't looked at the rest of the PR, but wanted to address that comment to clarify.

**Review by milleruntime — COMMENTED** [review]
I made a comment on the other PR but it also applies to this one as well... if we are moving each of these one-off utilities into the Admin command, they shouldn't need main methods anymore. This would be nice to simplify the code and turn them into POJOs. I guess this could break existing scripts that call the classes directly but I would be OK with that. We will just have to list all the utilities in the release notes and mention the new equivalent command. Also, now that Admin has a bunch of commands, it would be nice to have them alphabetized in Help.

**Comment by cshannon** [comment]
That's fine i can drop the main methods, I wasn't sure if we still wanted the option to run them directly so I left them in there initially. Re-ordering the help is a good catch too.

**Comment by cshannon** [comment]
@milleruntime - How about we just go ahead and merge the utilities as they are and keep the main methods and then in a separate PR we remove the main or deprecate them from all the utilities? I think that makes more sense as a follow on.

For alphabetizing the help I figure once we merge all of these utilities I can re-arrange them in one of the PR we merge or a new PR just so all the commands are there so we can re-order all at once and prevent conflicts if that sounds good to you.

**Comment by milleruntime** [comment]
> @milleruntime - How about we just go ahead and merge the utilities as they are and keep the main methods and then in a separate PR we remove the main or deprecate them from all the utilities? I think that makes more sense as a follow on.
> 
> For alphabetizing the help I figure once we merge all of these utilities I can re-arrange them in one of the PR we merge or a new PR just so all the commands are there so we can re-order all at once and prevent conflicts if that sounds good to you.

That works. Then you can resolve conflicts and just make one PR for all the improvements.

**Review by milleruntime — APPROVED** [review]

**Pull request merged**
