### PR TITLE
Add text icon to monitor navbar to indicate manager state

### PR DESCRIPTION
**Pull request by DomGarguilo**
Alternative approach to #3711. The difference here is the icon added is simply a unicode character that is displayed over the existing dot icon when the manager state is not normal. With this approach, the changes are a lot more minimal compared to #3711 which had to introduce an svg and change the code to accomodate.

Here are some screenshots with these changes:

Screenshot from 2023-08-24 11-47-26

Screenshot from 2023-08-24 11-48-04

Manager in `SAFE_MODE` state
Screenshot from 2023-08-24 11-50-13

Manager in `CLEAN_STOP` state
Screenshot from 2023-08-24 11-51-55

Screenshot from 2023-08-24 12-01-47

It is very easy to change which icon is displayed. Here are some alternative icons that have been suggested:
Screenshot from 2023-08-24 12-03-29

Screenshot from 2023-08-24 12-04-22

Any other suggestions for which icons to try out are welcome.

### CODE REVIEW

**Comment by ivakegg** [comment]
I like the triangle with the exclamation mark the best.

**Comment by ivakegg** [comment]
SO.... the whole point of the original ticket is to see that the system is being shutdown.  I see that the Manager shows as being green when this is the case.  Hence this whole icon thing is actually not going to do me any good.  Also to reiterate we almost always have some tserver down, that that will alway be yellow for us.  This is another reason that this icon may not actually be helping us.

**Comment by ivakegg** [comment]
> 

I see that the icon is an indication of the master state, and the color is a combination of the states.  So I guess this actually works.  I still want text but I will have to add that in our fork.

**Review by ivakegg — APPROVED** [review]

**Comment by ctubbsii** [comment]
> > 
> 
> I see that the icon is an indication of the master state, and the color is a combination of the states. So I guess this actually works. I still want text but I will have to add that in our fork.

I don't think you need to maintain a text solution in your fork. There's a good chance that if you find a particular set of information useful to display, others will too. I think we can come to consensus on a general solution with a little more work. I proposed some more ideas on #3688. I think what you're asking for is a little different than server statuses... I think maybe it'd be useful to tease apart the concept of server statuses (the color dot icon), and have a separate alert icon for system messages. On #3688, I proposed a separate icon in the nav bar to show that there is a system message, and opens a modal window with the system message when clicked. System messages could be "Manager reported that it is in safe mode", or "There are no (managers|gc|tservers) running", or "System is shutting down", etc. If we keep these separate from the server statuses, I think it might achieve what you're looking for.

**Review by ctubbsii — COMMENTED** [review]
I like this solution, as it's pretty simple and easy to understand.

Color = status

Icon = abnormal manager condition


But, based on the discussion, it might still not be the best solution just yet, but I think it's much closer.

**Comment by EdColeman** [comment]
What if GOAL_STATE was treated as a process?  The pull-down could look like 

- GOAL_STATE (Green - Normal. Yellow - SAFE_MODE, Red SHUTDOWN)
- Manager(s) (Green expected running, Yellow - on or more expected not available, Red, all down)
- TSERVERS (Green is n > x% available, Yellow if y < n < x, available, Red n < y. 
- GC (Green normal, Yellow slow, Red not run since ?)

The roll-up goal would be to show - GOAL_STATE or if something needed attention.

**Comment by ctubbsii** [comment]
> What if GOAL_STATE was treated as a process? The pull-down could look like
> 
> * GOAL_STATE (Green - Normal. Yellow - SAFE_MODE, Red SHUTDOWN)
> * Manager(s) (Green expected running, Yellow - on or more expected not available, Red, all down)
> * TSERVERS (Green is n > x% available, Yellow if y < n < x, available, Red n < y.
> * GC (Green normal, Yellow slow, Red not run since ?)
> 
> The roll-up goal would be to show - GOAL_STATE or if something needed attention.

It basically already works like that, except the goal state. The goal state is not really a "server" status, though, so I think maybe it's useful to not conflate it with the status codes in the "Servers" menu in the nav bar. I think it'd be better to treat it as its own visual element, which is why I was suggesting having a separate "System messages" element.

This gets a bit complicated, though, because "Safe mode" and "Shutting down" are really handled by the Manager, even though they are system-wide goal states.

One other option is that the Manager just turns orange with safe mode, and red with shutting down. That will be visually distinct enough from the normal yellow because a few tservers are offline. But, it still won't satisfy Ivan's desire to have text prominently displayed.

**Comment by ivakegg** [comment]
LGTM.  I can write up a separate ticket for the text in the navbar

**Review by Manno15 — APPROVED** [review]

**Comment by ctubbsii** [comment]
> But, based on the discussion, it might still not be the best solution just yet, but I think it's much closer.

My previous comment on the current iteration was "But, based on the discussion, it might still not be the best solution just yet, but I think it's much closer."

@ivakegg's latest comment about opening up another ticket seems to indicate the same. This ticket was supposed to be the one that made text in the nav bar unnecessary (because of limited real estate there) by adding an icon instead. If this ticket isn't quite right, then there's no point in merging it and opening another one... let's just reiterate and consider a different idea.

Here's the considerations:

1. Desire to see indication of certain states (safe mode, offline) on every page of monitor
2. Some states are important enough to require immediate disambiguation, without needing to expand a menu (specifically, the manager being in safe mode should be visually distinguishable from the a couple tservers being offline)
3. Limited space in nav bar

I believe this PR, as is, addresses all three of these. However, @ivakegg seems to indicate that icon-only disambiguation in consideration number 2 is insufficient, and prefers to see text. However, I'm concerned that the nav bar is too space constrained to place additional text.

Here's some ideas for a subsequent iteration on this, given the lack of consensus:

1. If @ivakegg is willing to flex on the need for text, perhaps there's a way we can add a secondary icon:
  a. We could add a new icon (like an alert) to indicate the presence of "system messages". This icon will not normally be present, and could never be confused for another state, but would take up minimal space. Clicking on it could bring up a modal alert window with a description of the system message.
  b. We could add a new icon that is not mixed in with the server state, but indicates one very specific system message: that manager is in safe mode. If we have additional system conditions we want to alert on, we can add new, distinct icons. This idea is similar to 1.a, but instead of having one global alert icon for the presence of any system message, each system message would get its own unique icon. I'm not a fan of this option as much, because of the need to maintain a legend to track all the different icon meanings.
2. If we must have text, then I think putting it in the body of the main page layout, rather than the nav bar, so it shows up on each page, would be a reasonable idea *only* if it were not presented as "manager state", but specifically as a generic "system message" alert on the main page. If it were just the manager state, it's very strange to report the manager state on the tserver page, for example. But it would make more sense for the tserver page (and other pages) to show a global system message, that just happened to come from the manager. We could have a few different system messages that could do this. But, we need to take care we don't confuse the user by saying something like "Accumulo is in safe mode". Instead, we should say something like "A manager server has sent a system message that it has entered safe mode". We don't need to be that verbose, of course, but I do think it's important we're that unambiguous, since safe mode is not a global system state, but a manager-specific one.
2

**Comment by DomGarguilo** [comment]
@ctubbsii, thanks for the detailed explanation here. I won't merge this in until we find a good solution.

After reading your suggestions/ideas it seems like the idea of adding an alert in the body of the main template page could work. For example, currently there is an alert banner on the manager page that might be something close to what we are looking for where it will appear whenever there is a message that should be displayed on all pages:

Manager page showing safe mode banner

We would change the message of the banner to something closer to what is mentioned about signifying a system-wide message.

If this sounds like a good idea I am wondering if it would also be a good idea to keep the current changes in this branch where the unique icon gets displayed in addition to adding a new banner with text outlining what the message is. That way if a user is scrolled down slightly or for some reason does not see the banner at the top of a page, there is another indication present in the navbar icons. Just an idea though not sure if we would want both an icon and a banner.

**Comment by ctubbsii** [comment]
So, after speaking with @DomGarguilo , I want to break down the next steps we discussed:

1. Create an icon that is normally not present, but appears as a distinct alert, whenever a system-wide alert is active. This icon would be placed on the top bar, but not part of the server status menu. It'd be it's own icon and would not collapse into the navigation if the display width is small.
    * Unknowns for this are: placement of icon, style of icon, which specific things will result in an alert (aside from a manger being in safe mode)
2. Create one of the following in which to place the details of the system-wide alert:
    1. A [modal window](https://getbootstrap.com/docs/5.3/components/modal/#toggle-between-modals) that pops up when clicking on the icon in step 1, or
    2. An [alert box](https://getbootstrap.com/docs/5.3/components/alerts/#icons) in the page that is always present.

I'm leaning towards the alert box always present, just because it's the simplest, and allows us to wrap this up quickest.

A few other considerations:

I think the icon shown in the alert box should match the icon in the top bar, to visually link them, just like a footnote marker or asterisk would link to a footnote.

I also think the description needs to indicate where it's coming from. This is different from the "safe mode" alert on the manager page, because that is clear it's referring to the manager itself. Since these would be shown on all pages, more details are needed. For example, instead of just saying "safe mode", it might say "Manager at \<hostname\> is in safe mode". (Note: we could probably get rid of the redundant alert on the manager page, if it's going to be shown on all pages anyway).

I thought we might want to make the alert dismiss-able, but I think that's too complicated. Just leaving it ever-present so long as the situation that caused the alert is still in effect, is fine.

**Comment by ivakegg** [comment]
Yes, some sort of banner or alert box that is present on all pages is what I am looking for.

**Comment by DomGarguilo** [comment]
Closing as superseded by #3770

**Pull request closed without merging**
