### PR TITLE
Move ZooKeeperTestingServer

### PR DESCRIPTION
**Pull request by milleruntime**
* ZooKeeperTestingServer is only used by the tests in fate.zookeeper pkg

### CODE REVIEW

**Comment by milleruntime** [comment]
OK no problem. This can definitely wait.

**Comment by milleruntime** [comment]
> I use it elsewhere - and it has utility outside of just fate testing if other wise to use it in improving testing beyond just using mocks.

I agree. This can definitely wait until after merging your ZK changes. If you have tests that use it, then it would make sense to keep it or move it up a package.

**Review by ctubbsii — CHANGES_REQUESTED** [review]
I agree that this shouldn't be moved. The name "fate" in all the ZooKeeper-related package names is misleading. Some of the tests are FaTE-related, but not all of them. This is a ZooKeeper test utility, not exclusive to FaTE.

**Comment by milleruntime** [comment]
OK. I just thought it wasn't worth having a package just for this one class.

**Comment by ctubbsii** [comment]
> OK. I just thought it wasn't worth having a package just for this one class.

I think there's a strong possibility that we could put more tests in this package later, for non-FaTE related ZK things. Packages are free, though, so I don't think it's a big deal. We can use as many as we want. (One class per package!!!! haha, just kidding).

**Pull request closed without merging**
