### PR TITLE
fixes #3045 remove stale compactions from coordinator

### LINKED ISSUE #3045: External Compaction stuck
In testing 2.1.0-RC1, I found that an external compaction became "stuck". 

From the tserver log:
```
2022-10-25T14:57:33,815 [tablet.files] DEBUG: Compacting 1;1f5c28f5c28f5c58;1eb851eb851eb88 on e.q1 for SYSTEM from [C0000zjn.rf, C0001hht.rf, F0001hjq.rf, F0001hk2.rf, C000188q.rf, C0001hjd.rf, C0001c2z.rf, F0001hkd.rf, C0001eis.rf] size 497 MB
2022-10-25T14:57:33,815 [compactions.CompactionManager] DEBUG: Reserved external compaction ECID:b6c0707e-d39b-4be8-a3d2-8a12485061d5
2022-10-25T14:57:34,923 [compactions.CompactionManager] DEBUG: Attempting to reserve external compaction, queue:q1 priority:-32749 compactor:X.Y.Z.Z:9133
```

From the compactor log:
```
2022-10-25T14:57:33,816 [compactor.Compactor] DEBUG: Received next compaction job: TExternalCompactionJob(externalCompactionId:ECID:b6c0707e-d39b-4be8-a3d2-8a12485061d5, extent:TKeyExtent(table:31, endRow:31 66 35 63 32 38 66 35 63 32 38 66 35 63 35 38, prevEndRow:31 65 62 38 35 31 65 62 38 35 31 65 62 38 38),...
2022-10-25T14:57:33,816 [compactor.Compactor] INFO : Starting up compaction runnable for job: TExternalCompactionJob(externalCompactionId:ECID:b6c0707e-d39b-4be8-a3d2-8a12485061d5, extent:TKeyExtent(table:31, endRow:31 66 35 63 32 38 66 35 63 32 38 66 35 63 35 38, prevEndRow:31 65 62 38 35 31 65 62 38 35 31 65 62 38 38)...
```
and **then the compactor was killed by the agitator at 14:58**.

From the coordinator log:
```
2022-10-25T14:57:33,816 [coordinator.CompactionCoordinator] DEBUG: Returning external job ECID:b6c0707e-d39b-4be8-a3d2-8a12485061d5 to X.Y.Z.Z:9133
2022-10-25T14:57:33,817 [coordinator.CompactionCoordinator] DEBUG: Compaction status update, id: ECID:b6c0707e-d39b-4be8-a3d2-8a12485061d5, timestamp: 1666709853817, update: TCompactionStatusUpdate(state:STARTED, message:Compaction started, entriesToBeCompacted:-1, entriesRead:-1, entriesWritten:-1)
2022-10-25T15:00:35,363 [coordinator.DeadCompactionDetector] DEBUG: Possible dead compaction detected ECID:b6c0707e-d39b-4be8-a3d2-8a12485061d5 1;1f5c28f5c28f5c58;1eb851eb851eb88
2022-10-25T15:05:35,380 [coordinator.DeadCompactionDetector] DEBUG: Possible dead compaction detected ECID:b6c0707e-d39b-4be8-a3d2-8a12485061d5 1;1f5c28f5c28f5c58;1eb851eb851eb88
```

The message 'Possible dead compaction detected...` is emitted [here](https://github.com/apache/accumulo/blob/main/server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/DeadCompactionDetector.java#L120) and then the compaction is killed [here](https://github.com/apache/accumulo/blob/main/server/compaction-coordinator/src/main/java/org/apache/accumulo/coordinator/DeadCompactionDetector.java#L134) if it happens more than twice. But it doesn't for some reason.

### PR DESCRIPTION
**Pull request by keith-turner**
I added a unit test and I ran all ITs that matched the pattern `*Compaction*IT` but have not tested the scenario in #3045 with these changes.  The unit test shows it working in isolation, but not end to end.

### CODE REVIEW

**Review by dlmarion — COMMENTED** [review]
Looks good, but I wonder if we should put the cleanup in a background thread instead of on the request thread that the Monitor uses to get the data. I'm not sure that this is super-important, as I think the orphaned RUNNING entries happen in a small number of cases. But, if the Monitor is down or never used by the user, then no cleanup will happen.

**Comment by ctubbsii** [comment]
Test seems to fail on JDK 17. Not sure what's going on with that.

**Comment by keith-turner** [comment]
> Looks good, but I wonder if we should put the cleanup in a background thread instead of on the request thread that the Monitor uses to get the data. I'm not sure that this is super-important, as I think the orphaned RUNNING entries happen in a small number of cases. But, if the Monitor is down or never used by the user, then no cleanup will happen.

When I first started looking into this I was considering adding this code to the DeadCompactionDetector because it already scans the metadata table and runs periodically in the background.  I decided against this because I thought it may make the code harder to understand and would force these two task to run at the same cadence.  I think I will take another look at making it run in the background as a task or as part of the dead compaction detector.

> Test seems to fail on JDK 17. Not sure what's going on with that.

I saw that, going to look into it.  Seemed to be failing to initialize the class, wonder if thats because I called System.nanoTime to initialize an instance var and maybe JDK 17 does not like that.

**Comment by keith-turner** [comment]
> Test seems to fail on JDK 17. Not sure what's going on with that.

I was able to reproduce this locally and fix it locally in commit  [7249313](https://github.com/apache/accumulo/pull/3059/commits/7249313ceecc4c6815654336bb6a7ec68630b838).  Was a problem with powermock, reflection, and java modules.  Needed to add java.time which contained the Duration class that powermock was trying to modify.

**Comment by keith-turner** [comment]
>  But, if the Monitor is down or never used by the user, then no cleanup will happen.

@dlmarion I modified the code to run periodically in the background.  This could avoid an OOME in a long running coordinator process for that case you mentioned.

**Review by dlmarion — APPROVED** [review]

**Pull request merged**
