### PR TITLE
Fix Fate operation name

### PR DESCRIPTION
**Pull request by milleruntime**
See comments #2842

### CODE REVIEW

**Comment by milleruntime** [comment]
Another option for the enum name could be "REPO_NAME", which I think is too vague or "RUNNING_REPO_NAME".

**Comment by milleruntime** [comment]
I think we are both confused :grin:. OK I figured it out...

The weird debug REPO is just the first REPO in the transaction. The only time it ever gets set is during `seedTransaction()`. So sometimes it makes sense as "target" like you were thinking but other times it doesn't. For example, the legacy Bulk import it will be `BulkImport` from bulkVer1 package but for the new bulk import it gets set to `PrepBulkImport`. For a compaction, it will be `CompactRange`. For create table it will be `CreateTable`.

You were correct that the `top` is actually the current running REPO.

I guess the name should be something like `INITIAL_REPO` or we can just remove it since its caused so much confusion. The only value I think it has is to see if its the same as the running repo to try and gauge progress. But an admin really doesn't know the REPOs of the TX without looking at the code. Since there is usually only 1 REPO that will hang during a problematic TX, this doesn't really help. 

We should be passing in the name of the FateOperation ENUM since that is the name of the TX.

**Comment by EdColeman** [comment]
It is helpful to admin to know both the intent and the current step.  Even with delete table, there are stages that can take awhile - just showing a delete operation is less helpful than showing its a delete, currently running clean-up.  While it would be nice to have the intent clearer, its is better to have something.  If it only reflected the running REPO - say clean-up, that could be a delete, an import,...

**Comment by milleruntime** [comment]
Sunny ITs are passing.

**Comment by milleruntime** [comment]
In my latest change, I passed in a string for the TX_NAME. This works better than using the strong type FateOperation because the shutdown tserver tx doesn't use the FateOperation enum.

**Comment by milleruntime** [comment]
This fix is good to go now. I like the new name. Here is what `fate -print` will display now:
<pre>
TABLE_COMPACT   txid: 754ab57de33ea843  status: IN_PROGRESS        locked: [R:+default, R:1] locking: []              op: CompactionDriver created: 2022-08-31T17:01:55.523Z
</pre>

**Comment by EdColeman** [comment]
Can you try fate -summary?

**Review by dlmarion — COMMENTED** [review]
LGTM

**Comment by milleruntime** [comment]
> Can you try fate -summary?

<pre>
Report Time: 2022-08-31T19:44:00Z
Status counts:
  IN_PROGRESS: 1

Command counts:
  TABLE_COMPACT: 1

Step counts:
  CompactionDriver: 1

Fate transactions (oldest first):
Status Filters: [NONE]

Running	txn_id				Status		Command		Step (top)		locks held:(table id, name)	locks waiting:(table id, name)
0:00:09	3f94c44c38546f76	IN_PROGRESS	TABLE_COMPACT	CompactionDriver	held:[R:(+default,ns:), R:(1,t:ci)]	waiting:[]
</pre>

**Review by EdColeman — APPROVED** [review]

**Pull request merged**
