### PR TITLE
fixes ACCUMULO-4634 : Appropriately implement the mocked out methods …

### PR DESCRIPTION
**Pull request by ivakegg**
…per the interface specifications.

### CODE REVIEW

**Comment by joshelser** [comment]
LGTM -- nice to see the semantics clear on IteratorEnvironment.

Any interest in adding a unit test?

**Comment by ivakegg** [comment]
I will see what I can do to force the MockAccumulo through that path.....

**Comment by joshelser** [comment]
bq. I will see what I can do to force the MockAccumulo through that path

Oh, I don't think you need to do anything so high-level. Just instantiate the MockIteratorEnvironment and add test methods that verify what each of those methods you modified does :)

**Comment by ivakegg** [comment]
tests added

**Comment by joshelser** [comment]
Thanks for the revisions, @ivakegg! Will try to commit later today.

**Comment by joshelser** [comment]
> Will try to commit later today.

I am also expanding the `*` import and squashing the commits together.

**Pull request closed without merging**
