### PR TITLE
Deprecate Master and replace with Manager in public API

### LINKED ISSUE #1643: Rename master references in public API
Once a new name is selected, we'll need to rename master references in the public API. Per [semver](https://semver.org/), the existing references will need to be deprecated for at least a release, and then the deprecated methods can be removed in a major release. Identify all public API references to master. At least the following exist:

- [Instance.getMasterLocations](https://github.com/apache/accumulo/blob/master/core/src/main/java/org/apache/accumulo/core/client/Instance.java#L48)
- [ZooKeeperInstance.getMasterLocations](https://github.com/apache/accumulo/blob/master/core/src/main/java/org/apache/accumulo/core/client/ZooKeeperInstance.java#L137)

### PR DESCRIPTION
**Pull request by jkosh44**
Fixes #1643

### CODE REVIEW

**Review by ctubbsii — CHANGES_REQUESTED** [review]
Looks great overall.

Please add `@SuppressWarnings("removal")` on the methods causing compiler warnings because of the use of the `MASTER` enum.

**Comment by jkosh44** [comment]
> Looks great overall.
> 
> Please add `@SuppressWarnings("removal")` on the methods causing compiler warnings because of the use of the `MASTER` enum.

Pretty sure I got all of them.

**Comment by jkosh44** [comment]
Looks like the failed check is from a connection timeout download hadoop jars from maven. Can we re-run it?

**Review by ctubbsii — APPROVED** [review]

**Comment by ctubbsii** [comment]
@jkosh44 It occurred to me after I merged that it probably wasn't necessary to modify `Instance`, since that is already deprecated and ready to be removed in 3.0.0... the same time these newly deprecated methods would be removed. So, the deprecation cycle for `Instance` was already on track. I will do a partial revert of those changes, so as to limit the introduction of a new API in 2.1.0 in an already deprecated class, that can be removed in 3.0.0.

**Comment by ctubbsii** [comment]
@jkosh44 Please see #1704. I wouldn't mind having your review on that, if you have a chance to look, since it rolls back the changes you made (and I merged) here to `Instance`.

**Comment by jkosh44** [comment]
@ctubbsii so sorry that I never responded to the comments, my github notifications have been messed up and I never saw these. For what it's worth the changes look fine to me.

**Pull request merged**
