### PR TITLE
Convert table.js to DataTables

### PR DESCRIPTION
**Pull request by DomGarguilo**
This PR converts the table in table.js to a DataTable.

The table should behave the same except for one small change:

Current table:
Screenshot from 2022-06-08 15-06-11

Table with the changes from this PR:
Screenshot from 2022-06-09 15-53-55

I broke the scans and compactions columns up into running and queued instead of having the queued compactions in the same column within the parenthesis.

### CODE REVIEW

**Comment by milleruntime** [comment]
> I broke the scans and compactions columns up into running and queued instead of having the queued compactions in the same column within the parenthesis.

That does look easier to read but I am worried how wide it makes the table. What was the reasoning for breaking them out into new columns? Maybe we could put the scan and compaction numbers in a separate table?

**Comment by DomGarguilo** [comment]
> That does look easier to read but I am worried how wide it makes the table. 

It makes the table only slightly wider and the table is still able to shrink to fit the window like before:
image


> What was the reasoning for breaking them out into new columns? Maybe we could put the scan and compaction numbers in a separate table?

It seemed more intuitive to have them in separate, labeled columns since there is nothing that says what the two numbers in the single columns mean.

> Maybe we could put the scan and compaction numbers in a separate table?

That seems like it could be a good option. Do you think we should do that?

**Comment by milleruntime** [comment]
> there is nothing that says what the two numbers in the single columns mean.

The tooltip hover should say what the parenthesis represent.

**Comment by milleruntime** [comment]
> > Maybe we could put the scan and compaction numbers in a separate table?
> 
> That seems like it could be a good option. Do you think we should do that?

I am not sure. I personally, thought the 2 numbers in one column were fine.

**Comment by DomGarguilo** [comment]
> > there is nothing that says what the two numbers in the single columns mean.
> 
> The tooltip hover should say what the parenthesis represent.

Whoops, I forgot about those. I'll go ahead and put it back to how it was since there is a description for the parenthesis.

**Comment by DomGarguilo** [comment]
Here is a screenshot of the tables page on the current commit: 
image

**Review by Manno15 — APPROVED** [review]

**Review by milleruntime — APPROVED** [review]

**Pull request merged**
