### PR TITLE
Examine WALs used by root tablet during GC

### PR DESCRIPTION
**Pull request by keith-turner**

### CODE REVIEW

**Comment by keith-turner** [comment]
I noticed this while working on #936.  It seems the GC of walogs does not look at what walogs the root tablet may be using.  In many cases if the root tablet has walogs it likely that the metadata table can not be read and GC would block.  However this is not always the case as the location of the metadata table may be cached and metadata tablets may still be online.

**Comment by ctubbsii** [comment]
Did #936 address this in the 2.1 branch already?

**Comment by keith-turner** [comment]
> Did #936 address this in the 2.1 branch already?

No it did not.  That change was concerning tablet files.  This changes is related to WALs.  In the GC files and WALs are two separate pieces of code.

**Comment by ctubbsii** [comment]
> > Did #936 address this in the 2.1 branch already?
> 
> No it did not. That change was concerning tablet files. This changes is related to WALs. In the GC files and WALs are two separate pieces of code.

It sounds like this got fixed in 2.1.0 by means of merging this PR, and not by the other issue. I'll mark this issue as "Done" for 2.1.0 accordingly.

**Pull request merged**
