### PR TITLE
Use internal RFile scan code for RecoveryLogsIterator

### LINKED ISSUE #2979: Metadata Table recovery failure
**Describe the bug**
Ran cingest on a 2.1.0-SNAPSHOT cluster with per-table crypto configured. Specifically, the following properties are set in `accumulo.properties`:
```
instance.crypto.opts.factory=org.apache.accumulo.core.spi.crypto.PerTableCryptoServiceFactory
general.custom.crypto.recovery.service=org.apache.accumulo.core.spi.crypto.AESCryptoService
general.custom.crypto.wal.service=org.apache.accumulo.core.spi.crypto.AESCryptoService
general.custom.crypto.key.uri=file:///opt/accumulo-testing/accumulo/accumulo-2.1.0-SNAPSHOT/conf/per-table-enc-key
```
and the `ci` table had the property `table.crypto.opts.service=org.apache.accumulo.core.spi.crypto.AESCryptoService`. I loaded the table with a bunch of data, then I deleted it via the shell. The `deletetable` command never returned and it appears that one of the metadata tablets was re-assigned during the delete operation. When trying to load the metadata tablet, the tserver logged the following error:

```
2022-09-28T16:50:44,468 [log.RecoveryLogsIterator] DEBUG: Opening recovery log dir 11946b4a-99b6-4b7e-b0d4-ccc1f981783a
2022-09-28T16:50:44,469 [crypto.CryptoFactoryLoader] DEBUG: Creating new crypto factory class org.apache.accumulo.core.spi.crypto.GenericCryptoServiceFactory
2022-09-28T16:50:44,472 [tserver.AssignmentHandler] WARN : exception trying to assign tablet !0<;~ null
java.lang.RuntimeException: Error recovering tablet !0<;~ from log files
        at org.apache.accumulo.tserver.tablet.Tablet.<init>(Tablet.java:379) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.AssignmentHandler.run(AssignmentHandler.java:165) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.ActiveAssignmentRunnable.run(ActiveAssignmentRunnable.java:63) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.io.IOException: java.io.UncheckedIOException: java.io.IOException: incorrect header check
        at org.apache.accumulo.tserver.log.TabletServerLogger.recover(TabletServerLogger.java:544) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.TabletServer.recover(TabletServer.java:1204) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.tablet.Tablet.<init>(Tablet.java:334) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        ... 7 more
Caused by: java.io.UncheckedIOException: java.io.IOException: incorrect header check
        at org.apache.accumulo.core.file.blockfile.impl.CachableBlockFile$Reader$BCFileLoader.load(CachableBlockFile.java:223) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.client.rfile.RFileScanner$NoopCache.getBlock(RFileScanner.java:165) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.client.rfile.RFileScanner$NoopCache.getBlock(RFileScanner.java:158) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.file.blockfile.impl.CachableBlockFile$Reader.getMetaBlock(CachableBlockFile.java:376) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.file.rfile.RFile$Reader.<init>(RFile.java:1164) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.file.rfile.RFile$Reader.<init>(RFile.java:1256) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.core.client.rfile.RFileScanner.iterator(RFileScanner.java:354) ~[accumulo-core-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.log.RecoveryLogsIterator.validateFirstKey(RecoveryLogsIterator.java:156) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.log.RecoveryLogsIterator.<init>(RecoveryLogsIterator.java:77) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.log.SortedLogRecovery.findMaxTabletId(SortedLogRecovery.java:107) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.log.SortedLogRecovery.findLogsThatDefineTablet(SortedLogRecovery.java:147) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.log.SortedLogRecovery.recover(SortedLogRecovery.java:291) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.log.TabletServerLogger.recover(TabletServerLogger.java:542) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.TabletServer.recover(TabletServer.java:1204) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.apache.accumulo.tserver.tablet.Tablet.<init>(Tablet.java:334) ~[accumulo-tserver-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        ... 7 more
Caused by: java.io.IOException: incorrect header check
        at org.apache.hadoop.io.compress.zlib.ZlibDecompressor.inflateBytesDirect(Native Method) ~[hadoop-client-api-3.3.4.jar:?]
        at org.apache.hadoop.io.compress.zlib.ZlibDecompressor.decompress(ZlibDecompressor.java:225) ~[hadoop-client-api-3.3.4.jar:?]
...
```

One tablet for the metadata table is in an offline state and the `ci` table is in a deleting state.

### PR DESCRIPTION
**Pull request by dlmarion**
RecoveryLogsIterator was using the client side RFile scanner which does not allow for the Recovery scope to be used. This change modifies the RecoveryLogsIterator to use the server side RFile reader code (FileOperations) with the Recovery crypto environment

Closes #2979

### CODE REVIEW

**Review by milleruntime — APPROVED** [review]
Looks good.

**Comment by ctubbsii** [comment]
It's unfortunate we have two separate RFile read paths. It'd be really nice to just have one that was easier for users to use, and also supported all our internal needs.

**Comment by milleruntime** [comment]
> It's unfortunate we have two separate RFile read paths. It'd be really nice to just have one that was easier for users to use, and also supported all our internal needs.

Yeah that would be nice. For this situation, we would need to have the RFile API take a CryptoService or something to differentiate it from the table properties. Maybe once crypto graduates from being experimental, we can add something to the RFile API. But there are likely to be other situations like this though, where we don't won't to expose internals and still need FileSKVIterator.

**Comment by ctubbsii** [comment]
I think having the RFile API accept an optional CryptoService was something I had previously suggested, but yeah, maybe it's premature if it's still marked experimental.

**Pull request merged**
