### PR TITLE
Update ConstraintChecker.java

### PR DESCRIPTION
**Pull request by Umang228**
Changed the ArrayList object from constrains to constraints.

### CODE REVIEW

**Review by EdColeman — APPROVED** [review]

**Review by EdColeman — CHANGES_REQUESTED** [review]
You need to also change the places in the code that had "constrains" to the correct "constraints" - it occurs 3 places in the file.

You can run the following maven command to perform the same QA checks performed on submission:
`mvn verify javadoc:jar -Psec-bugs -DskipTests`

if you can get that to pass the QA checks will likely succeed.

**Review by EdColeman — APPROVED** [review]

**Comment by EdColeman** [comment]
Thanks for the contribution @Umang228  and welcome to the Apache Accumulo community. If you would like to be listed as a contributor on Accumulo's people page please make a website PR for people.md. https://github.com/apache/accumulo-website/edit/main/pages/people.md
If you intend to make more contributions, please consider subscribing to the dev list and introducing yourself. Also, you can use the dev list or slack to reach out if you have questions about anything. https://accumulo.apache.org/contact-us/

**Comment by Umang228** [comment]
Sir, can u plz be a bit more specific about what i have to do in people.md

**Comment by EdColeman** [comment]
Basically you want to create a pull request to the Accumulo web-site repo updating the file, people.md [accumulo-website/pages/people.md](https://github.com/apache/accumulo-website/blob/main/pages/people.md#contributors) and add yourself to the contributors section.

Go to https://github.com/apache/accumulo-website and clone that repo.
Checkout the people.md file.  https://github.com/apache/accumulo-website/blob/main/pages/people.md
Add your information in markdown format into the table (name, organization (optional), timezone (optional)) in the contributors section.
Submit your change as a pull request.

You may be able to to this via the github UI, but I am unsure if the edit this page option is available to you.

**Pull request merged**
