### PR TITLE
ACCUMULO-2806: changed permissions of /accumulo to 700

### PR DESCRIPTION
**Pull request by milleruntime**
Simple fix for ACCUMULO-2806.  I had overcomplicated the issue by attempting to set the permissions independently for each directory under /accumulo but I think just securing permissions at the top will work fine. 

My question for the community, will this change break/complicate 3rd party tools?

### CODE REVIEW

**Comment by joshelser** [comment]
> My question for the community, will this change break/complicate 3rd party tools?

I am A-OK with this "breaking" any 3rd party tools. There should be no need for applications to read the "raw" data stored under `/accumulo`. If someone was expecting this, they can do the `-chown` as a reminder that they're allowing this.

**Comment by joshelser** [comment]
Also, @milleruntime can you scope out our tests to see if we have these cases covered with HDFS permissions:

* Bulk load of files into Accumulo
* ExportTable

We should be able to set up a secure-enough MiniDfsCluster that will enforce fs permissions. These are the two cases that come to mind in which "things" reach into `/accumulo`

**Comment by busbey** [comment]
Does the shell work after this change? (do we have a test for the shell working?)

**Comment by milleruntime** [comment]
> I am A-OK with this "breaking" any 3rd party tools. There should be no need for applications to read the "raw" data stored under /accumulo. If someone was expecting this, they can do the -chown as a reminder that they're allowing this.

I agree. This change enforces proper behavior while also securing internal files.

**Comment by milleruntime** [comment]
> Does the shell work after this change? (do we have a test for the shell working?)

@busbey Yes and yes.  I tested basic shell functionality (create table, insert, scan, create user, grant) manually using Uno.  It also passed ShellServerIT and ShellConfigIT

**Comment by milleruntime** [comment]
Discovered these babies (which use the Hadoop FileSystem object in some way) and they all pass:
- FastBulkImportIT
- BulkFileIT
- ImportExportIT 
I will run sunny ITs before I leave for the day.

**Comment by joshelser** [comment]
> Discovered these babies (which use the Hadoop FileSystem object in some way) and they all pass:

I wouldn't trust this... We very likely don't configure HDFS to actually enforce filesystem permissions (no, this is not the default).

https://hadoop.apache.org/docs/r2.7.2/hadoop-project-dist/hadoop-hdfs/HdfsPermissionsGuide.html#Configuration_Parameters

**Comment by milleruntime** [comment]
> We very likely don't configure HDFS to actually enforce filesystem permissions (no, this is not the default).

According to [Hadoop](https://hadoop.apache.org/docs/r2.7.2/hadoop-project-dist/hadoop-hdfs/hdfs-default.xml), the default setting for dfs.permissions.enabled is true. 

So I guess the question is whether our current tests are enough or not.

**Comment by joshelser** [comment]
>According to Hadoop, the default setting for dfs.permissions.enabled is true.
> So I guess the question is whether our current tests are enough or not.

+1 to both points. Thanks for investigating for me :)

**Pull request merged**
