### PR TITLE
Accumulo 4378

### PR DESCRIPTION
**Pull request by melrief**

### CODE REVIEW

**Comment by melrief** [comment]
@keith-turner added the @since 1.8.0 annotation to the javadocs as requested

**Comment by joshelser** [comment]
Thanks! Merging.

**Comment by keith-turner** [comment]
Whats going on with the other commit?  I suspect it has different commit hash when josh merged it, but when I click on the commit it shows some diffs.  I am not sure whats going on and I Am curious (don't let this keep you from merging @joshelser )  Commit w/ the `@since` tags looks good.  Thanks!

**Comment by joshelser** [comment]
Yeah, something is goofy @keith-turner. Just fixing it by hand :)

**Pull request closed without merging**
