### PR TITLE
Update micrometer

### PR DESCRIPTION
**Pull request by ctubbsii**

### CODE REVIEW

**Comment by ctubbsii** [comment]
@cshannon  I created a separate PR to reproduce the error you observed in #3207 to see if there's an easy way to address it here.

**Comment by cshannon** [comment]
We could try defining our own version of Netty and import the BOM instead of relying on transitive dependencies. Also, there appears to be an exclusion for Netty for Zookeeper in core but nowhere else which is weird, especially because as far as I know we need Netty for Zookeeper to work.

https://github.com/apache/accumulo/blob/fe31930ccef448a549cea082943c510b678dbecd/core/pom.xml#L127-L135

Furthermore, the exclusion doesn't do anything as the GAV is incorrect as Zookeeper has a dependency on netty-handler and not netty.

**Comment by ctubbsii** [comment]
> We could try defining our own version of Netty and import the BOM instead of relying on transitive dependencies. Also, there appears to be an exclusion for Netty for Zookeeper in core but nowhere else which is weird, especially because as far as I know we need Netty for Zookeeper to work.

My best guess is that we used to rely on ZooKeeper being brought in transitively by the core module, but that changed when we started doing dependency analysis, we needed to specify it in every module where we explicitly use ZooKeeper  as a direct dependency, but we didn't carry over the exclusion.

As for the exclusion itself, it's possible we were just relying on the netty version being resolved by Hadoop or another dependency. In order to converge on a specific version of netty, we should specify the version in our top-level POM's dependencyManagement section. However, I don't know which of our dependencies use Netty, and whether the version we'd pick will work for all of them... we'd have to check.

> 
> https://github.com/apache/accumulo/blob/fe31930ccef448a549cea082943c510b678dbecd/core/pom.xml#L127-L135
> 
> Furthermore, the exclusion doesn't do anything as the GAV is incorrect as Zookeeper has a dependency on netty-handler and not netty.

It probably did work at some earlier point. It's frustrating that this isn't a simple fix, because micrometer and ZooKeeper depend on Netty via different transitive paths, so there's no simple common entry point, like both depending on netty-handler.

**Comment by cshannon** [comment]
> It probably did work at some earlier point. It's frustrating that this isn't a simple fix, because micrometer and ZooKeeper depend on Netty via different transitive paths, so there's no simple common entry point, like both depending on netty-handler.

Right, that's why I figured I'd go with a BOM import to cover everything in my PR https://github.com/ctubbsii/accumulo/pull/20 since there's no common entry point.

The Jenkins job appears to have [passed](https://github.com/cshannon/accumulo/actions/runs/4325083411/jobs/7550765166) for that run in my branch (after I fixed the import order)

**Comment by ctubbsii** [comment]
Luckily, netty has a BOM, so we don't need to converge each dependency individually!

**Comment by cshannon** [comment]
> Luckily, netty has a BOM, so we don't need to converge each dependency individually!

Yep, we appear to have come to the same fix at the same time. :) 

I  had created a PR to your fork because it wouldn't let me push a commit to this.

**Review by cshannon — APPROVED** [review]
Looks good to me now. Do you also want to update opentelemetry in this PR or separate? We've updated them together in the past I think.

**Comment by cshannon** [comment]
We should also update https://github.com/apache/accumulo-testing with the new version when merged I guess.

**Comment by ctubbsii** [comment]
> Looks good to me now. Do you also want to update opentelemetry in this PR or separate? We've updated them together in the past I think.

They aren't related, and don't need to be updated together. This one was done separate, just because of the dependency convergence issue. I haven't looked into opentelemetry to know if it has any issues being updated.

**Pull request merged**
