### PR TITLE
cleanup unused methods

### PR DESCRIPTION
**Pull request by ddanielr**
Remove unused methods from MetadataTableUtil

### CODE REVIEW

**Comment by cshannon** [comment]
Looks like the imports are not properly sorted according to CI.

**Comment by ddanielr** [comment]
> Looks like the imports are not properly sorted according to CI.

Yeah I saw that. I spun this out of my current work since it's just cleanup. 
Do you use pre-commit hooks for auto running the format and import sort maven commands?

**Review by DomGarguilo — APPROVED** [review]
LGTM once the checks pass

**Comment by DomGarguilo** [comment]
> Do you use pre-commit hooks for auto running the format and import sort maven commands?

I run `mvn clean package -DskipTests` which sorts and formats.

**Comment by cshannon** [comment]
> > Looks like the imports are not properly sorted according to CI.
> 
> Yeah I saw that. I spun this out of my current work since it's just cleanup. Do you use pre-commit hooks for auto running the format and import sort maven commands?

as Dom said just running a build will run the QA plugins to make sure things like imports are correct which is all I do

**Review by ctubbsii — APPROVED** [review]

**Pull request merged**
