### PR TITLE
update wait for tservers to allow infinite wait

### PR DESCRIPTION
**Pull request by EdColeman**
Fix issue with allowing infinite wait for tserver count

This is a follow-on and updates PR https://github.com/apache/accumulo/pull/3231 and issue https://github.com/apache/accumulo/issues/3159

### CODE REVIEW

**Comment by ddanielr** [comment]
Given that the intervals just need to be changed, wouldn't just changing the number of retries and the increment variable accomplish that without redoing the logic? 

```
    long retries = 10;
    long waitPeriod = maxWait / retries;
    long waitIncrement = 0;
    
    if (maxWait <= 0) {
      log.info("tserver availability check set to block indefinitely, To change, set {} > 0.",
          Property.MASTER_STARTUP_TSERVER_AVAIL_MAX_WAIT.getKey());
      maxWait = Long.MAX_VALUE;
      
      // Change retry logic for incremental backoff and logging due to indefinite blocking
      retries = maxWait;
      waitPeriod = maxWait;
      waitIncrement = 15_000;
    }
 ```

**Comment by EdColeman** [comment]
I think that trying to use `maxWait(waitPeriod, MILLISECONDS)` when waitPeriod is MAX_LONG would make the time between checks excessively long  - we should continue to poll at a reasonable interval (this code picked 30 seconds as a max)

**Comment by ddanielr** [comment]
> I think that trying to use `maxWait(waitPeriod, MILLISECONDS)` when waitPeriod is MAX_LONG would make the time between checks excessively long - we should continue to poll at a reasonable interval (this code picked 30 seconds as a max)

Sure, that could be reduced. I believe the original value was 50ms or half of maxWait. 
The incremental change is what causes the inaccuracy for defined startup timeouts.

**Comment by EdColeman** [comment]
@ddanielr is going to post an alternate instead of this approach.

**Comment by ctubbsii** [comment]
#3235 supersedes this

**Pull request closed without merging**
