### PR TITLE
Upgrade to Jline 2.14.6

### PR DESCRIPTION
**Pull request by Manno15**
Based on the Jira ticket [4320](https://issues.apache.org/jira/browse/ACCUMULO-4320). I upgraded Jline to the newest version of Jline2 and fixed several errors that came from upgrading. Most were just spacing issues that were fixed with `'\t'` and one EasyMock issue. All IT's passed locally though I'd appreciate someone double-checking that for me.

I will look into upgrading to Jline3 as well.

### CODE REVIEW

**Comment by ctubbsii** [comment]
@Manno15 Thanks for this. I saw a new build warning:

```
[WARNING] /home/runner/work/accumulo/accumulo/shell/src/main/java/org/apache/accumulo/shell/Shell.java:[623,13] shutdown() in jline.console.ConsoleReader has been deprecated
```

Presumably, this is because `ConsoleReader` is now `Closeable`. Is that warning something that you can fix?

Also, I'm running the full ITs myself, as a double-check, and will run some manual checks in the shell to see if there are any behavioral differences.

Also, do you know why the `\t` changes in the tests were necessary? Were we always outputting `\t`, and the console was replacing them with spaces?

Also, the original ticket mentioned the following additional things that I'm wondering if they need anything done for them:

- [ ] Closing FileReader opened by FileHistory
- [ ] The number in "Display all n possibilities?" differs from the actual number of commands listed
- [ ] Upgrade to jansi 1.12
- [ ] Default buffer is not printed correctly

Some of these are lacking details, so it's not clear what was intended to be done for them, but did you look at any of those to see if those were necessary to address?

**Comment by Manno15** [comment]
@ctubbsii I did not see that warning but I will take a look.

Thank you for taking another look at it for me. I did some checks on the shell myself and I noticed no issue.

The `\t` changes were necessary because for some reason it would error out without them. It wouldn't accept that they were equal. I noticed when I copy-pasted the result from the shell into the string it automatically added the `\t` for me and it worked. That is what caused most of the errors from these changes. 

I think the other things mentioned are just what else was fixed in 2.14.2. I noticed it was just copied from the release notes from Jline. Not sure if it was intended as something to add additional to the upgrade for accumulo.

**Comment by ctubbsii** [comment]
> @ctubbsii I did not see that warning but I will take a look.

Thanks.

> I suppose it is also possible to just strip out the `\t` when we print to the shell. Maybe that would be a better change, we wouldn't have to make add the `\t` in all the related IT's.

I think your change is fine. I was just curious why it previously worked.

> I think the other things mentioned are just what else was fixed in 2.14.2. I noticed it was just copied from the release notes from Jline. Not sure if it was intended as something to add additional to the upgrade for accumulo.

Okay, cool.

**Comment by Manno15** [comment]
Yeah, I am not sure why it previously worked either. I couldn't find any details on what changed in Jline that would cause such a thing.

**Comment by Manno15** [comment]
> [WARNING] /home/runner/work/accumulo/accumulo/shell/src/main/java/org/apache/accumulo/shell/Shell.java:[623,13] shutdown() in jline.console.ConsoleReader has been deprecated

I forgot to add the fix to this back. I kept switch from Jline versions so I took it out. The new function is now `close()`. I will make that change.

**Comment by ctubbsii** [comment]
It looks like #1715 introduced a bunch of new build warnings, so they kind of dominate any that this might produce. I saw your change to use `close()`, and it probably fixes the warning I saw, but if not, it can be dealt with later. I wouldn't worry about it here. I'm just waiting on the ITs to pass for me before I approve.

**Comment by ctubbsii** [comment]
I did see a test failure with `org.apache.accumulo.test.ShellIT.insertIntoSpecifiedTableTest`

**Comment by Manno15** [comment]
I slightly messed things up trying to push the change. I was working from two different machines and things weren't aligned properly. I think I fixed it.

**Comment by ctubbsii** [comment]
I re-ran the ITs, and saw failures in VolumeIT... but that should be unrelated. I'm going to investigate a little bit first, before merging.

**Review by ctubbsii — APPROVED** [review]
Fixed the test error in #1795  and this looks okay.

**Pull request merged**
