### PR TITLE
Use long instead of int for monitor scan rate (fixes #1858)

### LINKED ISSUE #1858: Monitor should use long instead of integer for "Scan (Entries/s)" graph
When running Accumulo 1.10 on a large cluster with a very high scan rate, the "Scan (Entries/s)" graph flatlined at 2,147,483,647. Looking at the [Monitor code](https://github.com/apache/accumulo/blob/6bf3f406481a392c5bcffc15d44ccdfd52c2b577/server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java#L157), it appears that the queryRateOverTime and scanRateOverTime lists use an Integer instead of a Long to store the rates. Changing to a Long should solve the problem.

### PR DESCRIPTION
**Pull request by brianloss**
This is the version of the changes from PR #1860 to go on the main branch. I had to upgrade the flot library to a newer version (from 0.8.3 to 4.2.1) since the old version didn't render properly when values exceeding a 32-bit int appeared in the graph.

I tested by modifying the monitor code to use large values for scan rate. Here's a screenshot:

image

### CODE REVIEW

**Review by milleruntime — APPROVED** [review]
Looks good!

**Review by ctubbsii — CHANGES_REQUESTED** [review]
All files added to `monitor/resources/external/` should be added without modification. From where were these obtained? And were they added without modification?

The following LICENSE files have been modified to reflect our redistribution of flot code. They must be updated to properly reflect the updated version of flot.

* assemble/src/main/resources/LICENSE
* LICENSE
* server/monitor/src/main/appended-resources/META-INF/LICENSE

Aside from the license issues, these changes look fine to me.

**Comment by brianloss** [comment]
> All files added to `monitor/resources/external/` should be added without modification. From where were these obtained? And were they added without modification?
> 
> The following LICENSE files have been modified to reflect our redistribution of flot code. They must be updated to properly reflect the updated version of flot.
> 
> * assemble/src/main/resources/LICENSE
> * LICENSE
> * server/monitor/src/main/appended-resources/META-INF/LICENSE
> 
> Aside from the license issues, these changes look fine to me.

I downloaded it from their [releases page](https://github.com/flot/flot/releases) and inserted the source files unmodified. AFAICT, the license file hasn't been updated since 2014 shows no differences from the currently checked in license file [here](https://github.com/apache/accumulo/blob/main/server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/external/flot/LICENSE.txt). Therefore, I'm not sure what I'd update in the files you reference. I didn't see the flot version referenced in them anywhere.

**Comment by ctubbsii** [comment]
> I downloaded it from their [releases page](https://github.com/flot/flot/releases) and inserted the source files unmodified.

Okay, cool. I recommend including this fact in the git commit message when this gets merged, so it's easy to track down later.

> AFAICT, the license file hasn't been updated since 2014 and shows no differences from the currently checked in license file [here](https://github.com/apache/accumulo/blob/main/server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/external/flot/LICENSE.txt).

It's likely that we didn't update our own LICENSE files the last time we updated flot, because the copyright dates seemed a little different than what's in that file.

> Therefore, I'm not sure what I'd update in the files you reference. I didn't see the flot version referenced in them anywhere. Are you suggesting I need to update those files to include the version now?

No, there's no need to include the version. The current files I listed looked slightly out of sync with the file you pointed to (copyright dates, in particular... I didn't take a very deep look). It may just be a matter of doing a sanity check on our own LICENSE files to make sure they aren't out of sync... and, if needed, add a reference to Flot's bundled LICENSE.txt file, so it's simpler to keep sync'd.

**Comment by brianloss** [comment]
@ctubbsii I updated my commit to include a reference to the downloaded source file location, as well as updating the LICENSE files to reference the flot source repo and flot's MIT license file. I checked the license and confirmed the inline dependency on "jQuery resize event" still exists and hasn't changed. The only discrepancy I found was the copyright dates. Those dates had already changed before the the 0.8.3 release that was our previous version, so they've been incorrect in our code for a while. It looks like the update to the 0.8.3 release happened in 0ca5cd3389f366e311d6f89f64cf68c3d0f3ca41 and the prior LICENSE file updates relating to flot happened in 9d9118d4e0eb22079a58d332d5b50e12348e0328. Please let me know if you think this is sufficient or if there are other changes you would like.

**Review by ctubbsii — APPROVED** [review]
LGTM. Thanks, @brianloss

**Pull request merged**
