### PR TITLE
Refactor common code into PropUtil

### LINKED ISSUE #2772: Explore combining TablePropUtil and NamespacePropUtil functionality
TablePropUtil and NamespacePropUtil contain virtually identical code functionality. The primary difference is the use of the PropUtil<TableId> and PropUtil<NamespaceId> parameters passed into the methods. 

It should be explored if these two methods could be combined. 

See #2633 and #2771 for additional details.

### PR DESCRIPTION
**Pull request by DomGarguilo**
This PR takes similar logic from `NamespacePropUtil` and `TablePropUtil` and moves it into their parent class, `PropUtil`.

Fixes #2772

### CODE REVIEW

**Review by dlmarion — APPROVED** [review]
LGTM

**Comment by EdColeman** [comment]
With the concrete methods now in the parent (PropUtil) taking abstract ids, are the methods even needed in the NamespaeUtil and TableUtil classes?

**Review by jmark99 — APPROVED** [review]

**Comment by DomGarguilo** [comment]
> With the concrete methods now in the parent (PropUtil) taking abstract ids, are the methods even needed in the NamespaeUtil and TableUtil classes?

Im not sure that they are needed. I might be possible to get rid of the two child classes entirely and just use the methods from PropUtil. I'll try that out and see how it works.

**Review by Manno15 — APPROVED** [review]

**Comment by DomGarguilo** [comment]
> > With the concrete methods now in the parent (PropUtil) taking abstract ids, are the methods even needed in the NamespaeUtil and TableUtil classes?
> 
> Im not sure that they are needed. I might be possible to get rid of the two child classes entirely and just use the methods from PropUtil. I'll try that out and see how it works.

It turned out to require more changes than I initially thought, but I made these changes in [f547bfb](https://github.com/apache/accumulo/pull/2796/commits/f547bfbe11e82e0ee86fdecdb08be2cf482a19de), @EdColeman

**Comment by DomGarguilo** [comment]
I realized that the `AbstractId` parameter in `PropUtil.setProperties` was only being used in the exception message. I found that using the `PropStoreKey` in its place is even more descriptive so I removed  `AbstractId` from the method in [922ca4d](https://github.com/apache/accumulo/pull/2796/commits/922ca4d6b738e16eed182ef0c7815928d0cbe166).

**Comment by DomGarguilo** [comment]
There have been a few approved reviews on this PR but a bit has changed since the reviews. I wanted to see if anyone wanted to take another quick look and approve this PR again before I merge it. I left a few comments explaining the commits to make things easier to review.

**Comment by EdColeman** [comment]
Going even further - is PropUtil necessary? - it looks like the functions could be moved into ZooBasedConfiguration.

**Comment by DomGarguilo** [comment]
> Going even further - is PropUtil necessary? - it looks like the functions could be moved into ZooBasedConfiguration.

Possibly? It looks like the places that the functions are used there is usually not a `ZooBasedConfiguration` object available so one would need to be created in order to use these functions unless I am misinterpreting something. It looks like it might be possible to more easily more these functions into `ServerContext` if that seems like it would be an improvement?

**Review by EdColeman — APPROVED** [review]
LGTM - This moves in the right direction - it strikes me as being odd that PropUtil is needed - but I don't see a better place for it now and these changes make future changes easier if that is decided as desirable.

**Pull request merged**
