### PR TITLE
Bump surefire and failsafe plugins to 3.0.0-M6

### LINKED ISSUE #2555: Issue upgrading to surefire version M5
In order to run some tests that are being changed in #2545, it appears that we need to upgrade the surefire version from M4 to M5. The issue with this is it causes certain tests to fail with hard to debug issues.
https://github.com/apache/accumulo/blob/8c07e0c8281fef857eeda03f78e287a37cdc6e47/pom.xml#L158-L159

At least the two tests mentioned above, [`RowHashIT.test`](https://github.com/apache/accumulo/blob/26821c1926a3b48943f3231725f8e2e0735d05fb/hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/RowHashIT.java#L80) and [`ShellServerIT.scansWithClassLoaderContext`](https://github.com/apache/accumulo/blob/f442f94b1b2505d9425bbbcc940f26225bfe3930/test/src/main/java/org/apache/accumulo/test/shell/ShellServerIT.java#L1692) still fail when surefire is upgraded.

I wasn't sure if a separate issue should be made for these failing tests given that they do not fail on main and only fail when surefire is upgraded. Below is the strack trace and a few details for each test in case it might be evident to someone what a solution might be. I have not been able to make any progress in tracking down what the specific cause of the test failures might be and this is holding up progress on #2545.

<details>
  <summary>RowHashIT</summary>

```
[INFO] Running org.apache.accumulo.hadoop.its.mapreduce.RowHashIT
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 17.04 s <<< FAILURE! - in org.apache.accumulo.hadoop.its.mapreduce.RowHashIT
[ERROR] org.apache.accumulo.hadoop.its.mapreduce.RowHashIT.test  Time elapsed: 17.029 s  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at accumulo.hadoop.mapreduce@2.1.0-SNAPSHOT/org.apache.accumulo.hadoop.its.mapreduce.RowHashIT.runTest(RowHashIT.java:100)
	at accumulo.hadoop.mapreduce@2.1.0-SNAPSHOT/org.apache.accumulo.hadoop.its.mapreduce.RowHashIT.test(RowHashIT.java:82)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

</details>

<details>
  <summary>ShellServerIT</summary>

```
[INFO] Running org.apache.accumulo.test.shell.ShellServerIT
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 13.916 s <<< FAILURE! - in org.apache.accumulo.test.shell.ShellServerIT
[ERROR] org.apache.accumulo.test.shell.ShellServerIT.scansWithClassLoaderContext  Time elapsed: 4.115 s  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at accumulo.test@2.1.0-SNAPSHOT/org.apache.accumulo.test.shell.ShellServerIT.scansWithClassLoaderContext(ShellServerIT.java:1718)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)


```

</details>

### PR DESCRIPTION
**Pull request by ctubbsii**
* Bypass buggy 3.0.0-M5 version; this fixes #2555

### CODE REVIEW

**Comment by DomGarguilo** [comment]
This looks good so far to me. The tests that were failing with M5, ShellServerIT and RowHashIT, now pass on this branch. 

For some reason there is a test failing in the checks, MiniAccumuloClusterImplTest, but it passes for me when run locally so not sure whats going on there.

**Comment by ctubbsii** [comment]
> This looks good so far to me. The tests that were failing with M5, ShellServerIT and RowHashIT, now pass on this branch.

I confirmed that too. It is unlikely that it broke any other tests, but I'll try to run the full ITs, just in case.

> For some reason there is a test failing in the checks, MiniAccumuloClusterImplTest, but it passes for me when run locally so not sure whats going on there.

Yeah, it's probably just a temporary resource issue in the GH actions runner. I triggered a re-run.

**Review by DomGarguilo — APPROVED** [review]
Ran `Psunny` as well as the other tests that were in question. LGTM once the checks pass.

**Comment by ctubbsii** [comment]
All ITs passed, so I'll merge this.

**Pull request merged**
