### PR TITLE
Some cleanup of Zoo-related code

### PR DESCRIPTION
**Pull request by ctubbsii**
Remove three unneeded ZooCache constructors - these were simple
variations of the main one, with very little added value, and removing
them made some method calls slightly less convenient, but enabled a lot
of code complexity reduction.

Remove unneeded ZooConfigurationFactory - it was unnecessarily complex,
written to handle caching of ZooConfiguration objects for multiple
InstanceIds; however, it was only ever used by
ServerConfigurationFactory, which only ever called it once, with the
first instanceId it found. This is sufficient. If further work is needed
to ensure ServerConfigurationFactory only uses a single InstanceId, that
work should be done in that class. This change preserves the existing
behavior, but much more simplified. An additional benefit to removing
this is that it can no longer be confused with the similarly named
ZooCacheFactory.

Remove unneeded "hack" to use a watcher in ZooCacheFactory that supplied
an unused Watcher to force the ZooCacheFactory to return a new instance.
Now, it explicitly returns a new instance, with a method that says as
much in its name and javadoc. The old method wasn't used for anything
else.

Remove unnecessary call in ReplicationIT to ZooCacheFactory, instead
using the ZooCache that is already available in the ClientContext in the
test.

### CODE REVIEW

**Comment by ctubbsii** [comment]
I am working towards issue #2298. These changes allow the code to be cleaned up and simplified quite a bit. However, I think the final result is getting too big. I think these changes are sufficient to stand on their own, and I'll continue working on #2298, with the expectation that this will be merged first.

**Review by milleruntime — APPROVED** [review]
Nice!

**Review by EdColeman — APPROVED** [review]
LGTM - Overall this looks to go in a good direction in simplifying things.

I do have questions concerning the watchers in context of single node prop conversion, but I will need to merge those changes before I'd have additional comments.  This can be merged and once conflicts with the single node store are reconciled, if changes are desired they can be handled in a separate PR.

**Comment by ctubbsii** [comment]
All ITs passed with these changes.

**Pull request merged**
