### PR TITLE
 Make old MR more backwards compatible & deprecate

### PR DESCRIPTION
**Pull request by milleruntime**
1) Make old MR more backwards compatible
* Remove new API that had been added
* Remove new functionality that was added for summarizers and execution hints
* Add back non consequential deprecated methods that were dropped

2) Deprecate core client Map reduce API

This is also work towards #788

### CODE REVIEW

**Comment by mikewalch** [comment]
I am not sure if the old MR code should be deprecated for 2.0.  It might make sense to keep it for 2.0 and hold off on releasing the MR API until 2.1.  This should give the new API time to mature.

**Comment by milleruntime** [comment]
> I am not sure if the old MR code should be deprecated for 2.0. It might make sense to keep it for 2.0 and hold off on releasing the MR API until 2.1. This should give the new API time to mature.

I think that is a good idea.  IIRC @ctubbsii had some reasons for separating the MR code from core in the first place though so perhaps he can weigh in on.

**Comment by ctubbsii** [comment]
I had made a first pass attempt at this also. I will try to reconcile your branch with mine, and add commits to your branch, as my review.

**Comment by milleruntime** [comment]
Sounds good.  I won't make any further changes on this branch for now.

**Comment by ctubbsii** [comment]
@milleruntime I had to force-push to resolve the numerous conflicts with master. I'll continue to reconcile my branch with this one to add my commits on top of yours.

**Comment by ctubbsii** [comment]
Force pushed again to resolve conflicts with master. I've been sick the last few days, but am slowly working towards wrapping up my changes on top of this PR.

**Comment by ctubbsii** [comment]
Okay, I've reconciled my working branch with this one, restoring a few additional removed APIs since 1.9, and cleaning up some other stuff, including slight rewording of deprecated javadoc messages.

Tests are broken still, and there may be some opportunity to clean up deprecation warnings from the compiler. I'll work on those issues to wrap this up.

**Pull request merged**
