### PR TITLE
Update Thrift from 0.16.0 to 0.17.0

### PR DESCRIPTION
**Pull request by dlmarion**

### CODE REVIEW

**Comment by dlmarion** [comment]
It looks like Thrift 0.17.0 requires gradle to be installed to successfully build. You can install gradle using the instructions [here](https://gradle.org/install/) and then put `gradle` on your $PATH.

**Comment by dlmarion** [comment]
Java Thrift 0.17.0 changes [here](https://github.com/apache/thrift/blob/master/CHANGES.md#java)

**Comment by dlmarion** [comment]
Looks like this update changes the generated code by:
  1. Adding @Override annotations
  2. Adding @SuppressWarnings annotations
  3. Adding methods calls as part of [THRIFT-5519](https://issues.apache.org/jira/browse/THRIFT-5519)
  
I used the following command to see the changes:
```
git diff main | grep '+' | grep -v Override | grep -v SuppressWarnings | grep -v @@
```

**Comment by dlmarion** [comment]
Full IT build passed successfully

**Review by ctubbsii — APPROVED** [review]
Even with the build error due to PMD, I'm thinking that this is okay to merge. Most people aren't going to need to build libthrift.jar themselves, because it's published in Maven Central for them by its developers. If they do need to rebuild it themselves, they can patch out PMD from the build as a workaround.

For everyone else, they don't really need gradle or to worry about the PMD build bug, because the build works just fine if all you need is the compiler (which is most devs): `./configure --without-libs && make`. The build might error out on some platforms (it did on mine... I think because I have a newer version of GCC), but would be enough to get the compiler built at `./compiler/cpp/thrift`.

**Pull request merged**
