### PR TITLE
Changed KeyTest for assertArrayEquals assertion

### PR DESCRIPTION
**Pull request by vallari118**
Changed KeyTest.java file with assertTrue to assertArrayEquals

### CODE REVIEW

**Review by EdColeman — CHANGES_REQUESTED** [review]
You need to include the import - `import static org.junit.Assert.assertArrayEquals;`

imports should be in sorted order and avoid using wild cards (*).

You can use the following command to run the full set of QA checks:
`mvn clean verify javadoc:jar -Psec-bugs package -DskipITs=true -DskipTests=true`

When that compiles cleanly you should consider running at least the tests (IT tests can take some time)

**Review by EdColeman — CHANGES_REQUESTED** [review]
You can not uses wildcards  `import static org.junit.Assert.*;.`  This would fail the QA build. 

Please expand to use individual imports.  

Please try to get a clean run using `mvn clean verify -DskipITs` or some variation that will run the QA tests locally before submitting am update.

**Comment by EdColeman** [comment]
You indicated that you fixed the issue - but they are not showing up in github / this PR.  You need to push your changes to your repo with the same branch that you created the PR - that should trigger github to update the PR with the latest files.  As it is now, your commit goes to a page with the following note: `This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository`
And the code there does not look like it has been corrected.

**Comment by vallari118** [comment]
I have pushed the changes to the same branch of my Repo with which I created PR. In the PR I am able to see all 3 commits done by me. Can you please check ?

**Comment by vallari118** [comment]
https://github.com/apache/accumulo/compare/main...vallari118:dev-assertTrueArray-Fix?expand=1 Check This

**Comment by vallari118** [comment]
Also my project is not getting set locally. 
image

**Comment by Manno15** [comment]
Accumulo 2.1.0-SNAPSHOT requires Java 11.  In the image above, you are building with java 8.

**Comment by EdColeman** [comment]
Your changes are now visible - not sure what was going on there.
As @Manno15 shared, you need jdk-11 to build the 2.1.x line of Accumulo

If you can build / run the QA tests, your code should pass - one of the things is that the build will enforce the ordering of the imports so they are standard across the project (static imports first, then alphabetical)

**Comment by vallari118** [comment]
I am using Java 11 to compile.

image

**Comment by EdColeman** [comment]
When you ran maven, the error shows you are running jdk-8 from the command line.  Do you have JAVA_HOME set on the command line? For example, my env:
`
> env | grep JAVA
JAVA_HOME=/usr/java/jdk-11

and

> java --version
openjdk 11 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
`

**Comment by EdColeman** [comment]
Superseded by https://github.com/apache/accumulo/pull/2079

**Pull request closed without merging**
