### PR TITLE
replace moniitor by monitor

### PR DESCRIPTION
**Pull request by josselinchevalay**

### CODE REVIEW

**Comment by josselinchevalay** [comment]
yes how to do that ?

**Comment by mjwall** [comment]
You can either put a PR against https://github.com/apache/accumulo-website/blob/master/pages/people.md or we can put up that PR for you.  Thanks

**Comment by josselinchevalay** [comment]
done

**Comment by mjwall** [comment]
@josselinchevalay merged in with https://github.com/apache/accumulo/commit/761b4eb7f377c114088b33c482d15310d4136665.  Please close this PR

**Comment by mjwall** [comment]
nevermind, I closed it in another commit.  Thanks @josselinchevalay

**Pull request closed without merging**
