### PR TITLE
Reduce usage of VolumeManagerImpl.get, use ServerContext.getVolumeManager instead

### LINKED ISSUE #666: Analyze creation of Volume Managers
In the course of reviewing #645 I was curious when VolumeChoosers are created.   Seems they are created by the VolumeManager.  Most code uses a single VolumeManager created as part of ServerContext.  However some code seems to create its own VolumeManager directly from config.  Where possible it's better to use the VolumeManager from server context.

Making this has a direct impact on #645 because it creates a VolumeChooser with a cache.

### PR DESCRIPTION
**Pull request by dlmarion**
Closes #666

### CODE REVIEW

**Review by Manno15 — APPROVED** [review]

**Comment by dlmarion** [comment]
No, I did not do that yet. Good find though.

**Comment by Manno15** [comment]
> No, I did not do that yet. Good find though. Are you going to write a new issue for the ChangeSecret failure?

If you can confirm that it happens on your end too then I will. It is possible I am not running it correctly.

**Comment by dlmarion** [comment]
Let me check....

**Comment by dlmarion** [comment]
So, I did the following:

```
~/Software/accumulo-2.1.0-SNAPSHOT/bin$ ./accumulo org.apache.accumulo.server.util.ChangeSecret --old secret --new secret2
2021-09-09T15:48:30,014 [conf.SiteConfiguration] INFO : Found Accumulo configuration on classpath at /home/dlmari2/Software/accumulo-2.1.0-SNAPSHOT/conf/accumulo.properties
old zookeeper password: 
new zookeeper password: 
Usage: org.apache.accumulo.server.util.ChangeSecret [options]
  Options:
    -auths, --auths
      the authorizations to use when reading or writing
      Default: <empty string>
    -c, --config-file
      Read the given client config file. If omitted, the classpath will be 
      searched for file named accumulo-client.properties
    -h, -?, --help, -help

    --password
      connection password (can be specified as '<password>', 
      'pass:<password>', 'file:<local file containing the password>' or 
      'env:<variable containing the pass>')
    --trace
      turn on distributed tracing
      Default: false
    -u, --user
      Connection user
    -o
      Overrides property in accumulo-client.properties. Expected format: -o 
      <key>=<value> 
      Default: []

Can only specify option --old once.
```

So, I guess I don't know how to run it. So I tried it w/out args and it did not fail.

```
~/Software/accumulo-2.1.0-SNAPSHOT/bin$ ./accumulo org.apache.accumulo.server.util.ChangeSecret
2021-09-09T15:49:29,824 [conf.SiteConfiguration] INFO : Found Accumulo configuration on classpath at /home/dlmari2/Software/accumulo-2.1.0-SNAPSHOT/conf/accumulo.properties
old zookeeper password: 
new zookeeper password: 
~/Software/accumulo-2.1.0-SNAPSHOT/bin$ 
```

**Comment by Manno15** [comment]
Interesting. That is what I did but I get a zookeeper KeeperException.

**Comment by dlmarion** [comment]
I'm not sure what password it's changing. But I noticed that using the old and new password in the shell worked. For example, both worked:
```
./bin/accumulo shell -u root -p secret
./bin/accumulo shell -u root -p secret2
```

Also, the following worked too:
```
./bin/accumulo shell -u root -p secret3
./bin/accumulo shell -u root -p foo
```


This doesn't make sense to me. I am going to init a new instance on `main` and try.

**Comment by dlmarion** [comment]
Ok, I think I see what's happening now. It looks like you can log into the shell with whatever password you want, and it fails later when you try to do something. However, some things work (list tables):

```
~/Software/accumulo-2.1.0-SNAPSHOT/bin$ ./accumulo shell -u root -p foo
Loading configuration from /home/dlmari2/Software/accumulo-2.1.0-SNAPSHOT/conf/accumulo-client.properties

Shell - Apache Accumulo Interactive Shell
- 
- version: 2.1.0-SNAPSHOT
- instance name: password-test
- instance id: a467172e-f040-420e-acb9-3cc0ec9dc02f
- 
- type 'help' for a list of available commands
- 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.hadoop.security.authentication.util.KerberosUtil (file:/home/dlmari2/Software/hadoop-3.2.1/share/hadoop/client/hadoop-client-api-3.2.1.jar) to method sun.security.krb5.Config.getInstance()
WARNING: Please consider reporting this to the maintainers of org.apache.hadoop.security.authentication.util.KerberosUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
root@password-test> tables
accumulo.metadata
accumulo.replication
accumulo.root
trace
root@password-test> scan -t accumulo.root
2021-09-09T16:05:33,102 [shell.Shell] ERROR: Could not load the specified formatter. Using the DefaultFormatter
2021-09-09T16:05:33,137 [shell.Shell] ERROR: org.apache.accumulo.core.client.AccumuloSecurityException: Error BAD_CREDENTIALS for user root - Username or Password is Invalid
```
Maybe this changed with 2.0, I'm more familiar with bad passwords failing to let you in the shell at all.

**Comment by DomGarguilo** [comment]
> It looks like you can log into the shell with whatever password you want, and it fails later when you try to do something.

This reminded me of #1868. Not too sure if they are related but seem similar to me.

**Comment by Manno15** [comment]
It doesn't appear we do any authentication until we try to exec a command.

**Pull request merged**
