### PR TITLE
avoids uneeded object allocation on ServiceLocksPath

### PR DESCRIPTION
**Pull request by keith-turner**
ServiceLockPaths allows filtering hosts using a predicate.  In the case where a predicate was passed in that always returned true a HostPort object needlessly allocated to pass to the predicate.  These changes refactor the predicate to only allocate the HostAndPort object when needed.  Before the changes in #4943 this was the behavior, that when all host were wanted no objects were allocated.

### CODE REVIEW

**Comment by cshannon** [comment]
The failure here seems like a spotsbug false positive.

**Comment by dlmarion** [comment]
Update your version of `main`. I had an un-pushed merge commit that I pushed after your merged in the other PR. That might be the conflict.

**Comment by keith-turner** [comment]
> The failure here seems like a spotsbug false positive.

I thought that was the case too.  Tried running the exact command locally and it passed. So went and looked at the git hash for the github actions build to make sure it was reading the same data and noticed it was merging in main prio to building.  So I tried merging main locally and then the build error messages started to actually make sense and line up with places where lamda existed doing the incorrect equality check.

**Comment by keith-turner** [comment]
> Update your version of main. I had an un-pushed merge commit that I pushed after your merged in the other PR. That might be the conflict.

Ha, I just saw this.  Wish I had seen it earlier before digging into the problem.

**Review by dlmarion — APPROVED** [review]

**Pull request merged**
