### PR TITLE
Fix ZooStoreFateIT

### PR DESCRIPTION
**Pull request by kevinrr888**
closes https://github.com/apache/accumulo/issues/4378
Added checks that the store has no transactions at the beginning and end of each test. Added missing cleanup to one test.

### CODE REVIEW

**Review by DomGarguilo — APPROVED** [review]
LGTM. Verified the test fails before these changes and passes after applying these changes.

**Review by cshannon — CHANGES_REQUESTED** [review]
This seems like something that we could move into a common area for before/after all tests since it's the same thing copied and pasted for every test. I have not tested this so not sure if it will work but could you maybe add a try/finally block into the executeTest() method and have it run before/after this line?: https://github.com/apache/accumulo/blob/f1914da45a73f6010b5eba5827a22e90b94557be/test/src/main/java/org/apache/accumulo/test/fate/zookeeper/ZooStoreFateIT.java#L78

For the AccumuloStoreFateIT it may not be needed since it uses a different table for each test anyways.

**Comment by kevinrr888** [comment]
Added the requested changes

**Review by cshannon — APPROVED** [review]
LGTM

**Pull request merged**
