### PR TITLE
Accumulo 4061

### PR DESCRIPTION
**Pull request by lstav**
Fixes ACCUMULO-4061. I started working on the shell code on a separate [branch](accumulo/tree/ACCUMULO-4558), which is why I removed the commits done for #ACCUMULO-4558 from this branch and moved them to the new one. If you wish to see what the commits comments were, you can look at them from the other branch (the commits will have ACCUMULO-4061 in the message).

### CODE REVIEW

**Comment by joshelser** [comment]
>  Yes, it'd be nice if the other services also had a status API (with a version).

+1. 

Having a version for the Master RPC would also be good.

Have you thought about trying to write a test for this? :) It would be a good adventure for you in using our lower-level RPC API calls to interact with Accumulo (instead of just the public API). Can point you in the right direction for examples if you're amenable

**Comment by lstav** [comment]
It would be interesting to see and try to write a test for it. I would appreciate if you point me in the right direction.

**Comment by joshelser** [comment]
> It would be interesting to see and try to write a test for it. I would appreciate if you point me in the right direction.

You've had a little bit of experience here, seeing what Thrift generates and how to implement the server-side interface.

At a high level, think about the Accumulo Java 'Public API' is a wrapper around the Thrift RPCs. Client-side, we also have the Thrift generated code. Typically, the public API call would call either `MasterClient.execute(..)`, `ServerClient.execute(..)`, or `ThriftUtil.getTServerClient(..)`. These calls are for Master RPCs, RPC to any TabletServer, or RPC to a specific TabletServer, specifically.

I would not worry about doing a low-level test case, instead, build some public API method and then write a test around that new method. I think adding a method to `InstanceOperations` makes the most sense here.

If we decide that we don't want to make a new public API call for this, using `MasterClient.execute` to invoke the `getMasterStats(..)` method. https://github.com/apache/accumulo/blob/e900e67425d950bd4c0c5288a6270d7b362ac458/core/src/main/java/org/apache/accumulo/core/client/impl/InstanceOperationsImpl.java#L69-L74 is an example of how to invoke this method. Hopefully this will be very straightforward to do with any of the existing test classes that extend AccumuloClusterIT.

**Comment by lstav** [comment]
Closing since the changes on this pull request are in #200

**Pull request closed without merging**
