### PR TITLE
Format functions.js

### PR DESCRIPTION
**Pull request by DomGarguilo**
This PR changes the formatting of functions.js to conform to the jslint formatting guidelines. 

These changes include:
* Changing indentation
* Adding brackets for all if statements
* Removing else statements where not needed
* Rearranging resources so they are defined before they are used

No logic in this file should be altered by these changes.

### CODE REVIEW

**Review by ctubbsii — CHANGES_REQUESTED** [review]
Can this be configured to use 2 space indent? 4 spaces is just excessive.

**Comment by milleruntime** [comment]
FYI It looks like you can specify an option when running `jslint`:
`npx jslint --indent 2 <file>`

**Comment by milleruntime** [comment]
It would be nice if we had something to run once to fix all the indentation on the JS. I will look to see if I can find anything.

**Comment by ctubbsii** [comment]
> It would be nice if we had something to run once to fix all the indentation on the JS. I will look to see if I can find anything.

Could put a script in contrib/ to do it. Or, make it run with an optional profile during the build and using exec-maven-plugin, if you have a command to do it.

**Comment by DomGarguilo** [comment]
> Can this be configured to use 2 space indent? 4 spaces is just excessive.

Addressed in [0f5ffed](https://github.com/apache/accumulo/pull/2711/commits/0f5ffed7987e396c999465b8cce0912615652d8f)

**Review by ctubbsii — APPROVED** [review]
I'm not a JavaScript expert, but these look okay to me.

**Review by milleruntime — APPROVED** [review]
LGTM. Were you able to use jslint with the indent option?

**Comment by DomGarguilo** [comment]
> LGTM. Were you able to use jslint with the indent option?

Yep. I used the command you mentioned earlier, thanks!

**Pull request merged**
