### PR TITLE
Drop FateAdmin classes

### PR DESCRIPTION
**Pull request by milleruntime**
Follow on for #2914 . The Fate operations code now lives in way too many places. The FateAdmin class should be dropped.

### CODE REVIEW

**Comment by milleruntime** [comment]
Left off the Project label but I think we should drop this in 2.1

**Comment by EdColeman** [comment]
Would it make sense for 2.1 if both classes were marked as deprecated and then point to the replacement?

I think the history was that the master version was / is deprecated because of the renaming to manager - I thought we were scheduled to fully remove master in 3.0 - but we need to leave some references in 2.1 because of semver?

I think the ideal way to handle this would be to have them print a deprecated warning and then call the equivalent new functionality - this would preserve compatibility from anyone coming from 1.10.x or 2.0.x to 2.1.0.

**Comment by EdColeman** [comment]
Between major, no so 2.x to 3.x allows incompatible API changes.
Minor, so 2.0 to 2.1, new functionality can be added in a backward compatible manor.

Not sure that FateAdmin is strictly considered public API, but that does not mean that we cannot preserve compatibility even if we "could" just drop it as people migrate to 2.1

**Comment by milleruntime** [comment]
FateAdmin is not API and is a server utility. There has been the deprecated message since version 1.6.6.

**Comment by milleruntime** [comment]
If there are no objections to dropping this class in 2.1, I will merge this PR.

**Comment by dlmarion** [comment]
I have no objection.

**Pull request merged**
