### PR TITLE
Log at debug when mini starts process

### PR DESCRIPTION
**Pull request by keith-turner**

### CODE REVIEW

**Comment by milleruntime** [comment]
This seems pretty useful for info level.  Is there another place where this gets logged as well?  Is this duplicate information?

**Comment by ctubbsii** [comment]
I think launching the process is useful at info, but not the whole environment for the process... that should be debug.

**Comment by keith-turner** [comment]
> This seems pretty useful for info level. Is there another place where this gets logged as well? Is this duplicate information?

When running Fluo's ITs against 2.0.0-alpha-1 there was a lot of stuff printed because of this log statement.  The classpath is what makes the log msg so long.  For each process mini starts, it logs which prints the classpath again.  So it prints alot and duplicates.

**Comment by keith-turner** [comment]
> I think the minimal information of what process is being started should be logged at info.

I don't think this is useful information.  The process may not even start.  I think what may be more useful would be if mini logged when processed unexpectedly exited.

**Comment by ctubbsii** [comment]
> I don't think this is useful information. The process may not even start. I think what may be more useful would be if mini logged when processed unexpectedly exited.

For a user who isn't 100% familiar with what Mini is *supposed* to be doing under the hood (casual users, users who aren't Accumulo developers, but application developers who use Accumulo), I think that the minimum information is very useful. I agree it would be even more useful to report unexpected exits... but log lines that establish that it *should* be running process X, Y, and Z, provide a base context in which a user is more easily able to understand error messages about unexpected exits of those processes.

**Comment by keith-turner** [comment]
I don't think log messages that repeatedly spam the same information every time a piece of software runs is a good way to document how that software works for new users.  Would be better to put this info in documentation.

**Comment by ctubbsii** [comment]
I argued for "minimal", not "spam".

**Comment by ctubbsii** [comment]
Weird. Yeah, I was tracking your repo as a remote. I saw you deleted like 60 or more branches. :smile:
Did you want to restore/reopen this one?

**Comment by keith-turner** [comment]
> Did you want to restore/reopen this one?

Yeah I am still interested in seeing the change made.

**Comment by ctubbsii** [comment]
Since the change is trivial, I would recommend just committing the change directly to the repo, with a reference back to this issue number, rather than bother to try to reopen the issue or create a new PR.

**Pull request closed without merging**
