### PR TITLE
fixes #3050 properly include last tablet that overlaps ample range

### LINKED ISSUE #3050: ShellServerIT.testCompactions seems to be pointing at metadata issue.
**Describe the bug**
The ShellServerIT.testCompactions test is failing

```
[ERROR] Tests run: 59, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 220.185 s <<< FAILURE! - in org.apache.accumulo.test.shell.ShellServerIT
[ERROR] org.apache.accumulo.test.shell.ShellServerIT.testCompactions  Time elapsed: 5.174 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <2> but was: <4>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
	at org.apache.accumulo.test.shell.ShellServerIT.testCompactions(ShellServerIT.java:757)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.api.AssertTimeoutPreemptively.lambda$submitTask$3(AssertTimeoutPreemptively.java:95)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

Adding logging shows the folloing files were found (when run in an IDE)

```
2022-10-26T19:26:05,260 [shell.ShellServerIT] DEBUG: countFiles(): root@miniInstance ShellServerIT_testCompactions0> scan -t accumulo.metadata -np -c file -b 1 -e 1~
1;f file:file:./workspace/wtree/v2.1/test/target/mini-tests/org.apache.accumulo.test.shell.ShellServerIT_SharedMiniClusterBase/accumulo/tables/1/default_tablet/A0000003.rf []	77,0
1< file:file:./workspace/wtree/v2.1/test/target/mini-tests/org.apache.accumulo.test.shell.ShellServerIT_SharedMiniClusterBase/accumulo/tables/1/default_tablet/A0000003.rf []	155,2
1< file:file:./workspace/wtree/v2.1/test/target/mini-tests/org.apache.accumulo.test.shell.ShellServerIT_SharedMiniClusterBase/accumulo/tables/1/default_tablet/F0000005.rf []	207,1
1< file:file:./workspace/wtree/v2.1/test/target/mini-tests/org.apache.accumulo.test.shell.ShellServerIT_SharedMiniClusterBase/accumulo/tables/1/default_tablet/F0000006.rf []	210,1

```

### PR DESCRIPTION
**Pull request by keith-turner**

### CODE REVIEW

**Comment by cshannon** [comment]
I'm testing this now.

**Comment by keith-turner** [comment]
The problem was the end range for overlapping.  If I have a table with splits g,r,z and I want the tablets that overlap the row range (i,s] then the tablets with end rows r,z would overlap.  However z sorts after s, so a metadata range with s would exclude z.

**Review by cshannon — APPROVED** [review]
This looks good to me so far, everything passes now locally.

I went ahead and kicked off a full IT build with this PR to make sure everything else is good to go which will be done in a few hours.

**Review by ctubbsii — APPROVED** [review]
Confirmed all the ITs are passing now.

**Pull request merged**
