### PR TITLE
Update formatter-maven-plugin to Eclipse Oxygen

### PR DESCRIPTION
**Pull request by ctubbsii**

### CODE REVIEW

**Comment by ctubbsii** [comment]
This actually doesn't even change any file formatting. Neon and Oxygen formatters were basically the same, if not identical.

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by milleruntime** [comment]
@ctubbsii I think this can be closed?  Looks like this change was already made in 646b059eb0b2de3bffe329d744c47bd9890103c7

**Comment by ctubbsii** [comment]
LOL, oops. I just pushed it. I didn't realize I still had an open PR.

**Pull request closed without merging**
