### PR TITLE
Update SingletonManager.java

### PR DESCRIPTION
**Pull request by Umang228**
Renamed method in SingletonManager

### CODE REVIEW

**Review by EdColeman — CHANGES_REQUESTED** [review]
You need to also change the place where that method was called.  Run
`mvn clean verify -DskipITs`
to verify your changes before updating your pull request.

**Comment by Umang228** [comment]
But there is only one rerservation which I corrected and  rest are correct

**Comment by EdColeman** [comment]
The QA build failed with a compilation error - symbol not found.  When you changed the name of the method, you also need to update all references to that name to the updated name - and those can be in other files. If you compile locally, the failure will tell you the files that need to be modified, or you can use the find references in your ide.

**Comment by billierinaldi** [comment]
> But there is only one rerservation which I corrected and rest are correct

@Umang228 The method is called from one other class, see [SingletonReservation.java](https://github.com/apache/accumulo/blob/f9bc91405ea4fb166d50d28a26d438265af5b554/core/src/main/java/org/apache/accumulo/core/singletons/SingletonReservation.java#L50)

**Comment by EdColeman** [comment]
The QA tests still failed - this cannot be merged until you can get a clean run.  Please verify locally before updating the PR.

**Comment by Umang228** [comment]
Sorry for that. Give me some time I messed up.

**Comment by EdColeman** [comment]
No worries - hopefully this is a good learning experience.  This is one reason I keep suggesting that you build locally - once you can do that then you are better positioned for future contributions.

**Comment by Umang228** [comment]
I dont know how to do locally. plz suggest me a guide ( video or steps ) to do that

**Comment by EdColeman** [comment]
See https://accumulo.apache.org/how-to-contribute/#example-contribution-workflow  But basically run
`mvn clean verify -DskipITs`
and get a clean build.

**Comment by Umang228** [comment]
Bro.... Accumulo start is failed to run . There are no errors in the file and also I didnt changed anything in start still its failed to run.
org.codehaus.mojo:exec-maven-plugin:3.0.0:exec  this is not executing. Plz help..

**Comment by EdColeman** [comment]
I do not understand what you mean by Accumulo start.  Please provide the commands that you are using, your java , maven and os versions.

**Comment by Umang228** [comment]
Accumulo start is a folder . The files in the folder are giving error in checks. And my IDE showing everything right (no errors).
Java -> version 13 , Maven -> version 3.8,  command -> mvn clean verify -DskipITs ...... Plz help asap.

**Comment by Umang228** [comment]
image

**Comment by EdColeman** [comment]
Assuming that by your drive name - this is windows?  The file that is trying to execute is a linux bash script.  I'm not sure that Accumulo will build on windows - do you have access linux vm?

**Comment by Umang228** [comment]
yes I have it.

**Comment by brianloss** [comment]
Yeah, I don't believe building on Windows is supported. I think you can try a cygwin or possible WSL environment, but little or no testing has been done with either of those as far as I am aware. If you have or can install Docker, then you could try building from a Docker container. Something like [maven](https://hub.docker.com/_/maven) would probably work if you volume mount your source directory.

**Comment by EdColeman** [comment]
If you have access to slack, you can sign up to the Accumulo channel using info provided here: https://accumulo.apache.org/contact-us/ - that might be easier for help.

**Comment by ctubbsii** [comment]
Superseded by #2061

**Pull request closed without merging**
