### PR TITLE
Fix for #1064.

### PR DESCRIPTION
**Pull request by keith-turner**

### CODE REVIEW

**Comment by milleruntime** [comment]
NativeMapIT passes with this fix on Fedora 28 with gcc-8.3.1-2.fc28.src.rpm

**Comment by ctubbsii** [comment]
This native code is hard to review for somebody used to looking at OO code. The native code is in desperate need of some sort of documented developer information to explain the overall design... even a few inline comments here and there to explain how the objects are supposed to be used would be helpful (For example, what is a SubKey? Or a Field? And what is going on with "blocks" vs. "bigBlocks" vectors that has been the cause of these last two bugs?)

I'm happy if the tests pass, but I don't have a lot of confidence that it's doing the right thing in all circumstances.

**Comment by milleruntime** [comment]
> This native code is hard to review for somebody used to looking at OO code. The native code is in desperate need of some sort of documented developer information to explain the overall design... even a few inline comments here and there to explain how the objects are supposed to be used would be helpful (For example, what is a SubKey? Or a Field? And what is going on with "blocks" vs. "bigBlocks" vectors that has been the cause of these last two bugs?)
> 
> I'm happy if the tests pass, but I don't have a lot of confidence that it's doing the right thing in all circumstances.

I agree.  Anything to make this code more maintainable would be very helpful.

**Comment by keith-turner** [comment]
@ctubbsii @milleruntime I added some comments to the code

**Comment by milleruntime** [comment]
I think this is good for 1.9.  For 2.0 can we refactor some of these variables to be more meaningful... like `linkBlockAllocator` instead of `lba`.

**Comment by keith-turner** [comment]
Github just goofed up my merge for #1070.  I pressed "squash and merge" and it said there was an error and presented a "try again" button.  So I pressed that and it did a merge commit instead of squashing.

**Comment by joshelser** [comment]
> Github just goofed up my merge for #1070. I pressed "squash and merge" and it said there was an error and presented a "try again" button. So I pressed that and it did a merge commit instead of squashing.
Can you revert and re-apply as a squash in the future? Running into this pain now :)

**Comment by keith-turner** [comment]
> Can you revert and re-apply as a squash in the future? Running into this pain now :)

I decided to just leave it in order to avoid as it was instead of doing a force push to fix it.

**Comment by joshelser** [comment]
> instead of doing a force push to fix it.

A revert of the previous commits and re-application of your commits as one wouldn't have required a force-push :)

**Comment by keith-turner** [comment]
> A revert of the previous commits and re-application of your commits as one wouldn't have required a force-push :)

Right.  I was being lazy and didn't fully explain what I meant by fix it.  From my perspective the problem at the time was that the merge made the history messier than it needed to be. I could not think of anything besides force push achieved my goal of making history cleaner, so I decided to just leave it.

**Comment by keith-turner** [comment]
> Can you revert and re-apply as a squash in the future? Running into this pain now :)

I suppose revert and re-apply with good commit messages explaining what happened could make history cleaner.

**Pull request merged**
