### PR TITLE
Bump Hadoop version from 3.3.6 to 3.4.0

### PR DESCRIPTION
**Pull request by dlmarion**

### CODE REVIEW

**Comment by DomGarguilo** [comment]
LGTM. I ran `-Psunny` without issue. Not sure what else should be considered when bumping hadoop though.

**Comment by dlmarion** [comment]
I don't think there is anything else to do here. The `maven-enforcer-plugin` should, in theory, catch dependency issues that might arise due to upstream dependency changes (introduction of banned dependencies, duplicates, etc.).

**Review by ctubbsii — COMMENTED** [review]
What's the motivation for this? We typically bump the minimum supported Hadoop version when there's newer Hadoop features we'd like to use, or if there's some code cleanup we can do (like removing some reflection to handle different versions). On it's own, I don't see any reason to drop support for 3.3.

**Review by ctubbsii — APPROVED** [review]
Oh wait, nevermind. This isn't the minimum supported version. It's the latest. We still test version 3.0 in the GitHub Actions builds (specifically, 3.0.3) for the minimum. I'm in favor of this change.

**Pull request merged**
