### PR TITLE
Fix TokenFile in MapReduce

### PR DESCRIPTION
**Pull request by milleruntime**
This removes the use of the hadoop DistributedCache.  It was no longer being used now with the Client properties doing the serialization of the token.  If we want to keep this functionality going into 2.0, then I can open a separate issue.  This PR at least makes the old API work with the new functionality in 2.0.

### CODE REVIEW

**Comment by milleruntime** [comment]
> we cannot simply read the file and store the credentials in the job configuration. That defeats the whole point of having the feature to use a token file.

I agree. I think the only way to fix this in the old API is to revert how we serialize the client properties. 

How do you propose handling the token file in the new API?

**Comment by ctubbsii** [comment]
> I agree. I think the only way to fix this in the old API is to revert how we serialize the client properties.

I think that's best.

> How do you propose handling the token file in the new API?

In the new API, we do not need to have a "Token File" feature at all. We already support serializing credentials into a client properties file. We just need to make sure that if a user sets the client properties file (vs. setting a token directly in the fluent API), we do not immediately read that file and store its contents as properties in the job. We should handle it either by putting the file in the distributed cache, or simply serialize the path to the file around so we can read it from HDFS directly in the input/output formats. This would basically mean protecting the contents of the client properties file in the new API the same way we treated the token file in the old API.

**Comment by milleruntime** [comment]
Reverting the old MR code back to using Connector becomes a problem down in the implementation in getSplits().  Because of other improvements in 2.0, we now need a ClientContext aka Client to create an OfflineScanner, Tablet Location and other places.  We have no a way to create a ClientContext or AccumuloClient without client properties.

**Comment by milleruntime** [comment]
OK maybe it will work with ClientConfConverter... let me try.

**Comment by milleruntime** [comment]
I think the ITs are still failing but ran so we can see errors: https://jenkins.revelc.net/job/Accumulo-PR/126/

**Comment by ctubbsii** [comment]
ConnectorImpl contains a ClientContext instance we can use.

**Pull request closed without merging**
