### PR TITLE
Change MasterTime to use currentTimeMillis. Fixes #1355

### LINKED ISSUE #1355: Anaylyze how MasterTime uses System.nanoTime
The master time class persist the output of System.nanoTime to zookeeper.  System.nanoTime should only be used to compute elapsed times in a single process.  The following is from its javadoc.

```
     * This method can only be used to measure elapsed time and is
     * not related to any other notion of system or wall-clock time.
     * The value returned represents nanoseconds since some fixed but
     * arbitrary <i>origin</i> time (perhaps in the future, so values
     * may be negative).  The same origin is used by all invocations of
     * this method in an instance of a Java virtual machine; other
     * virtual machine instances are likely to use a different origin.
```

I noticed this while looking at #1354.  Maybe the use of System.nanoTime is appropriate, I am not sure.  Opening this issue to remember to analyze its use.

### PR DESCRIPTION
**Pull request by milleruntime**
* System.nanoTime was being used for a persisted time value which could
be different upon restarts
* Time returned was also being converted to millis so no need for
nanosecond precision

### CODE REVIEW

**Comment by ctubbsii** [comment]
It might be worth backporting this to 1.x, if the tablet suspend feature exists there.

**Comment by keith-turner** [comment]
I looked over the code and I think the way it is using System.nanoTime is appropriate, because the use of skewTime makes the use of nanoTime always relative within a process.  This means the code should maintain a monotonically increasing counter as its javadoc suggest.  Below is an example of what the current code would do.

  * When never run before master process M1 puts 0 on ZK.  Assume M1 has nanoTime of 60E9, it will set its skewTime to 0 - 60E9 = -60E9.
   * 10 seconds later, master M1 has nanoTime of 70E9.  It will add its skew time and store that in ZK.  So it stores 70E9-60E9 = 10E9 in ZK.
   * Master M1 dies.  
   * 3 hours later master M2 starts.  It reads the current time from ZK as 10E9.  Assume master M2 has a nano time of 2500E9.  It will compute a skew time of 10E9 - 2500E9 = -2490E9.
   * 10 seconds later, M2 has a nanoTime of 2510E9.  It will add its skewTime and store that in ZK.  So it does 2510E9 - 2490E = 20E and stores that in ZK.

**Comment by milleruntime** [comment]
> I looked over the code and I think the way it is using System.nanoTime is appropriate, because the use of skewTime makes the use of nanoTime always relative within a process. This means the code should maintain a monotonically increasing counter as its javadoc suggest. Below is an example of what the current code would do.
> 
> * When never run before master process M1 puts 0 on ZK.  Assume M1 has nanoTime of 60E9, it will set its skewTime to 0 - 60E9 = -60E9.
> * 10 seconds later, master M1 has nanoTime of 70E9.  It will add its skew time and store that in ZK.  So it stores 70E9-60E9 = 10E9 in ZK.
> * Master M1 dies.
> * 3 hours later master M2 starts.  It reads the current time from ZK as 10E9.  Assume master M2 has a nano time of 2500E9.  It will compute a skew time of 10E9 - 2500E9 = -2490E9.

This is assuming that the M2 initial measurement of nano time is greater than the initial measurement of M1.  M2 will run in a different Java VM so there is no guarantee of how the second time will relate to the first time.

**Comment by keith-turner** [comment]
> M2 will run in a different Java VM so there is no guarantee of how the second time will relate to the first time.

I don't think the time between machines matters, because the way skewTime is used it makes everything relative within a process. Below is another scenario where M2 has a nanoTime less than M1.

 * M2 starts.  I reads the current time from ZK as 10E9.  M2 has a nanoTime of -4200E9.  It computes a skew time of 10E9 - (-4200E9) = 4210E9.
 * 10 seconds later, M2 writes -4190E9 + 4210E9 = 20E9 to ZK

**Comment by milleruntime** [comment]
> a monotonically increasing counter

This is exactly what System.currentTimeMillis is... and the function that returns this time, ```getTime``` drops the nano second precision by converting it to millis.  I don't see why we would want to use nano time over currentTimeMillis.

**Comment by keith-turner** [comment]
> I don't see why we would want to use nano time over currentTimeMillis.

System.currentTimeMillis can go backwards (if someone resets the time on a machine).  Differences computed by System.nanoTime will always increase, even if someone resets the time on the machine.  This code seems primarily concerned about the deltas and does not care about absolute times.

**Comment by milleruntime** [comment]
> > I don't see why we would want to use nano time over currentTimeMillis.
> 
> System.currentTimeMillis can go backwards (if someone resets the time on a machine). Differences computed by System.nanoTime will always increase, even if someone resets the time on the machine. This code seems primarily concerned about the deltas and does not care about absolute times.

OK I see. And I now see that it is only used for tracking tablet suspension.  The javadoc comments were misleading to me.

**Comment by ctubbsii** [comment]
I had a difficult time trying to figure out what the skewTime did. Thanks for explaining it with the examples, @keith-turner . Although it is mere subtraction, I find the code very confusing the way it is written.

**Pull request closed without merging**
