### PR TITLE
fixes bulk import filename prefix

### PR DESCRIPTION
**Pull request by keith-turner**
Before this change bulk import files ended up with a name like BULK_IMPORT000008h.rf after this change the name would be I000008h.rf instead.

### CODE REVIEW

**Comment by ctubbsii** [comment]
> > Does this affect 2.1? Should it be applied there first?
> 
> Looking at the 2.1 code I don't see the same problem, but I did not try running 2.1 and looking in the logs.
> 
> https://github.com/apache/accumulo/blob/2.1/server/manager/src/main/java/org/apache/accumulo/manager/tableOps/bulkVer2/PrepBulkImport.java#L246

Oh, I wonder which 3.0 change broke this, then.

**Review by ctubbsii — APPROVED** [review]

**Comment by ctubbsii** [comment]
Found it. Simple bug introduced in #3148, so it would not have been in 2.1.

**Comment by ctubbsii** [comment]
> Found it. Simple bug introduced in #3148, so it would not have been in 2.1. But I wonder if some of the other uses of these enums are also incorrect.

I reviewed all the uses of FilePrefix, and they all seem to be correct now. This was the only one that wasn't right.

**Comment by keith-turner** [comment]
> I reviewed all the uses of FilePrefix, and they all seem to be correct now.

Nice.  Suppose we could add an IT that verifies each file type has the expected prefix.

**Pull request merged**
