### PR TITLE
Adds test for multiple start events in WAL #1675

### PR DESCRIPTION
**Pull request by keith-turner**

### CODE REVIEW

**Comment by ctubbsii** [comment]
I closed / re-opened this PR to force the QA checks to run again after the main branch was updated. I expected the PR to sync automatically when main was updated, but it didn't seem to, so this forces it.

**Comment by milleruntime** [comment]
Actually, the fix I did in #1675 shouldn't affect how many start events get written to the WAL correct?  You just thought of this scenario while looking at that part of the code?

**Comment by keith-turner** [comment]
> Actually, the fix I did in #1675 shouldn't affect how many start events get written to the WAL correct? You just thought of this scenario while looking at that part of the code?

@milleruntime that is correct.  The while loop that could cause multiple start events already existed.  The changes you introduced added another exception scenario that could could cause multiple start events.  However there were pre-existing exception scenarios that could cause multiple start events.

**Comment by keith-turner** [comment]
@milleruntime the thing I noticed was `tablet.getNextMapFilename()` throws an IOException.  Moving that into the while loop adds another function to the while loop that throws IOException.

**Pull request merged**
