### PR TITLE
Update several dependencies to latest versions

### PR DESCRIPTION
**Pull request by cshannon**

### CODE REVIEW

**Comment by EdColeman** [comment]
@dlmarion - would it be feasible to have the teraform configuration inherit package versions from the main accumulo.pom - that would eliminate the need to manually sync configuration changes.

**Comment by dlmarion** [comment]
It's not just the code, it's the README as well. We could remove that from the README I guess. I'll create a ticket to investigate.

**Comment by dlmarion** [comment]
Created https://github.com/apache/accumulo-testing/issues/246

**Comment by cshannon** [comment]
> Updating OpenTelemetry and Micrometer here requires an update in the Terraform code in accumulo-testing. You can look at the prior commits in accumulo-testing to see what needs to change.

Done: https://github.com/apache/accumulo-testing/pull/247

**Review by dlmarion — APPROVED** [review]
LGTM

**Comment by cshannon** [comment]
I'll merge once the checks finish

**Comment by cshannon** [comment]
> I may have found a few more that could be included here. I'll make a PR against this branch soon.

I will just merge this one and if you find some more you can open another PR against main

**Pull request merged**
