### PR TITLE
ACCUMULO-4699 Fixed queued work key in replication

### PR DESCRIPTION
**Pull request by milleruntime**
Hoping someone more familiar with the replication code can make sure this was a bug...

### CODE REVIEW

**Comment by joshelser** [comment]
This part of the code is meant to handle the case when the active master changes while there data out to be replicated. The Master should initialize itself with the current state of ZooKeeper to know what has already been assigned out for replication (by the previous active Master).

I can see that this bug would result in the Master holding onto some memory that it would never free (in the Map), and it would result in the Master trying to submit it back out to the cluster. However, I think eventually the Master (or TabletServer which took the work task) would see that there is no more work to be done and eventually clean up the record.

I believe, by nature of the DistributedWorkQueue, there is sufficient exclusion to prevent two TabletServers from concurrently trying to replicate the same WAL. However, I believe the worst case would be that we inadvertently replicate the entire WAL twice.

Would be nice to add a test for this method and not commit as-is.

**Comment by milleruntime** [comment]
Created ACCUMULO-4697 for this issue.

**Comment by joshelser** [comment]
> Would be nice to add a test for this method and not commit as-is.

:\

**Comment by milleruntime** [comment]
> :\

Sorry I don't understand the replication process well enough to write a test.  I am not even sure what to test.  If you can describe the test, I will create a follow on ticket.

**Comment by joshelser** [comment]
```java
       Map<String,String> replicationForPeer = queuedWorkByPeerName.get(peerName);
       if (null == replicationForPeer) {
         replicationForPeer = new HashMap<>();
-        queuedWorkByPeerName.put(sourceTableId, replicationForPeer);
+        queuedWorkByPeerName.put(peerName, replicationForPeer);
       }
```

I think it would be pretty easy to unit test `initializeQueuedWork()` -- `DistributedWorkQueueWorkAssignerHelper` already exists with helper methods to handle the serialization. You don't need to write some end-to-end case that uses a real Accumulo instance.

You might have to mock out some more methods in SequentialWorkAssigner (e.g. `workQueue.getWorkQueued()`), but it strikes me as being straightforward. If it's not, please ask a more specific question about what still confuses you.

> Sorry I don't understand the replication process well enough to write a test.

I was more frustrated that I saw this was merged with my comment being ignored. It's fine if you don't know how to address a test (we all face this).

**Comment by ctubbsii** [comment]
Careful not to assume a comment is ignored, versus other options, such as "thought I already responded", "overlooked/missed", "still trying to parse", "still formulating a response", or "in process of investigating and writing a follow on test as requested".

**Comment by joshelser** [comment]
I think we have the situation completely under control without your social corrections

**Comment by ctubbsii** [comment]
@joshelser I was attempting to gently remind you to "assume good intentions", as stated in the ASF Code of Conduct, enforcement of which, is everyone's responsibility. Assuming good intentions is something I frequently fail at... and sometimes need extra help pointing out when I fail. I thought that perhaps you might also appreciate the heads up when you did it. Sorry.

**Comment by joshelser** [comment]
I really didn't want to get sucked into another argument, but here we go again:

* I made a statement was essentially "-0" (would prefer this to not be merged as-is)
* The change was merged as-is without further comment
* I made a comment two-hours later expressing my disappointment (via an emoticon)
* A comment was received and the barrier to "fixing" my -0 was shared
* I provided (what I think was) a helpful comment to overcoming that barrier

I honestly do not understand why you are quoting me "assume good intentions". Good intentions have nothing to do with this situation -- I saw something which I thought was not ideal and said something about it.

The fact that the majority of my interactions here are boiling down to arguments over things other than code make me think I need to more aggressively step away.

**Comment by milleruntime** [comment]
> I made a statement was essentially "-0" (would prefer this to not be merged as-is)

That is my mistake.  I took your comments as +0.  Then I merged the PR without the intention of writing a test.  

As far as the test goes, I appreciate your explanations but I don't think we need a test for this fix.  It is not new code and the only reason I opened the PR was for someone else more familiar with replication to take a look at it.  The only thing I was going to do further was to open up a JIRA ticket for follow on work of creating a test if you thought it was needed.

**Comment by ctubbsii** [comment]
What I hear when I hear someone say they were "ignored" is an accusation of active malicious intent on the part of another to dismiss. If this is not what you meant by "ignore", and you simply meant "lack of response", then my caution was entirely unwarranted, and this was all a misunderstanding because words mean different things to different people. No big deal. Sorry for the trouble. Please move on.

**Comment by joshelser** [comment]
> That is my mistake. I took your comments as +0. Then I merged the PR without the intention of writing a test.

Not an issue, that's why I dropped the ":\" in the first place and didn't leave any sort of flame ;). I thought it was a simple way to just grab your attention. The distinction between -0 and +0 is pretty vague and I'm not going to fault anyone for assuming the opposite. It really wasn't as big of an issue as it's blown up to be.

> As far as the test goes, I appreciate your explanations but I don't think we need a test for this fix. It is not new code..

I'd disagree with you on the above point, but, I don't feel strongly enough to -1 your commit, so I'll (likely) think that I should write one myself for a few weeks until I forget about it :)

**Comment by milleruntime** [comment]
> I'll (likely) think that I should write one myself for a few weeks until I forget about it :)

Haha sounds good

**Pull request merged**
